### ISSUE TITLE
Helidon Tracing config processing does not strip trailing whitespace

### ISSUE THREAD

**Issue by pfmackin** [oracle/helidon#1012]
Helidon Version: 1.2.1
Helidon MP 
JDK version: 1.8.0_211  
OS: MacOS 10.13.6  
Problem Description:  Tracing does not strip whitespace from tracing.host config, which results in an exception when starting the server.  I ran into problem when testing the Tracing Guide, since I am cutting and pasting from the guide into the IDE and it picks up a trailing space.  The same thing happened with tracing.service and it was not obvious why I could not get traces using the REST API for that service.

Steps to reproduce:
1) Create a quickstart project using MP archetype and add the following to 
META-INF/microprofile-config.properties.  Make sure there is a space after localhost.

tracing.service=helidon-mp
tracing.host=localhost 

2) Start the app and you will see the following exception:
java -jar target/helidon-quickstart-mp.jar

Exception in thread "main" java.lang.IllegalArgumentException: Invalid Zipkin endpoint: http://localhost :9411/api/v2/spans
	at io.helidon.tracing.zipkin.ZipkinTracerBuilder.createEndpoint(ZipkinTracerBuilder.java:395)
	at io.helidon.tracing.zipkin.ZipkinTracerBuilder.createSender(ZipkinTracerBuilder.java:400)
	at io.helidon.tracing.zipkin.ZipkinTracerBuilder.build(ZipkinTracerBuilder.java:294)
	at io.helidon.microprofile.tracing.MpTracingService.configure(MpTracingService.java:40)
	at io.helidon.microprofile.server.ServerImpl.lambda$loadExtensions$7(ServerImpl.java:216)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at io.helidon.microprofile.server.ServerImpl.loadExtensions(ServerImpl.java:215)
	at io.helidon.microprofile.server.ServerImpl.<init>(ServerImpl.java:115)
	at io.helidon.microprofile.server.Server$Builder.doBuild(Server.java:264)
	at io.helidon.common.context.Contexts.runInContext(Contexts.java:118)
	at io.helidon.microprofile.server.Server$Builder.build(Server.java:202)
	at io.helidon.microprofile.server.Server.create(Server.java:94)
	at io.helidon.examples.quickstart.mp.Main.startServer(Main.java:55)
	at io.helidon.examples.quickstart.mp.Main.main(Main.java:42)
Caused by: java.net.URISyntaxException: Illegal character in authority at index 7: http://localhost :9411/api/v2/spans
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.parseAuthority(URI.java:3186)
	at java.net.URI$Parser.parseHierarchical(URI.java:3097)
	at java.net.URI$Parser.parse(URI.java:3053)
	at java.net.URI.<init>(URI.java:673)
	at io.helidon.tracing.zipkin.ZipkinTracerBuilder.createEndpoint(ZipkinTracerBuilder.java:386)

**Comment by spericas** [comment]
There are lots of places in Helidon where config strings are read and not _trimmed_. It seems a bit inconsistent to just address this for host names in tracing. Should we make this consistent everywhere or categorize this issue as _pilot error_ and not fix it?

**Comment by pfmackin** [comment]
I think it should be fixed everywhere, trailing whitespace should always be trimmed from user input.

**Comment by spericas** [comment]
@pfmackin We had a discussion in our team meeting and concluded that there are some risks in introducing a whitespace-trimming logic: (1) It is not how `Properties::load` works, it preserves all trailing spaces (I verified this too) and (2) It is hard to be consistent across config sources (JSON, YAML, etc). So this is a _won't fix_, at least for now.
