### ISSUE TITLE
Helidon Tracing config not using Env vars.

### ISSUE THREAD

**Issue by pfmackin** [oracle/helidon#1013]
Helidon Version: 1.2.1
Helidon MP 
JDK version: 1.8.0_211  
OS: MacOS 10.13.6  
Problem Description: I set the TRACING_SERVICE env var and it is not being used by the Helidon app.

Steps to reproduce:

1) docker run -d --name zipkin -p 9411:9411 openzipkin/zipkin
2) Create a quickstart project using MP archetype 
3) Add tracing dependency to pom.xml
<dependency>
  <groupId>io.helidon.tracing</groupId>
  <artifactId>helidon-tracing-zipkin</artifactId>
</dependency>

4) mvn package -DskipTests=true
5) export TRACING_SERVICE=helidon-mp-1
6) java -jar target/helidon-quickstart-mp.jar

Exception in thread "main" java.lang.NullPointerException: Service name must be defined, either programmatically or in configuration using key "service"
	at java.util.Objects.requireNonNull(Objects.java:228)
	at io.helidon.tracing.zipkin.ZipkinTracerBuilder.build(ZipkinTracerBuilder.java:287)
	at io.helidon.microprofile.tracing.MpTracingService.configure(MpTracingService.java:40)
	at io.helidon.microprofile.server.ServerImpl.lambda$loadExtensions$7(ServerImpl.java:216)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at io.helidon.microprofile.server.ServerImpl.loadExtensions(ServerImpl.java:215)
	at io.helidon.microprofile.server.ServerImpl.<init>(ServerImpl.java:115)
	at io.helidon.microprofile.server.Server$Builder.doBuild(Server.java:264)
	at io.helidon.common.context.Contexts.runInContext(Contexts.java:118)
	at io.helidon.microprofile.server.Server$Builder.build(Server.java:202)
	at io.helidon.microprofile.server.Server.create(Server.java:94)
	at io.helidon.examples.quickstart.mp.Main.startServer(Main.java:55)
	at io.helidon.examples.quickstart.mp.Main.main(Main.java:42)
Weld SE container 8acc4353-7999-49e1-9989-1e10319e50da shut down by shutdown hook

Now and do the following.  You will see that tracing works.

1)  add tracing.service=helidon-mp-1 to META-INF/microprofile-config.properties
2)  mvn package -DskipTests=true
3) java -jar target/helidon-quickstart-mp.jar
4) curl http://localhost:8080/greet
5) go to http://localhost:9411/zipkin and see the trace.

**Comment by tomas-langer** [comment]
This problem is fixed in latest version of Helidon (1.3.1) and in `master`.
