### ISSUE TITLE
Listing Java Module dependencies (OpenJDK 13 and later) in Helidon SE Quickstart fails

### ISSUE THREAD

**Issue by c16a** [oracle/helidon#1120]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version: 1.3.1
* Helidon SE
* JDK version
```
openjdk version "13" 2019-09-17
OpenJDK Runtime Environment AdoptOpenJDK (build 13+33)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 13+33, mixed mode, sharing)
```
* OS: Ubuntu 19.04

----------

## Problem Description
The quickstart Helidon SE application generated by the Maven archetype successfully runs, but it is not able to list the java modules it depends on

## Steps to reproduce
```
mvn archetype:generate -DinteractiveMode=false \
    -DarchetypeGroupId=io.helidon.archetypes \
    -DarchetypeArtifactId=helidon-quickstart-se \
    -DarchetypeVersion=1.3.1 \
    -DgroupId=io.helidon.examples \
    -DartifactId=helidon-quickstart-se \
    -Dpackage=io.helidon.examples.quickstart.se
```

Attempt to list the java module dependencies
```
jdeps --list-deps target/**/*.jar 
```

### Encountered error
```
Exception in thread "main" java.lang.module.FindException: Module microprofile.health.api not found, required by io.helidon.health
	at java.base/java.lang.module.Resolver.findFail(Resolver.java:877)
	at java.base/java.lang.module.Resolver.resolve(Resolver.java:191)
	at java.base/java.lang.module.Resolver.resolve(Resolver.java:140)
	at java.base/java.lang.module.Configuration.resolve(Configuration.java:422)
	at java.base/java.lang.module.Configuration.resolve(Configuration.java:256)
	at jdk.jdeps/com.sun.tools.jdeps.JdepsConfiguration$Builder.build(JdepsConfiguration.java:564)
	at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.buildConfig(JdepsTask.java:603)
	at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.run(JdepsTask.java:557)
	at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.run(JdepsTask.java:533)
	at jdk.jdeps/com.sun.tools.jdeps.Main.main(Main.java:49)

```

**Comment by tomas-langer** [comment]
This is related to JPMS and to the fact, that a lot of libraries do not have a proper `module-info` file defined.
Even though Helidon libraries have `module-info`, we still depend on a lot of libraries that act as "automatic modules" - e.g. the module name is "guessed" from the library name.
One of these libraries is MicroProfile Health (in fact all MP specifications have this problem).

Until all libraries we depend on use `module-info`, tools such as `jlink` will not work correctly.

We are working hard on a solution for Helidon users to have a custom tool for building `jlink` libraries, let's hope we do not encounter any show stoppers for this effort.

**Comment by c16a** [comment]
Is it something we can contribute towards? Any pointers on how to start off?

**Comment by barchetta** [comment]
As stated by Tomas this is a limitation of the Java ecosystem -- many open source libraries are not yet Java modules. Not much we can do about this. For this reason I'm closing this issue.

The custom tool mentioned is experimental, and it's not clear if the benefits of the tool are worth the complexity.
