### ISSUE TITLE
RestClient with Exception Mapper is not working as expected...

### ISSUE THREAD

**Issue by zarub2k** [oracle/helidon#1147]
DailyApiExceptionMapper is my Exception Mapper defined to handle my application level Exception (DailyApiException).

I have my method like the below,

```java
public void create(Country country) throws DailyApiException {
        if (country.getCode() == null || country.getCode().isEmpty()) {
            throw new DailyApiException(400, "Country code should not be empty");
        }
}
```

My unit test:
I have created my RestClient like the following,

```java
RestClientBuilder.newBuilder()
                .baseUri(new URI(HOST))
                .register(DailyApiExceptionMapper.class)
                .build(ICountryApi.class);
```

```java
   @Test
    @DisplayName("Method to test create() without country code")
    public void testCreateWithoutCode() {
        final Country country = new Country("", "Test", "Test Capital");
        try {
            countryApi.create(country);
        } catch (DailyApiException e) {
            assertEquals(400, e.getCode(), "Country code should be given");
        }
    }
```

But my test fails with the following error. I am not be able to get the proper exception in my unit test. How can I get the proper exception in my unit test?

Result from unit test:

```
javax.ws.rs.WebApplicationException: Unknown error, status code 400
	at org.glassfish.jersey.microprofile.restclient.DefaultResponseExceptionMapper.toThrowable(DefaultResponseExceptionMapper.java:32)
	at org.glassfish.jersey.microprofile.restclient.MethodModel.evaluateResponse
```

Any clue?

**Comment by spericas** [comment]
@zarub2k Would it be possible for you to share some runnable code? Perhaps a Github link?

**Comment by spericas** [comment]
@zarub2k Any update on that runnable code? If I don't hear back, I'll assume you've resolved the issue and close it.

**Comment by spericas** [comment]
@zarub2k Please re-open if this is still an issue.

**Comment by zarub2k** [comment]
I am sorry. I was on travel so I couldn't get time to look into this issue. Please find the required details.

Mapper class:
--------------
@Provider
@Produces(MediaType.APPLICATION_JSON)
public class DailyApiExceptionMapper implements ExceptionMapper<DailyApiException> {
    @Override
    public Response toResponse(DailyApiException e) {
        Map<String, Object> entities = new HashMap<>();
        entities.put("code", e.getCode());
        entities.put("message", e.getMessage());
        return Response
                .status(e.getCode())
                .entity(entities)
                .build();
    }
}

API class:
@Path("/users")
public interface IUserApi {
    @POST
    @Consumes(MediaType.APPLICATION_JSON)
    Response create(JsonObject userJson) throws DailyApiException;
}

@RequestScoped
public class UserApi implements IUserApi {
    @Inject UserManager userManager;

    @Override
    public Response create(JsonObject userJson) throws DailyApiException {
        userManager.create(userJson);

        return Response
                .status(Response.Status.CREATED)
                .build();
    }
}

Junit:
------
@Test
    public void testCreate() throws DailyApiException {
        final JsonObject userJson = Json.createObjectBuilder()
                .add("email", "test@gmail.com")
                .add("password", "test123")
                .build();
        final Response response = userApi.create(userJson);
        System.out.println(response.getStatus());
        assertEquals(201, response.getStatus(), "Response code should be 201");
    }

Failure result:
javax.ws.rs.WebApplicationException: Unknown error, status code 500

	at org.glassfish.jersey.microprofile.restclient.DefaultResponseExceptionMapper.toThrowable(DefaultResponseExceptionMapper.java:32)
	at org.glassfish.jersey.microprofile.restclient.MethodModel.evaluateResponse(MethodModel.java:437)
	at org.glassfish.jersey.microprofile.restclient.MethodModel.synchronousCall(MethodModel.java:232)
	at org.glassfish.jersey.microprofile.restclient.MethodModel.invokeMethod(MethodModel.java:202)
	at org.glassfish.jersey.microprofile.restclient.InterceptorInvocationContext.proceed(InterceptorInvocationContext.java:110)
	at org.glassfish.jersey.microprofile.restclient.RestClientModel.invokeMethod(RestClientModel.java:91)
	at org.glassfish.jersey.microprofile.restclient.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:70)
	at com.sun.proxy.$Proxy37.create(Unknown Source)
	at com.hustlebar.dailyapi.api.user.UserApiTest.testCreate(UserApiTest.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:436)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:170)
	at org.junit.jupiter.engine.execution.ThrowableCollector.execute(ThrowableCollector.java:40)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:166)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:113)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:58)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$3(HierarchicalTestExecutor.java:112)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.executeRecursively(HierarchicalTestExecutor.java:108)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.execute(HierarchicalTestExecutor.java:79)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$2(HierarchicalTestExecutor.java:120)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$3(HierarchicalTestExecutor.java:120)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.executeRecursively(HierarchicalTestExecutor.java:108)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.execute(HierarchicalTestExecutor.java:79)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$2(HierarchicalTestExecutor.java:120)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$3(HierarchicalTestExecutor.java:120)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.executeRecursively(HierarchicalTestExecutor.java:108)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.execute(HierarchicalTestExecutor.java:79)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:55)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:43)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:170)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:154)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)

**Comment by zarub2k** [comment]
I am not able to open this issue...

**Comment by zarub2k** [comment]
This issue is tagged with 'cannot reproduce'. Are you still facing any trouble reproducing this problem?

**Comment by spericas** [comment]
@zarub2k No, we did not get to it yet. Will remove tag.

**Comment by spericas** [comment]
@zarub2k Looking at the additional code you provided, I think there may be a confusion here between client and server code. The type `ExceptionMapper` is only server side; the dual for the Rest Client API is called `ResponseExceptionMapper`. The former maps a server-side exception to a `Response`, the latter a `Response` received from the server to a client-side exception.

Despite seeing just pieces of your code, it seems from the original description of the problem that you want a client-side exception to be thrown, in which case you'd need to implement a `ResponseExceptionMapper`. Can you please check that?

**Comment by zarub2k** [comment]
@spericas I have already implemented the Exception Mapper in the server side. I would like to catch the exception even through the Client SDK. When I simulate the same scenario through Postman client, I am getting the proper exception based on the mapper i defined in the server side. I can open the complete code (permission to you) to you if you need more details. I believe I am missing some fundamental things in the code or configuration. Let me know how to take this forward.

**Comment by spericas** [comment]
@zarub2k Have you looked at `ResponseExceptionMapper::toThrowable`? You need an instance of _that mapper_ in your client config to get an exception on the client. The registration of `DailyApiExceptionMapper.class` in `RestClientBuilder` has no effect. The server is going to return a 400 code, and you should map that to a `DailyApiException` on the client side in your `ResponseExceptionMapper` implementation.

**Comment by zarub2k** [comment]
I am extremely sorry for asking. I have no idea on this. Do you have any reference to enhance this? I thought adding the exception mapper into our client builder will internally handle this behavior.

**Comment by spericas** [comment]
See the section about `ResponseExceptionMapper` here:

https://download.eclipse.org/microprofile/microprofile-rest-client-1.0/microprofile-rest-client.pdf

**Comment by zarub2k** [comment]
I will look into this and try the steps in my client code.

**Comment by spericas** [comment]
Let me know how it goes, if there's an issue, we can re-open.
