### ISSUE TITLE
Conflicts between @Transaction and @Fallback

### ISSUE THREAD

**Issue by spericas** [oracle/helidon#1171]
Originally reported by Tim Graves. The issue is not just with `@Fallback` but any FT annotation that results in Hystrix creating a new thread. The `@Transaction` logic is pinned to a thread, so if a new thread is created and contexts are not copied, an error is reported as shown below:

```2019.11.21 22:58:55 INFO org.jboss.weld.Version Thread[main,5,main]: WELD-000900: 3.1.1 (Final) 
2019.11.21 22:58:55 INFO org.jboss.weld.Bootstrap Thread[main,5,main]: WELD-ENV-000020: Using jandex for bean discovery 
2019.11.21 22:58:55 INFO org.jboss.weld.Event Thread[main,5,main]: WELD-000411: Observer method [BackedAnnotatedMethod] public org.glassfish.jersey.ext.cdi1x.internal.ProcessAllAnnotatedTypes.processAnnotatedType(@Observes ProcessAnnotatedType<?>, BeanManager) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds. 
2019.11.21 22:58:55 INFO org.jboss.weld.Event Thread[main,5,main]: WELD-000411: Observer method [BackedAnnotatedMethod] private io.helidon.microprofile.openapi.IndexBuilder.processAnnotatedType(@Observes ProcessAnnotatedType<X>) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds. 
2019.11.21 22:58:56 INFO org.jboss.weld.Bootstrap Thread[main,5,main]: WELD-ENV-002003: Weld SE container 7a7a6808-2bed-4aa9-a37d-e7eabe1590e9 initialized 
2019.11.21 22:58:56 INFO io.helidon.tracing.zipkin.ZipkinTracerBuilder Thread[main,5,main]: Creating Zipkin Tracer for 'stockmanager' configured with: http://zipkin:9411/api/v2/spans 
2019.11.21 22:58:56 INFO io.smallrye.openapi.api.OpenApiDocument Thread[main,5,main]: OpenAPI document initialized: io.smallrye.openapi.api.models.OpenAPIImpl@4cb40e3b 
2019.11.21 22:58:57 INFO io.helidon.webserver.NettyWebServer Thread[main,5,main]: Version: 1.3.1 
2019.11.21 22:58:57 INFO io.helidon.webserver.NettyWebServer Thread[nioEventLoopGroup-2-1,10,main]: Channel 'admin' started: [id: 0xd5af5261, L:/0:0:0:0:0:0:0:0:9081] 
2019.11.21 22:58:57 INFO io.helidon.webserver.NettyWebServer Thread[nioEventLoopGroup-2-2,10,main]: Channel '@default' started: [id: 0xcbf40f06, L:/0:0:0:0:0:0:0:0:8081] 
2019.11.21 22:58:57 INFO io.helidon.microprofile.server.ServerImpl Thread[nioEventLoopGroup-2-2,10,main]: Server started on http://localhost:8081 (and all other host addresses) in 96 milliseconds. 
http://localhost:8081/stocklevel 
2019.11.21 22:59:05 INFO com.arjuna.ats.arjuna Thread[helidon-1,5,server]: ARJUNA012170: TransactionStatusManager started on port 52985 and host 127.0.0.1 with service com.arjuna.ats.arjuna.recovery.ActionStatusService 
2019.11.21 22:59:05 WARNING com.netflix.config.sources.URLConfigurationSource Thread[helidon-1,5,server]: No URLs will be polled as dynamic configuration sources. 
2019.11.21 22:59:05 INFO com.netflix.config.sources.URLConfigurationSource Thread[helidon-1,5,server]: To enable URLs as dynamic configuration sources, define System property archaius.configurationSource.additionalUrls or make config.properties available on classpath. 
2019.11.21 22:59:05 INFO com.netflix.config.DynamicPropertyFactory Thread[helidon-1,5,server]: DynamicPropertyFactory is initialized with configuration sources: com.netflix.config.ConcurrentCompositeConfiguration@69056e94 
2019.11.21 22:59:06 INFO io.helidon.microprofile.faulttolerance.CommandRetrier Thread[helidon-1,5,server]: About to execute command with key createStockLevel2061748247 on thread helidon-1 
2019.11.21 22:59:06 INFO com.oracle.labs.helidon.stockmanager.resources.StockResource Thread[hystrix-io.helidon.microprofile.faulttolerance-1,5,server]: Creating StockId(departmentName=TestOrg, itemName=rivete), with count 500 
2019.11.21 22:59:06 INFO org.hibernate.jpa.internal.util.LogHelper Thread[hystrix-io.helidon.microprofile.faulttolerance-1,5,server]: HHH000204: Processing PersistenceUnitInfo [ 
    name: HelidonATPJTA 
    ...] 
2019.11.21 22:59:06 INFO org.hibernate.Version Thread[hystrix-io.helidon.microprofile.faulttolerance-1,5,server]: HHH000412: Hibernate Core {5.2.12.Final} 
2019.11.21 22:59:06 INFO org.hibernate.cfg.Environment Thread[hystrix-io.helidon.microprofile.faulttolerance-1,5,server]: HHH000206: hibernate.properties not found 
2019.11.21 22:59:06 INFO org.hibernate.annotations.common.Version Thread[hystrix-io.helidon.microprofile.faulttolerance-1,5,server]: HCANN000001: Hibernate Commons Annotations {5.0.1.Final} 
2019.11.21 22:59:06 INFO com.zaxxer.hikari.HikariDataSource Thread[hystrix-io.helidon.microprofile.faulttolerance-1,5,server]: HikariPool-1 - Starting... 
2019.11.21 22:59:09 INFO com.zaxxer.hikari.HikariDataSource Thread[hystrix-io.helidon.microprofile.faulttolerance-1,5,server]: HikariPool-1 - Start completed. 
2019.11.21 22:59:09 INFO org.hibernate.dialect.Dialect Thread[hystrix-io.helidon.microprofile.faulttolerance-1,5,server]: HHH000400: Using dialect: org.hibernate.dialect.Oracle10gDialect 
Hibernate: 
    select 
        stocklevel0_.departmentName as departmentName1_0_0_, 
        stocklevel0_.itemName as itemName2_0_0_, 
        stocklevel0_.itemCount as itemCount3_0_0_ 
    from 
        StockLevel stocklevel0_ 
    where 
        stocklevel0_.departmentName=? 
        and stocklevel0_.itemName=? 
2019.11.21 22:59:12 INFO com.oracle.labs.helidon.stockmanager.resources.StockResource Thread[hystrix-io.helidon.microprofile.faulttolerance-1,5,server]: Creating StockLevel(stockId=StockId(departmentName=TestOrg, itemName=rivete), itemCount=500) 
javax.persistence.TransactionRequiredException 
    at io.helidon.integrations.cdi.jpa.NonTransactionalEntityManager.persist(NonTransactionalEntityManager.java:92)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498) 
    at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38)
    at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:106)
    at org.jboss.weldx.persistence.EntityManager$197475146$Proxy$_$$_WeldClientProxy.persist(Unknown Source) 
    at io.helidon.integrations.cdi.jpa.DelegatingEntityManager.persist(DelegatingEntityManager.java:156)
    at com.oracle.labs.helidon.stockmanager.resources.StockResource.createStockLevel(StockResource.java:187)
    at com.oracle.labs.helidon.stockmanager.resources.StockResource$Proxy$_$$_WeldSubclass.createStockLevel$$super(Unknown Source) 
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498) 
    at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:51)
    at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:78)
    at io.helidon.common.context.Contexts.runInContextWithThrow(Contexts.java:142)
    at io.helidon.microprofile.faulttolerance.FaultToleranceCommand.run(FaultToleranceCommand.java:248)
    at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:302) 
    at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:298) 
    at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46) 
    at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35) 
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) 
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) 
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) 
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) 
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) 
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ```

**Comment by atimgraves** [comment]
Attached is a simple project using an in memory database that demonstrates this 
[helidon-fallback-transaction-eclipse.zip](https://github.com/oracle/helidon/files/3897468/helidon-fallback-transaction-eclipse.zip)

**Comment by spericas** [comment]
So far I've only explored copying some thread local vars using some very ugly code. This solution works, but requires a lot of code gymnastics. See here for more info,

https://github.com/spericas/helidon/commit/85f73cb45675de78536447f87afed152989adfbc

We need to find a cleaner solution for Helidon. I have one more idea to explore; I'll report back in a few days.

**Comment by spericas** [comment]
We no longer use Hystrix in Helidon 2.1. There's a good chance that this is no longer a problem, although there may be other problems related to `@Transaction`. I'm going to close this issue and we can open a new one if necessary.
