### ISSUE TITLE
Unable to find reusable metric with tags

### ISSUE THREAD

**Issue by spericas** [oracle/helidon#1238]
Error reported:

```
http://localhost:8080/greet
2019.12.17 09:32:48 WARNING io.helidon.microprofile.server.ServerImpl.jersey Thread[helidon-1,5,server]: Internal server error
java.lang.IllegalStateException: No counter with name [iss_greeter_messages_retrieved_total] found in registry [application: 8 metrics]
	at io.helidon.microprofile.metrics.InterceptorBase.lambda$called$0(InterceptorBase.java:132)
	at java.base/java.util.Optional.orElseGet(Optional.java:369)
	at io.helidon.microprofile.metrics.InterceptorBase.called(InterceptorBase.java:131)
	at io.helidon.microprofile.metrics.InterceptorBase.aroundMethod(InterceptorBase.java:108)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
```

Source code:

```
    @GET
    @Produces(MediaType.APPLICATION_JSON)
    @Counted(name = "iss_greeter_messages_retrieved_total", absolute=true,reusable = true, tags = {prd_name, prd_app, prd_svc, prd_cst})
    public JsonObject getDefaultMessage() { ...
    }

    @Path("/{name}")
    @GET
    @Produces(MediaType.APPLICATION_JSON)
    @Counted(name = "iss_greeter_messages_retrieved_total", absolute=true, reusable = true, tags = {prd_name, prd_app, prd_svc, prd_cst})
    public JsonObject getMessage(@PathParam("name") String name) {...
    }
```

**Comment by tjquinno** [comment]
Fixed.
