### ISSUE TITLE
Test Helidon with java 8u41 with ALPN patch

### ISSUE THREAD

**Issue by m0mus** [oracle/helidon#1285]
To make sure that we are fine. Helidon 1.x only.

**Comment by spericas** [comment]
Based on information received via e-mail, I'm using 8u251 instead. Helidon's behavior has changed as compared to an older version, such as 8u212. See below:

```JDK 8u212

java.lang.RuntimeException: ALPN unsupported. Is your classpath configured correctly? For Conscrypt, add the appropriate Conscrypt JAR to classpath and set the security provider. For Jetty-ALPN, see http://www.eclipse.org/jetty/documentation/current/alpn-chapter.html#alpn-starting
    at io.netty.handler.ssl.JdkAlpnApplicationProtocolNegotiator$FailureWrapper.wrapSslEngine(JdkAlpnApplicationProtocolNegotiator.java:122)
    at io.netty.handler.ssl.JdkSslContext.configureAndWrapEngine(JdkSslContext.java:360)
    at io.netty.handler.ssl.JdkSslContext.newEngine(JdkSslContext.java:330)
    ...


JDK 8u251 EA (ALPN Support)

java.lang.NoClassDefFoundError: org/eclipse/jetty/alpn/ALPN$Provider
    at io.netty.handler.ssl.JettyAlpnSslEngine.newServerEngine(JettyAlpnSslEngine.java:60)
    at io.netty.handler.ssl.JdkAlpnApplicationProtocolNegotiator$AlpnWrapper.wrapSslEngine(JdkAlpnApplicationProtocolNegotiator.java:141)
    at io.netty.handler.ssl.JdkSslContext.configureAndWrapEngine(JdkSslContext.java:360)
    at io.netty.handler.ssl.JdkSslContext.newEngine(JdkSslContext.java:330)```

Netty has some logic to determine on which JDK it is running. With the latest 8u251, because of the newly added support, it concludes it is running on JDK 8 with ALPN support provide by Jetty but fails to find Jetty's ALPN provider.

Based on this analysis, it seems we'd need a Netty update before we can run on top of 8u251. In other words, it seems Netty needs to be aware of this JDK change as well.

**Comment by spericas** [comment]
Here is the code in Netty that determines it is running in JDK 8 with Jetty: in class `JettyAlpnSslEngine`,

```
    private static boolean initAvailable() {
        if (PlatformDependent.javaVersion() <= 8) {
            try {
                // Always use bootstrap class loader.
                Class.forName("sun.security.ssl.ALPNExtension", true, null);
                return true;
            } catch (Throwable ignore) {
                // alpn-boot was not loaded.
            }
        }
        return false;
    }
```

**Comment by spericas** [comment]
Aside for the issue described above with ALPN, all other tests that use TLS are passing.

**Comment by spericas** [comment]
I will close this issue and file one in Netty to add support for 8u251.
