### ISSUE TITLE
Uber Jar created from maven-shade-plugin failed on application startup

### ISSUE THREAD

**Issue by vinodpahuja** [oracle/helidon#1358]
## Environment Details
* Helidon Version: 1.4.1
* Helidon MP
* JDK version: Open JDK 8
* OS: Window 10

----------

### Plugin :

```
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-shade-plugin</artifactId>
	<executions>
		<execution>
			<phase>package</phase>
			<goals>
				<goal>shade</goal>
			</goals>
			<configuration>
				<transformers>
					<transformer
						implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
						<mainClass>${mainClass}</mainClass>
					</transformer>
					<transformer
						implementation="org.apache.maven.plugins.shade.resource.IncludeResourceTransformer">
						<resource>META-INF/beans.xml</resource>
					</transformer>
				</transformers>
			</configuration>
		</execution>
	</executions>
</plugin>
```

## Console output
```
Feb 06, 2020 6:08:13 PM io.helidon.microprofile.server.Main configureLogging
INFO: Logging configured using defaults
Feb 06, 2020 6:08:13 PM org.jboss.weld.bootstrap.WeldStartup <clinit>
INFO: WELD-000900: 3.1.1 (Final)
Feb 06, 2020 6:08:14 PM org.jboss.weld.environment.deployment.discovery.DiscoveryStrategyFactory create
INFO: WELD-ENV-000020: Using jandex for bean discovery
Feb 06, 2020 6:08:18 PM org.jboss.weld.bootstrap.WeldStartup startContainer
INFO: WELD-000101: Transactional services not available. Injection of @Inject UserTransaction not available. Transactional observers will be invoked synchronously.
Exception in thread "main" org.jboss.weld.exceptions.DeploymentException: Exception List with 2 exceptions:
Exception 0 :
org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type double with qualifiers @ConfigProperty
  at injection point [BackedAnnotatedParameter] Parameter 2 of [BackedAnnotatedConstructor] @Inject io.helidon.health.checks.DiskSpaceHealthCheck(@ConfigProperty File, @ConfigProperty double)
  at io.helidon.health.checks.DiskSpaceHealthCheck.<init>(DiskSpaceHealthCheck.java:0)

        at org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:378)
        at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:290)
        at org.jboss.weld.bootstrap.Validator.validateGeneralBean(Validator.java:143)
        at org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:164)
        at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:526)
        at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:64)
        at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:62)
        at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:62)
        at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:55)
        at org.jboss.weld.executor.CommonForkJoinPoolExecutorServices.lambda$wrap$0(CommonForkJoinPoolExecutorServices.java:70)
        at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

## Steps to reproduce
mvn clean package 
java -jar target\microservice-starter-helidon.jar

[//]: # "Provide sample code/application if relevant"
https://github.com/ERS-HCL/microservice-starter/tree/master/microservice-starter-helidon

**Comment by tomas-langer** [comment]
Hello, in general we prefer (and support) deployment with multiple jars (as is created with our quickstarts), due to issues with resources in an uber jar (as you may have the same resources, such as `microprofile-config.properties` in multiple jar files. Also `beans.xml` are quite critical, as some of the extensions may not work correctly when in a jar that contains `beans.xml`.

Nevertheless I will investigate the issue you have encountered.

**Comment by tomas-langer** [comment]
The problem (at least part of it) is that you do not combine the `META-INF/services/*` files. Helidon uses the Java service loader quite heavily and your combined jar file contains only one implementation for each service.

**Comment by tomas-langer** [comment]
You can run your application, but you need to exclude some features from Helidon (as these depend on the `beans.xml` not being present in their jar file.
Change your dependency on Helidon as follows:
```xml
<dependency>
			<groupId>io.helidon.microprofile.bundles</groupId>
			<artifactId>helidon-microprofile</artifactId>
			<exclusions>
				<exclusion>
					<groupId>io.helidon.microprofile.tracing</groupId>
					<artifactId>helidon-microprofile-tracing</artifactId>
				</exclusion>
				<exclusion>
					<groupId>io.helidon.microprofile.metrics</groupId>
					<artifactId>helidon-microprofile-metrics2</artifactId>
				</exclusion>
				<exclusion>
					<groupId>io.helidon.microprofile.jwt</groupId>
					<artifactId>helidon-microprofile-jwt-auth-cdi</artifactId>
				</exclusion>
				<exclusion>
					<groupId>io.helidon.microprofile</groupId>
					<artifactId>helidon-microprofile-fault-tolerance</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
```

Modify your shade plugin configuration as follows:
```xml
<transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
```

**Comment by tomas-langer** [comment]
I have submitted a new issue #1362 so we can follow up on the problems you mentioned here.

**Comment by tomas-langer** [comment]
Also in version 2.0 (we have a milestone build for that - 2.0.0-M1) we have fixed the media type detection in Helidon, so config should work a bit better.

**Comment by tomas-langer** [comment]
https://github.com/ERS-HCL/microservice-starter/pull/5

**Comment by tomas-langer** [comment]
Closing this issue as 
 - the application now works (even though some Helidon features are not available)
 - we have a follow up issue to fix the remaining features
