### ISSUE TITLE
Some modules do not work with shaded jars in CDI

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#1362]
The following modules add beans using an extension and fail when `beans.xml` is part of their jar file, such as when using Maven shade plugin to create a shaded jar.

- [ ] `helidon-microprofile-tracing`
- [ ] `helidon-microprofile-metrics2`
- [ ] `helidon-microprofile-jwt-auth-cdi`

And maybe 
- [ ] `helidon-microprofile-fault-tolerance` (could not test, as it depends on metrics)

We should implement our extension in a way that is safe when running in a shaded jar.
This requires removal of bean defining annotations (such as `@ApplicationScoped`) and adding these explicitly when adding the bean in the extension.

This is based on version 1.4.1
May be partially resolved in `master`, requires verification

**Comment by tomas-langer** [comment]
I have removed the `bug` label, as we do not support this deployment style. Nevertheless we can fix these as there is no technical need to handle things the way we do.

**Comment by tomas-langer** [comment]
Tried with current master. Metrics, health and openapi works, Jersey does not.
```
2021.10.04 19:44:52 WARNING io.helidon.microprofile.server.JaxRsCdiExtension Thread[helidon-1,5,server]: Internal server error
org.jboss.weld.contexts.ContextNotActiveException: WELD-001303: No active contexts for scope type javax.enterprise.context.RequestScoped
	at org.jboss.weld.manager.BeanManagerImpl.getContext(BeanManagerImpl.java:647)
	at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.getIfExists(ContextualInstanceStrategy.java:89)
	at org.jboss.weld.bean.ContextualInstanceStrategy$CachingContextualInstanceStrategy.getIfExists(ContextualInstanceStrategy.java:164)
	at org.jboss.weld.bean.ContextualInstance.getIfExists(ContextualInstance.java:63)
	at org.jboss.weld.bean.proxy.ContextBeanInstance.getInstance(ContextBeanInstance.java:87)
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.getInstance(ProxyMethodHandler.java:131)
	at me.tomas.mp.quickstart.GreetResource$Proxy$_$$_WeldClientProxy.getDefaultMessage(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:475)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:397)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255)
```

As we do not intend to support this type of deployment, I will close this issue.
If this packaging is important for you, please re-open the issue.
