### ISSUE TITLE
-Dexit.on.started=! does not exit on Helidon 2.0.0-M1

### ISSUE THREAD

**Issue by batsatt** [oracle/helidon#1373]
Setting this property when starting an MP app does not exit the process.

The shutdown hander thread is blocked:
```
"helidon-cdi-shutdown-hook" #27 prio=5 os_prio=31 cpu=2.86ms elapsed=29.47s tid=0x00007fbfec07e800 nid=0xc303 waiting for monitor entry  [0x00007000032ac000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at org.jboss.weld.event.ExtensionObserverMethodImpl.sendEvent(ExtensionObserverMethodImpl.java:122)
	- waiting to lock <0x000000070c200c80> (a org.jboss.weld.Container)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:308)
	at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:286)
	at javax.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:124)
	at org.jboss.weld.util.Observers.notify(Observers.java:166)
	at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:285)
	at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:273)
	at org.jboss.weld.event.EventImpl.fire(EventImpl.java:96)
	at io.helidon.microprofile.cdi.HelidonContainerImpl$HelidonCdi.close(HelidonContainerImpl.java:336)
	at io.helidon.microprofile.cdi.HelidonContainerImpl.lambda$doStart$4(HelidonContainerImpl.java:262)
	at io.helidon.microprofile.cdi.HelidonContainerImpl$$Lambda$575/0x00000008003b9840.run(Unknown Source)
	at java.lang.Thread.run(java.base@11.0.6/Thread.java:834)
```
while the main thread holds lock `<0x000000070c200c80>`:
```
"main" #1 prio=5 os_prio=31 cpu=3473.76ms elapsed=33.26s tid=0x00007fbfeb801800 nid=0x1c03 waiting on condition  [0x0000000110845000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.6/Native Method)
	- parking to wait for  <0x000000070d249e00> (a java.util.concurrent.CompletableFuture$Signaller)
	at java.util.concurrent.locks.LockSupport.park(java.base@11.0.6/LockSupport.java:194)
	at java.util.concurrent.CompletableFuture$Signaller.block(java.base@11.0.6/CompletableFuture.java:1796)
	at java.util.concurrent.ForkJoinPool.managedBlock(java.base@11.0.6/ForkJoinPool.java:3128)
	at java.util.concurrent.CompletableFuture.waitingGet(java.base@11.0.6/CompletableFuture.java:1823)
	at java.util.concurrent.CompletableFuture.get(java.base@11.0.6/CompletableFuture.java:1998)
	at io.helidon.microprofile.server.ServerCdiExtension.startServer(ServerCdiExtension.java:128)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@11.0.6/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@11.0.6/NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@11.0.6/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@11.0.6/Method.java:566)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95)
	at org.jboss.weld.injection.MethodInvocationStrategy$SpecialParamPlusBeanManagerStrategy.invoke(MethodInvocationStrategy.java:187)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:330)
	at org.jboss.weld.event.ExtensionObserverMethodImpl.sendEvent(ExtensionObserverMethodImpl.java:123)
	- locked <0x000000070c200c80> (a org.jboss.weld.Container)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:308)
	at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:286)
	at javax.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:124)
	at org.jboss.weld.util.Observers.notify(Observers.java:166)
	at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:285)
	at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:273)
	at org.jboss.weld.event.EventImpl.fire(EventImpl.java:96)
	at io.helidon.microprofile.cdi.HelidonContainerImpl.doStart(HelidonContainerImpl.java:297)
	at io.helidon.microprofile.cdi.HelidonContainerImpl$$Lambda$471/0x0000000800378040.call(Unknown Source)
	at io.helidon.common.context.Contexts.runInContext(Contexts.java:118)
	at io.helidon.microprofile.cdi.HelidonContainerImpl.start(HelidonContainerImpl.java:223)
	at io.helidon.microprofile.server.ServerImpl.start(ServerImpl.java:88)
	at io.helidon.examples.quickstart.mp.Main.startServer(Main.java:58)
	at io.helidon.examples.quickstart.mp.Main.main(Main.java:45)
```
and the nio thread on which the `System.exit(0)` call is made is blocked waiting on the logging cleaner:
```
"nioEventLoopGroup-2-1" #44 prio=10 os_prio=31 cpu=21.47ms elapsed=29.49s tid=0x00007fbfeb5e2000 nid=0xbd03 in Object.wait()  [0x00007000030a5000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(java.base@11.0.6/Native Method)
	- waiting on <0x00000007001aea60> (a java.util.logging.LogManager$Cleaner)
	at java.lang.Thread.join(java.base@11.0.6/Thread.java:1305)
	- waiting to re-lock in wait() <0x00000007001aea60> (a java.util.logging.LogManager$Cleaner)
	at java.lang.Thread.join(java.base@11.0.6/Thread.java:1379)
	at java.lang.ApplicationShutdownHooks.runHooks(java.base@11.0.6/ApplicationShutdownHooks.java:107)
	at java.lang.ApplicationShutdownHooks$1.run(java.base@11.0.6/ApplicationShutdownHooks.java:46)
	at java.lang.Shutdown.runHooks(java.base@11.0.6/Shutdown.java:130)
	at java.lang.Shutdown.exit(java.base@11.0.6/Shutdown.java:174)
	- locked <0x00000007001ad3d0> (a java.lang.Class for java.lang.Shutdown)
	at java.lang.Runtime.exit(java.base@11.0.6/Runtime.java:113)
	at java.lang.System.exit(java.base@11.0.6/System.java:1749)
	at io.helidon.webserver.NettyWebServer.started(NettyWebServer.java:269)
	at io.helidon.webserver.NettyWebServer$$Lambda$815/0x000000080052f840.accept(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(java.base@11.0.6/CompletableFuture.java:714)
	at java.util.concurrent.CompletableFuture.postComplete(java.base@11.0.6/CompletableFuture.java:506)
	at java.util.concurrent.CompletableFuture.complete(java.base@11.0.6/CompletableFuture.java:2073)
	at io.helidon.webserver.NettyWebServer.lambda$start$7(NettyWebServer.java:247)
	at io.helidon.webserver.NettyWebServer$$Lambda$820/0x000000080052a840.operationComplete(Unknown Source)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:984)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:566)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:504)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:489)
	at io.netty.handler.logging.LoggingHandler.bind(LoggingHandler.java:177)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:504)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:489)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:973)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:248)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:348)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(java.base@11.0.6/Thread.java:834)
```
and the logging cleaner is waiting on the shutdown hook thread to exit:
```
"Logging-Cleaner" #12 prio=5 os_prio=31 cpu=0.28ms elapsed=29.47s tid=0x00007fbfee8be800 nid=0xc003 in Object.wait()  [0x00007000031a9000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(java.base@11.0.6/Native Method)
	- waiting on <0x000000070c200fb0> (a java.lang.Thread)
	at java.lang.Thread.join(java.base@11.0.6/Thread.java:1305)
	- waiting to re-lock in wait() <0x000000070c200fb0> (a java.lang.Thread)
	at java.lang.Thread.join(java.base@11.0.6/Thread.java:1379)
	at io.helidon.microprofile.cdi.HelidonContainerImpl$2.close(HelidonContainerImpl.java:282)
	at java.util.logging.LogManager.closeHandlers(java.logging@11.0.6/LogManager.java:1470)
	at java.util.logging.LogManager.resetLogger(java.logging@11.0.6/LogManager.java:1485)
	at java.util.logging.LogManager.resetLoggerContext(java.logging@11.0.6/LogManager.java:1460)
	at java.util.logging.LogManager.reset(java.logging@11.0.6/LogManager.java:1445)
	at java.util.logging.LogManager$Cleaner.run(java.logging@11.0.6/LogManager.java:282)
```

**Comment by batsatt** [comment]
Here is the entire stack dump: [mp-2.0.0-M1.log](https://github.com/oracle/helidon/files/4182421/mp-2.0.0-M1.log)
