### ISSUE TITLE
Quickstart MP native image has dependency on jar file

### ISSUE THREAD

**Issue by barchetta** [oracle/helidon#1578]
## Environment Details
* Helidon Version: 2.0.0-SNAPSHOT
* Helidon MP
* JDK version: 11
----------

## Problem Description
During testing for PR #1576 I ran into the following problem. The native image builds successfully but if you run the resulting executable without the existence of `target/helidon-quickstart-mp.jar`  you get the following error:
```
Exception in thread "main" javax.enterprise.inject.spi.DeploymentException: Failed to obtain index view
	at io.helidon.microprofile.openapi.OpenApiCdiExtension.registerOpenApi(OpenApiCdiExtension.java:119)
...
Caused by: java.io.IOException: Attempted to read from previously-located index file jar:file:/home/jdipol/GitHub/barchetta/helidon/examples/quickstarts/helidon-quickstart-mp/target/helidon-quickstart-mp.jar!/META-INF/jandex.idx but the file cannot be found
	at io.helidon.microprofile.openapi.OpenApiCdiExtension.existingIndexFileReader(OpenApiCdiExtension.java:163)
	at io.helidon.microprofile.openapi.OpenApiCdiExtension.indexView(OpenApiCdiExtension.java:147)
	at io.helidon.microprofile.openapi.OpenApiCdiExtension.registerOpenApi(OpenApiCdiExtension.java:112)
...
Caused by: java.nio.file.NoSuchFileException: /home/jdipol/GitHub/barchetta/helidon/examples/quickstarts/helidon-quickstart-mp/target/helidon-quickstart-mp.jar
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
...
	at io.helidon.microprofile.openapi.OpenApiCdiExtension.existingIndexFileReader(OpenApiCdiExtension.java:159)
```

If you build `target/helidon-quickstart-mp.jar` then the native image starts correctly.

**Comment by tomas-langer** [comment]
This looks like you built the "backup" native image, that is actually a wrapper of a jar file and starts normal java.

**Comment by tomas-langer** [comment]
The index file needs to be located through classpath resource, not through file system.

**Comment by tjquinno** [comment]
The Jandex indexes were indeed located using the classpath, but that happened at build-time in the native image scenario, and their URLs were cached and reused later which fails at native image runtime.
