### ISSUE TITLE
Unable to initialize gRPC service when using helidon-microprofile-metrics2

### ISSUE THREAD

**Issue by rlubke** [oracle/helidon#1618]
Environment Details
* Helidon Version: 1.4.4
* Helidon MP
* JDK version: 1.8.0_241
* OS: MacOS Catalina
* Docker version (if applicable): N/A

----------

When using the following dependency configuration:

```xml
        <dependency>
            <groupId>io.helidon.microprofile.grpc</groupId>
            <artifactId>helidon-microprofile-grpc-metrics</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>io.helidon.microprofile.metrics</groupId>
                    <artifactId>helidon-microprofile-metrics</artifactId>
                </exclusion>
            </exclusions>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>io.helidon.microprofile.metrics</groupId>
            <artifactId>helidon-microprofile-metrics2</artifactId>
            <scope>provided</scope>
        </dependency>
```

Results in an `IllegalAccessError` being raised stating `MetricUtil` isn't accessible from `MetricsConfigurer`

```
Caused by: java.lang.IllegalAccessError: tried to access class io.helidon.microprofile.metrics.MetricUtil$MatchingType from class io.helidon.microprofile.grpc.metrics.MetricsConfigurer
	at io.helidon.microprofile.grpc.metrics.MetricsConfigurer.addMetric(MetricsConfigurer.java:108)
	at io.helidon.microprofile.grpc.metrics.MetricsConfigurer.addMeter(MetricsConfigurer.java:93)
	at io.helidon.microprofile.grpc.metrics.MetricsConfigurer.lambda$accept$5(MetricsConfigurer.java:73)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
```

**Comment by tjquinno** [comment]
@rlubke reports that he feels this is no longer worth fixing. Closing.
