### ISSUE TITLE
Loading ssl config with nested config fails

### ISSUE THREAD

**Issue by gcameo** [oracle/helidon#1685]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version: 2.0.0-M1
* Helidon SE
* JDK version: 11
* OS: Mac
* Docker version (if applicable):

----------

## Problem Description
When running with SSL, using nested config fails to locate resources although documentation in the code suggests using the old format is legacy and may be removed

## Steps to reproduce
The commented out format works but the nested hierarchy version fails

```
app:
  greeting: "Hello"
server:
  port: 443
  host: 0.0.0.0
  ssl:
    private-key:
      #pem-key-resource-path: "privateKey.pem"
      pem-cert-chain-resource-path: "full-chain-withkey-certchain.pem"
      pem:
        key:
          resource:
            path: "privateKey.pem"
```
Leads to the following exception

```
Exception in thread "main" java.lang.RuntimeException: Private key not available
	at io.helidon.webserver.SSLContextBuilder.lambda$buildKmf$0(SSLContextBuilder.java:174)
	at java.base/java.util.Optional.orElseThrow(Optional.java:401)
	at io.helidon.webserver.SSLContextBuilder.buildKmf(SSLContextBuilder.java:174)
	at io.helidon.webserver.SSLContextBuilder.newSSLContext(SSLContextBuilder.java:144)
	at io.helidon.webserver.SSLContextBuilder.build(SSLContextBuilder.java:133)
	at io.helidon.webserver.SSLContextBuilder.create(SSLContextBuilder.java:79)
	at io.helidon.webserver.ServerConfiguration$Builder.configureSocket(ServerConfiguration.java:552)
```

**Comment by tomas-langer** [comment]
The configuration is slightly different than you have in your code.
The following will work if your `*.pem` files are on the classpath:
```yaml
server:
  port: 443
  host: 0.0.0.0
  ssl:
    private-key:
      pem:
        key:
          resource.resource-path: "privateKey.pem"
        cert-chain:
          resource.resource-path: "full-chain-withkey-certchain.pem"
```
If you `*.pem` files are on the file system, you would use `resource.path` instead of `resource.resource-path`.
