### ISSUE TITLE
oci-objectstorage example throws StackOverflowError

### ISSUE THREAD

**Issue by barchetta** [oracle/helidon#1704]
## Environment Details
* Helidon Version: 2.0-SNAPSHOT
* Helidon MP
* JDK version: 11
----------

## To Reproduce

```
cd integrations/cdi/oci-objectstorage
mvn clean package
java -jar target/helidon-examples-integrations-cdi-oci-objectstorage.jar
Apr 29, 2020 9:02:55 PM io.helidon.microprofile.cdi.LogConfig doConfigureLogging
INFO: Logging at initialization configured using defaults
Apr 29, 2020 9:02:55 PM org.jboss.weld.bootstrap.WeldStartup <clinit>
INFO: WELD-000900: 3.1.3 (Final)
Exception in thread "main" java.util.ServiceConfigurationError: io.helidon.config.spi.ConfigMapperProvider: io.helidon.config.objectmapping.ObjectConfigMapperProvider Unable to get public no-arg constructor
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:581)
	at java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:672)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1232)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1264)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1299)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1384)
	at java.base/java.lang.Iterable.forEach(Iterable.java:74)
	at io.helidon.common.serviceloader.HelidonServiceLoader$Builder.build(HelidonServiceLoader.java:167)
	at io.helidon.config.BuilderImpl.loadMapperServices(BuilderImpl.java:677)
	at io.helidon.config.BuilderImpl.buildMappers(BuilderImpl.java:656)
	at io.helidon.config.BuilderImpl.build(BuilderImpl.java:342)
	at io.helidon.config.MpConfigBuilder.build(MpConfigBuilder.java:81)
	at io.helidon.config.MpConfigProviderResolver.buildConfig(MpConfigProviderResolver.java:93)
	at io.helidon.config.MpConfigProviderResolver.getConfig(MpConfigProviderResolver.java:68)
	at io.helidon.config.MpConfigProviderResolver.getConfig(MpConfigProviderResolver.java:51)
	at org.eclipse.microprofile.config.ConfigProvider.getConfig(ConfigProvider.java:93)
	at io.helidon.integrations.cdi.oci.objectstorage.OciConfigConfigSource.getValue(OciConfigConfigSource.java:106)
	at io.helidon.config.BuilderImpl$PrioritizedMpSource.priority(BuilderImpl.java:893)
	at java.base/java.util.Comparator.lambda$comparingInt$7b0bb60$1(Comparator.java:490)
	at java.base/java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)

... blah...blah..blah...

Caused by: java.lang.StackOverflowError
	at java.base/java.lang.Class.getConstructor0(Class.java:3342)
	at java.base/java.lang.Class.getConstructor(Class.java:2151)
	at java.base/java.util.ServiceLoader$1.run(ServiceLoader.java:659)
	at java.base/java.util.ServiceLoader$1.run(ServiceLoader.java:656)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:667)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1232)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1264)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1299)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1384)
	at java.base/java.lang.Iterable.forEach(Iterable.java:74)
	at io.helidon.common.serviceloader.HelidonServiceLoader$Builder.build(HelidonServiceLoader.java:167)
	at io.helidon.config.BuilderImpl.loadMapperServices(BuilderImpl.java:677)
	at io.helidon.config.BuilderImpl.buildMappers(BuilderImpl.java:656)
	at io.helidon.config.BuilderImpl.build(BuilderImpl.java:342)
	at io.helidon.config.MpConfigBuilder.build(MpConfigBuilder.java:81)
	at io.helidon.config.MpConfigProviderResolver.buildConfig(MpConfigProviderResolver.java:93)
	at io.helidon.config.MpConfigProviderResolver.getConfig(MpConfigProviderResolver.java:68)
	at io.helidon.config.MpConfigProviderResolver.getConfig(MpConfigProviderResolver.java:51)
	at org.eclipse.microprofile.config.ConfigProvider.getConfig(ConfigProvider.java:93)

. . .
```

**Comment by ljnelson** [comment]
Thanks; we should check this under 1.4.4 as well since I don’t think the OCI-related code has changed. I’ll look at this Thursday morning.
