### ISSUE TITLE
ServerRequest injection fails in ContainerRequestFilter

### ISSUE THREAD

**Issue by dansiviter** [oracle/helidon#1739]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version: 1.4.4
* Helidon SE or Helidon MP: MP
* JDK version: 8
* OS: All
* Docker version (if applicable): N/A

----------

## Problem Description
When attempting to use `io.helidon.webserver.ServerRequest` within a `javax.ws.rs.ext.ContainerRequestFilter` Helidon fails to start up:

```
Exception in thread "main" MultiException stack 1 of 1
java.lang.IllegalStateException: Not inside a request scope.
        at org.glassfish.jersey.internal.guava.Preconditions.checkState(Preconditions.java:169)
        at org.glassfish.jersey.process.internal.RequestScope.current(RequestScope.java:153)
        at org.glassfish.jersey.inject.hk2.RequestContext.findOrCreate(RequestContext.java:55)
        at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2102)
        at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:93)
        at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:67)
        at org.glassfish.jersey.inject.hk2.ContextInjectionResolverImpl.resolve(ContextInjectionResolverImpl.java:103)
        at org.jvnet.hk2.internal.Utilities.justInject(Utilities.java:988)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.inject(ServiceLocatorImpl.java:998)
        at org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.inject(AbstractHk2InjectionManager.java:207)
        at org.glassfish.jersey.inject.hk2.ImmediateHk2InjectionManager.inject(ImmediateHk2InjectionManager.java:30)
        at org.glassfish.jersey.ext.cdi1x.internal.AbstractCdiBeanSupplier$2.getInstance(AbstractCdiBeanSupplier.java:88)
        at org.glassfish.jersey.ext.cdi1x.internal.AbstractCdiBeanSupplier._provide(AbstractCdiBeanSupplier.java:103)
        at org.glassfish.jersey.ext.cdi1x.internal.GenericCdiBeanSupplier.get(GenericCdiBeanSupplier.java:42)
        at org.glassfish.jersey.inject.hk2.InstanceSupplierFactoryBridge.provide(InstanceSupplierFactoryBridge.java:53)
        at org.jvnet.hk2.internal.FactoryCreator.create(FactoryCreator.java:129)
        at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:463)
        at org.jvnet.hk2.internal.PerLookupContext.findOrCreate(PerLookupContext.java:46)
        at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2102)
        at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:93)
        at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:67)
        at org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.lambda$getAllServiceHolders$0(AbstractHk2InjectionManager.java:136)       
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1239)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.getAllServiceHolders(AbstractHk2InjectionManager.java:140)
        at org.glassfish.jersey.inject.hk2.ImmediateHk2InjectionManager.getAllServiceHolders(ImmediateHk2InjectionManager.java:30)
        at org.glassfish.jersey.internal.inject.Providers.getServiceHolders(Providers.java:299)
        at org.glassfish.jersey.internal.inject.Providers.getAllRankedProviders(Providers.java:182)
        at org.glassfish.jersey.server.ProcessingProvidersConfigurator.postInit(ProcessingProvidersConfigurator.java:95)
        at org.glassfish.jersey.server.ApplicationHandler.lambda$initialize$2(ApplicationHandler.java:349)
        at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4390)
        at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:349)
        at org.glassfish.jersey.server.ApplicationHandler.lambda$initialize$1(ApplicationHandler.java:293)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
        at org.glassfish.jersey.internal.Errors.processWithException(Errors.java:232)
        at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:292)
        at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:259)
        at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:246)
        at io.helidon.webserver.jersey.JerseySupport.<init>(JerseySupport.java:132)
        at io.helidon.webserver.jersey.JerseySupport$Builder.build(JerseySupport.java:451)
        at io.helidon.microprofile.server.JaxRsCdiExtension.toJerseySupport(JaxRsCdiExtension.java:275)
        at io.helidon.microprofile.server.ServerCdiExtension.addApplication(ServerCdiExtension.java:257)
        at io.helidon.microprofile.server.ServerCdiExtension.lambda$registerJaxRsApplications$2(ServerCdiExtension.java:161)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at io.helidon.microprofile.server.ServerCdiExtension.registerJaxRsApplications(ServerCdiExtension.java:161)
        at io.helidon.microprofile.server.ServerCdiExtension.startServer(ServerCdiExtension.java:113)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95)
        at org.jboss.weld.injection.MethodInvocationStrategy$SpecialParamPlusBeanManagerStrategy.invoke(MethodInvocationStrategy.java:187)       
        at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:330)
        at org.jboss.weld.event.ExtensionObserverMethodImpl.sendEvent(ExtensionObserverMethodImpl.java:123)
        at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:308)
        at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:286)
        at javax.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:124)
        at org.jboss.weld.util.Observers.notify(Observers.java:166)
        at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:285)
        at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:273)
        at org.jboss.weld.event.EventImpl.fire(EventImpl.java:96)
        at io.helidon.microprofile.cdi.HelidonContainerImpl.doStart(HelidonContainerImpl.java:304)
        at io.helidon.common.context.Contexts.runInContext(Contexts.java:118)
        at io.helidon.microprofile.cdi.HelidonContainerImpl.start(HelidonContainerImpl.java:232)
        at io.helidon.microprofile.cdi.Main.main(Main.java:61)
```
I also cannot see any other way to get a handle of `ServerRequest` as it doesn't appear in the `io.helidon.common.context.Context` either.

## Steps to reproduce

1. Inject `ServerRequest` into a `ContainerRequestFilter`. For example:

```
import javax.ws.rs.container.ContainerRequestContext;
import javax.ws.rs.container.ContainerRequestFilter;
import javax.ws.rs.core.Context;
import javax.ws.rs.ext.Provider;

import io.helidon.webserver.ServerRequest;

@Provider
public class RemoteAddrFilter implements ContainerRequestFilter {
	@Context
	private ServerRequest req;
	
	@Override
	public void filter(ContainerRequestContext requestContext) {
		System.out.println(req.remoteAddress());
	}
}
``` 
2. Start server

The error appears to be due to how Jersey performs pre-flight checks on injectable types on filters.

**Comment by dansiviter** [comment]
I've just tried using `io.helidon.webserver.ServerResponse` and that works. I wonder if this is due to the difference in approach as:
* `ServerRequest`: `.proxy(false)`
* `ServerRespose`: `.proxy(true).proxyForSameScope(false)`

https://github.com/oracle/helidon/blob/1.4.4/webserver/jersey/src/main/java/io/helidon/webserver/jersey/WebServerBinder.java#L44,L52

**Comment by tomas-langer** [comment]
Merged into 1.x

**Comment by tomas-langer** [comment]
@dansiviter thanks for this contribution
