### ISSUE TITLE
Zipkin Client parent span name is "UNKNOWN"

### ISSUE THREAD

**Issue by jansupol** [oracle/helidon#1962]
Having an endpoint:
```
@Path("/reproducer")
public class ReproducerEndpoint {

    public static class Entity {
        public String hello;
        public static Entity create(String hello) {
            Entity entity = new Entity();
            entity.hello = hello;
            return entity;
        }
    }

    @POST
    public Entity echo(Entity entity) {
        return entity;
    }
}
```
the client creates a tracer, but ZIPKIN does not recognize the span name:
```
    public static void main(String[] args) {

        Tracer tracer = TracerBuilder.create("EntityService")
                .collectorUri(URI.create("http://localhost:9411"))
                .registerGlobal(true)
                .addTracerTag("Hit_Count", 0).build();


        try (Response response = ClientBuilder.newClient() .property(TRACER_PROPERTY_NAME, tracer)
                .target("http://localhost:8080").path("reproducer")
                .request(MediaType.APPLICATION_JSON_TYPE).post(
                javax.ws.rs.client.Entity.entity(ReproducerEndpoint.Entity.create("HI"), MediaType.APPLICATION_JSON_TYPE)
        )) {
            ReproducerEndpoint.Entity responseEntity = response.readEntity(ReproducerEndpoint.Entity.class);
            Assertions.assertEquals(responseEntity.hello, "HI");
            Assertions.assertEquals(200, response.getStatus());
        };
    }
```

**Comment by jansupol** [comment]
![image](https://user-images.githubusercontent.com/15908245/84263234-6c727e00-ab1f-11ea-85bd-8441da1607db.png)

**Comment by tomas-langer** [comment]
There is at least one bug - when I call `tracer.activeSpan(span)` when using Zipkin, I get:
```
INFO: Creating Zipkin Tracer for 'HelidonClient' configured with: http://127.0.0.1:9411/api/v2/spans
Exception in thread "main" java.lang.IllegalArgumentException: Span must be an instance of brave.opentracing.BraveSpan, but was class io.helidon.tracing.zipkin.ZipkinSpan
	at brave.opentracing.BraveScopeManager.activate(BraveScopeManager.java:37)
	at brave.opentracing.BraveTracer.activateSpan(BraveTracer.java:190)
	at io.helidon.tracing.zipkin.ZipkinTracer.activateSpan(ZipkinTracer.java:89)
	at me.tomas.mp.quickstart.T.main(T.java:24)
```

**Comment by tomas-langer** [comment]
Regarding tracing of client call - I had to add the following code:
```
        Thread.sleep(10000);
        tracer.close();
```
to the client, as otherwise the span would not be recorded. This is probably related to the way Zipkin sends the data to the collector (I guess there is some attempt at buffering, and as the client just terminates the VM, the span is never published).
With the sleep added (not needed in server environment), the spans are correctly reported (e.g. server span has the client span as its parent).

This may be a side effect of other fixes to tracing.

**Comment by tomas-langer** [comment]
Closing this issue, as it works as designed.
Fixing discovered problems with active span via #3346
