### ISSUE TITLE
Tyrus support in GraalVM

### ISSUE THREAD

**Issue by jbescos** [oracle/helidon#1966]
## Environment Details
* Helidon Version: 2.0.0-RC1
* Helidon SE
* JDK version:GraalVM Version 20.1.0 (Java Version 11.0.7)
* OS: Ubuntu 18.04.4 LTS
* Docker version (if applicable):

----------

## Problem Description

I talked with @jsupol and he thinks we need to add the native properties in tyrus helidon module to allow reflection.

Exception in thread "main" java.lang.NullPointerException
	at org.glassfish.tyrus.core.TyrusEndpointWrapper.<init>(TyrusEndpointWrapper.java:250)
	at org.glassfish.tyrus.core.TyrusEndpointWrapper.<init>(TyrusEndpointWrapper.java:152)
	at org.glassfish.tyrus.core.TyrusWebSocketEngine.register(TyrusWebSocketEngine.java:639)
	at io.helidon.webserver.tyrus.TyrusSupport$Builder.lambda$build$1(TyrusSupport.java:198)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at io.helidon.webserver.tyrus.TyrusSupport$Builder.build(TyrusSupport.java:195)
	at io.helidon.webserver.examples.websocket.Main.createRouting(Main.java:54)
	at io.helidon.webserver.examples.websocket.Main.startWebServer(Main.java:59)
	at io.helidon.webserver.examples.websocket.Main.main(Main.java:85)
## Steps to reproduce
cd helidon/examples/webserver/websocket
mvn package -Pnative-image
./target/helidon-examples-webserver-websocket

**Comment by jbescos** [comment]
We can make it work in this way:
```
jbescos@jbescos-TECRA-X40-E:~/workspace/helidon/examples/webserver/websocket$ mkdir -p src/main/resources/META-INF/native-image
jbescos@jbescos-TECRA-X40-E:~/workspace/helidon/examples/webserver/websocket$ $JAVA_HOME/bin/java -agentlib:native-image-agent=config-output-dir=src/main/resources/META-INF/native-image -jar target/helidon-examples-webserver-websocket.jar
jbescos@jbescos-TECRA-X40-E:~/workspace/helidon/examples/webserver/websocket$ mvn package -Pnative-image && ./target/helidon-examples-webserver-websocket
```

But this means that any user that wants to use tyrus  natively, they need to generate that META-INF files too. There should be a better way to set the configuration directly in helidon/webserver/tyrus but I need to find out how.

**Comment by tomas-langer** [comment]
This is a known issue, websocket was not yet tested with native image.
