### ISSUE TITLE
@Gauge in ReqeustScope breaks all metrics

### ISSUE THREAD

**Issue by jansupol** [oracle/helidon#1977]
Following the example from [TomiTribe](https://www.tomitribe.com/blog/getting-started-with-microprofile-metrics/#:~:text=The%20MicroProfile%20Metrics%20is%20a,build%20their%20own%20application%20metrics.) we have:

```
@Path("gauge")
@RequestScoped
public class GaugeReproducer {
    @GET
    @Path("/price")
    public Response getItemsPrice() {
        return Response.ok(getPrice()).build();
    }

    @Gauge(unit = "Heads", name = "addHeadGauge", absolute = true)
    public long getPrice() {
        return 4;
    }
}
```
And the request works fine:
```
    public static void main(String[] args) {
        try (Response response = ClientBuilder.newClient()
                .target("http://localhost:8080").path("gauge/price")
                .request(MediaType.APPLICATION_JSON_TYPE).get()) {
            Assertions.assertEquals(200, response.getStatus());
        }
    }
```
But when we made a request to metrics url _http://localhost:8080/metrics/application_ we get a response:
> java.lang.reflect.InvocationTargetException

And the server log contains the full stack trace:
> 2020.06.11 11:17:41 WARNING io.helidon.webserver.RequestRouting Thread[nioEventLoopGroup-3-3,10,main]: Default error handler: Unhandled exception encountered.
java.util.concurrent.ExecutionException: Unhandled 'cause' of this exception encountered.
	at io.helidon.webserver.RequestRouting$RoutedRequest.defaultHandler(RequestRouting.java:387)
	at io.helidon.webserver.RequestRouting$RoutedRequest.nextNoCheck(RequestRouting.java:367)
...
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at io.helidon.microprofile.metrics.DelegatingGauge.getValue(DelegatingGauge.java:66)
	at io.helidon.metrics.HelidonGauge.getValue(HelidonGauge.java:57)
...
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.helidon.microprofile.metrics.DelegatingGauge.getValue(DelegatingGauge.java:64)
...
Caused by: org.jboss.weld.contexts.ContextNotActiveException: WELD-001303: No active contexts for scope type javax.enterprise.context.RequestScoped
	at org.jboss.weld.manager.BeanManagerImpl.getContext(BeanManagerImpl.java:647)

**Comment by jansupol** [comment]
Observations:
- The `RequestScoped` is [not supported by the Spec](https://github.com/eclipse/microprofile-metrics/blob/master/spec/src/main/asciidoc/architecture.adoc), but the unhandled exception prevents any other measuring from being observed on the _metrics_ URI.
- The original exception message is not propagated to the topmost exception level, resulting in `java.lang.reflect.InvocationTargetException` displayed by a browser
- An optional validation of `@Gauge` can take place upon deployment
- A meaningful message when the exception is thrown would be welcome
