### ISSUE TITLE
@ConfigProperty injection in JAX-RS filters fails if unmanaged

### ISSUE THREAD

**Issue by dansiviter** [oracle/helidon#2033]
## Environment Details
* Helidon Version: 1.4.4
* Helidon SE or Helidon MP: MP
* JDK version: Java 8/11
* OS: Windows
* Docker version (if applicable): N/A

----------

## Problem Description
Bit of a difficult one to articulate here but essentially if a JAX-RS container filter is in a different bean archive and is unmanaged (i.e. `bean-discovery-mode="annotated"` and no annotation on the filter) and requires injection from `@ConfigProperty` two scenarios may happen:
* The wrong property is injected by Jersey if there is another single `@ConfigProperty` defined elsewhere,
* It fails to start with following exception if multiple `@ConfigProperty`s are defined elsewhere.

```
Exception in thread "main" org.jboss.weld.exceptions.IllegalArgumentException: WELD-001409: Ambiguous dependencies for type int with qualifiers @ConfigProperty
  at injection point [BackedAnnotatedField] @Inject @ConfigProperty private uk.dansiviter.rest.MyFilter.property
  at uk.dansiviter.rest.MyFilter.property(MyFilter.java:0)
  Possible dependencies:
  - ConfigPropertyProducer{qualifier=ConfigQLiteral{fullPath='uk.dansiviter.service.MyService.property', key='service.property', defaultValue='5', rawType=int}},
  - ConfigPropertyProducer{qualifier=ConfigQLiteral{fullPath='uk.dansiviter.rest.MyResouce.property', key='resource.property', defaultValue='1', 
rawType=int}}

        at org.jboss.weld.manager.InjectionTargetFactoryImpl.createInjectionTarget(InjectionTargetFactoryImpl.java:83)
        at org.jboss.weld.manager.InjectionTargetFactoryImpl.createInjectionTarget(InjectionTargetFactoryImpl.java:70)
        at org.jboss.weld.manager.InjectionTargetFactoryImpl.createInjectionTarget(InjectionTargetFactoryImpl.java:51)
        at org.glassfish.jersey.ext.cdi1x.internal.AbstractCdiBeanSupplier$2.<init>(AbstractCdiBeanSupplier.java:80)
        at org.glassfish.jersey.ext.cdi1x.internal.AbstractCdiBeanSupplier.<init>(AbstractCdiBeanSupplier.java:62)
        at org.glassfish.jersey.ext.cdi1x.internal.GenericCdiBeanSupplier.<init>(GenericCdiBeanSupplier.java:37)
```
This issue seems fixed in 2.0.0.RC1 (possibly due to all `@Provider` classes now being managed) and can be worked around in two ways in v1.4:
* by attaching `@ApplicationScoped` to the JAX-RS filter,
* setting `bean-discovery-mode="all"`.

## Steps to reproduce
* Build and install `my-library` in attached [bug.zip](https://github.com/oracle/helidon/files/4793945/bug.zip) file,
* Run `helidon-sandbox` in attached [bug.zip](https://github.com/oracle/helidon/files/4793945/bug.zip) file and the stacktrace above will appear on startup.

I've been unable to replicate the wrong value being injected in a simple example but verified it is possible through debugging. If I find a way to replicate that, I'll update.

**Comment by tomas-langer** [comment]
Also the `ConfigProperty` is only available to CDI beans.

**Comment by dansiviter** [comment]
I suppose at the injection partially works then fails later with a slightly perplexing error it might confuse some. As there is a workaround and it doesn't appear to be an issue in v2 this might just be left here to slowly wither into obsolescence.

**Comment by tomas-langer** [comment]
I will close this issue and mark it as will not fix. 
There is a solution in 2.0
There is a workaround to use `MpConfig` API directly

Thanks you for the time spent on identifying & reporting.
