### ISSUE TITLE
helidon-database-se archetype app fails health check with JdbcSQLSyntaxErrorException

### ISSUE THREAD

**Issue by barchetta** [oracle/helidon#2084]
## Environment Details
* Helidon Version: 2.0.0
* Helidon SE 
* JDK version: 11.0.7
* OS: MacOS

----------

## Problem Description
The application generated by the helidon-database-se archetype fails health check.

## Steps to reproduce
```
# Run generate the example as normal:

mvn archetype:generate -DinteractiveMode=false  \
    -DarchetypeGroupId=io.helidon.archetypes \
    -DarchetypeArtifactId=helidon-database-se 
    -DarchetypeVersion=2.0.0 -DgroupId=io.helidon.examples   \
    -DartifactId=helidon-database-se     \
    -Dpackage=io.helidon.examples.database.se

# Then build and run the app as described in the README
```

In another window:
```
curl -s -X GET http://localhost:8080/health
```

You'll see the health check fails and the app logs an error:
```
Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "DO[*] 0"; expected "DELETE, DROP, DECLARE, DEALLOCATE"; SQL statement:
DO 0 [42001-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:451)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.getSyntaxError(DbException.java:243)
	at org.h2.command.Parser.getSyntaxError(Parser.java:991)
	at org.h2.command.Parser.parsePrepared(Parser.java:951)
	at org.h2.command.Parser.parse(Parser.java:788)
	at org.h2.command.Parser.parse(Parser.java:764)
	at org.h2.command.Parser.prepareCommand(Parser.java:683)
	at org.h2.engine.Session.prepareLocal(Session.java:627)
	at org.h2.engine.Session.prepareCommand(Session.java:565)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1292)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:77)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:349)
	at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:316)
	at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java)
	at io.helidon.dbclient.jdbc.JdbcStatement.prepareIndexedStatement(JdbcStatement.java:149)
	... 12 more
```

I'm assuming the health check is meant to pass. If not, then the README should be updated.

**Comment by spericas** [comment]
Fixed by #2100
