### ISSUE TITLE
helidon-integrations-cdi-oci-objectstorage cause "401 Unauthorized" while using @Authenticated 

### ISSUE THREAD

**Issue by atjapan2015** [oracle/helidon#2131]
## Environment Details
* Helidon Version: 2.0.1
* Helidon MP
* JDK version: java version "11.0.7" 2020-04-14 LTS, Java(TM) SE Runtime Environment GraalVM EE 20.0.1 (build 11.0.7+8-LTS-jvmci-20.0-b04), Java HotSpot(TM) 64-Bit Server VM GraalVM EE 20.0.1 (build 11.0.7+8-LTS-jvmci-20.0-b04, mixed mode, sharing)
* OS: Windows
* Docker version (if applicable): not use

----------

## Problem Description
@Authenticated is for protecting rest endpoint.
While not using @Authenticated, helidon-integrations-cdi-oci-objectstorage worked well.
After adding @Authenticated, helidon-integrations-cdi-oci-objectstorage throws "401 Unauthorized".

Exception Trace:
```
com.oracle.bmc.model.BmcException: (401, NotAuthenticated, false) The required information to complete authentication was not provided. (opc-request-id: nrt-1:LaX0ZwyBXQgp-XaQktBP21ijalzJE5a5XBjvurPqdPtKjRtKTvP9-gXpsQdf3n-E)
	at com.oracle.bmc.http.internal.ResponseHelper.throwIfNotSuccessful(ResponseHelper.java:137)
	at com.oracle.bmc.http.internal.ResponseConversionFunctionFactory$ValidatingParseResponseFunction.apply(ResponseConversionFunctionFactory.java:87)
	at com.oracle.bmc.http.internal.ResponseConversionFunctionFactory$ValidatingParseResponseFunction.apply(ResponseConversionFunctionFactory.java:83)
	at com.oracle.bmc.objectstorage.internal.http.GetObjectConverter$1.apply(GetObjectConverter.java:87)
	at com.oracle.bmc.objectstorage.internal.http.GetObjectConverter$1.apply(GetObjectConverter.java:74)
	at com.oracle.bmc.objectstorage.ObjectStorageClient.lambda$null$28(ObjectStorageClient.java:828)
	at com.oracle.bmc.retrier.BmcGenericRetrier.lambda$execute$0(BmcGenericRetrier.java:50)
	at com.oracle.bmc.waiter.GenericWaiter.execute(GenericWaiter.java:54)
	at com.oracle.bmc.retrier.BmcGenericRetrier.execute(BmcGenericRetrier.java:46)
	at com.oracle.bmc.objectstorage.ObjectStorageClient.lambda$getObject$29(ObjectStorageClient.java:824)
	at com.oracle.bmc.retrier.BmcGenericRetrier.lambda$execute$0(BmcGenericRetrier.java:50)
	at com.oracle.bmc.waiter.GenericWaiter.execute(GenericWaiter.java:54)
	at com.oracle.bmc.retrier.BmcGenericRetrier.execute(BmcGenericRetrier.java:46)
	at com.oracle.bmc.objectstorage.ObjectStorageClient.getObject(ObjectStorageClient.java:818)
	at com.oracle.bmc.objectstorage.ObjectStorageClient$Proxy$_$$_WeldClientProxy.getObject(Unknown Source)
	at io.helidon.mp.api.ApiResource.getCarImage(ApiResource.java:195)
	at io.helidon.mp.api.ApiResource$Proxy$_$$_WeldClientProxy.getCarImage(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
	at io.helidon.webserver.jersey.JerseySupport$JerseyHandler.lambda$doAccept$3(JerseySupport.java:283)
	at io.helidon.common.context.Contexts.runInContext(Contexts.java:98)
	at io.helidon.common.context.ContextAwareExecutorImpl.lambda$wrap$1(ContextAwareExecutorImpl.java:129)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

## Steps to reproduce
step1: build a helidon-mp 2.0.1 project
step2: follow introduction to add basic auth(https://helidon.io/docs/latest/#/mp/security/01_security and https://helidon.io/docs/latest/#/mp/security/02_configuration-secrets)
step3: add a test method to ensure basic auth works well
step4: follow introduction to add helidon-integrations-cdi-oci-objectstorage(https://helidon.io/docs/latest/#/mp/extensions/04_cdi_oci-objectstorage)
step5: follow this example to add getLogo method(https://github.com/oracle/helidon/tree/1.0.0/examples/integrations/cdi/oci-objectstorage), and add bmcException.printStackTrace(); in catch block.
step6: step5 worked well firstly.
step7: add @Authenticated to getLogo method to make it protect by basic auth, got "401 Unauthorized".

**Comment by ljnelson** [comment]
Is this still an issue?
