### ISSUE TITLE
When security is disabled, OIDC Provider still tries to load well known data from the IDCS server.

### ISSUE THREAD

**Issue by mamj756** [oracle/helidon#2132]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version: 1.4.4
* Helidon MP
* JDK version: 1.8
* OS: Windows 10

----------

## Problem Description
[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"
[//]: # "State if the problem is easily reproducible or happens intermittently"
[//]: # "Include stack traces or command outputs"

Security is disabled and has placeholders for the IDCS-related attributes in the application.yaml as shown below. 
```
security:
  config.require-encryption: false
  jersey:
    enabled: false
    use-abort-with: false
  properties:
    uri: “https://idcs.identity.oraclecloud.com”
    client-id: “client_id_placeholder”
    client-secret: “${CLEAR=client_secret_placeholder}”
    # Used as a base for redirects back to us
    frontend-uri: “http://host:port”
    proxy-host: ""
    # scope-audience must always end with '/'
    scope-audience: “http://host:port/”
    audience: “http://host:port/”
```

When server is started, the OIDC provider tries to load the well-known data from the IDCS server and throws an error as shown below.  And also we don't want to make  **oidc-metadata-well-known** property to false and have **sign jwk** on the classpath. 

```
Exception in thread “main” io.helidon.common.Errors$ErrorMessagesException: [FATAL: Failed to load metadata: io.helidon.common.configurable.ResourceException: Failed to open stream to uri: https://idcs.identity.oraclecloud.com/.well-known/openid-configuration at io.helidon.common.configurable.ResourceException: Failed to open stream to uri: https://idcs.identity.oraclecloud.com/.well-known/openid-configuration, FATAL: When token_endpoint is not explicitly defined, the OIDC metadata must exist at class io.helidon.security.providers.oidc.common.OidcConfig$Builder, FATAL: When authorization_endpoint is not explicitly defined, the OIDC metadata must exist at class io.helidon.security.providers.oidc.common.OidcConfig$Builder, FATAL: When jwks_uri is not explicitly defined, the OIDC metadata must exist at class io.helidon.security.providers.oidc.common.OidcConfig$Builder]
	at io.helidon.common.Errors.checkValid(Errors.java:175)
	at io.helidon.security.providers.oidc.common.OidcConfig$Builder.build(OidcConfig.java:803)
	at io.helidon.security.providers.oidc.common.OidcConfig.create(OidcConfig.java:415)
	at io.helidon.security.providers.oidc.OidcSupport.create(OidcSupport.java:140)
	at io.helidon.security.providers.oidc.OidcSupport.create(OidcSupport.java:252)
	at io.helidon.microprofile.oidc.OidcMpService.configure(OidcMpService.java:30)
	at io.helidon.microprofile.server.ServerImpl.lambda$loadExtensions$10(ServerImpl.java:376)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at io.helidon.microprofile.server.ServerImpl.loadExtensions(ServerImpl.java:375)
	at io.helidon.microprofile.server.ServerImpl.<init>(ServerImpl.java:148)
	at io.helidon.microprofile.server.Server$Builder.doBuild(Server.java:271)
	at io.helidon.common.context.Contexts.runInContext(Contexts.java:118)
	at io.helidon.microprofile.server.Server$Builder.build(Server.java:209)
	at io.helidon.microprofile.server.Server.create(Server.java:95)
	at com.oracle.cx.communications.dx4c.fabric.Main.startServer(Main.java:69)
	at com.oracle.cx.communications.dx4c.fabric.Main.main(Main.java:42)

```

So need to way to disable the security completely in Helidon MP.

## Steps to reproduce
[//]: # "Step by step instructions to reproduce the problem"
[//]: # "Provide sample code/application if relevant"

- Create a Helidon MP project using 1.4.4
- Example application.yaml file:
```
security:
  config.require-encryption: false
  jersey:
    enabled: false
    use-abort-with: false
  properties:
    uri: “https://idcs.identity.oraclecloud.com”
    client-id: “client_id_placeholder”
    client-secret: “${CLEAR=client_secret_placeholder}”
    # Used as a base for redirects back to us
    frontend-uri: “http://host:port”
    proxy-host: ""
    # scope-audience must always end with '/'
    scope-audience: “http://host:port/”
    audience: “http://host:port/”
```

**Comment by tomas-langer** [comment]
I have one question - what is the expected behavior when you disable security?

I plan to:
- ignore all security annotations
- security will not be "present" in the system 

This has one result:
- if you inject anything security related in your application, it would not work (such as `SecurityContext`) - as security is disabled, security context is not created for requests and cannot be injected.

Is this the expected behavior? Or do you expect to get a security context that is not authenticated?

**Comment by mamj756** [comment]
I think the last option is better i.e, we need to get security context which is not authenticated.

**Comment by tomas-langer** [comment]
I have tested this with the "IDCS Example" for microprofile.
When you configure `security.enabled=false`, or in `application.yaml`:
```
security:
  enabled: false
```

The server starts and all endpoints work - you will get an `Optional.empty()` response for endpoints that return current `Subject`
