### ISSUE TITLE
Replace reflect-config.json with @Reflected in examples

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#2183]
We now have a `@Reflected` annotation to register a class for reflection in native image (when it must be reflected for all constructors and methods).

We should use `reflect-config.json` for third party classes and for classes where we want to enable only a small subset of its signature.

**Comment by tomas-langer** [comment]
Once #3358 is merged, we may not need this at all

**Comment by klustria** [comment]
When removing reflect-config.json, I'm getting this error:

```
Caused by: javax.json.bind.JsonbException: Cannot create instance of a class: class io.helidon.examples.dbclient.common.Pokemon, No default constructor found.
        at org.eclipse.yasson.internal.serializer.ObjectDeserializer.getInstance(ObjectDeserializer.java:101)
        at org.eclipse.yasson.internal.serializer.AbstractContainerDeserializer.deserialize(AbstractContainerDeserializer.java:65)
        at org.eclipse.yasson.internal.Unmarshaller.deserializeItem(Unmarshaller.java:62)
        at org.eclipse.yasson.internal.Unmarshaller.deserialize(Unmarshaller.java:51)
        at org.eclipse.yasson.internal.JsonBinding.deserialize(JsonBinding.java:59)
        at org.eclipse.yasson.internal.JsonBinding.fromJson(JsonBinding.java:99)
        at io.helidon.media.jsonb.JsonbBodyReader$BytesToObject.map(JsonbBodyReader.java:83)
        at io.helidon.media.jsonb.JsonbBodyReader$BytesToObject.map(JsonbBodyReader.java:70)
        at io.helidon.common.mapper.Mapper.apply(Mapper.java:39)
        at io.helidon.common.reactive.MultiMapperPublisher$MapperSubscriber.onNext(MultiMapperPublisher.java:73)
        ... 42 more
```

Adding @Reflected resolves this issue.

**Comment by klustria** [comment]
Tested against MongoDB... will further test with Oracle DB and MySQL
