### ISSUE TITLE
Switch from exec:java to exec:exec

### ISSUE THREAD

**Issue by aalmiray** [oracle/helidon#2194]
## Environment Details
* Helidon Version: 2.0.1
* Helidon SE _and_ Helidon MP
* JDK version: 11
* OS: OSX
* Docker version: N/A

----------

## Problem Description
Invoking `exec:java` on a Helidon SE project results in logging not being properly configured.

    [INFO] --- exec-maven-plugin:1.6.0:java (default-cli) @ helidon-se-example ---
    Can't load log handler "io.helidon.common.HelidonConsoleHandler"
    java.lang.ClassNotFoundException: io.helidon.common.HelidonConsoleHandler
    java.lang.ClassNotFoundException: io.helidon.common.HelidonConsoleHandler
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at java.logging/java.util.logging.LogManager.createLoggerHandlers(LogManager.java:1000)
        at java.logging/java.util.logging.LogManager$4.run(LogManager.java:970)
        at java.logging/java.util.logging.LogManager$4.run(LogManager.java:966)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.logging/java.util.logging.LogManager.loadLoggerHandlers(LogManager.java:966)
        at java.logging/java.util.logging.LogManager.initializeGlobalHandlers(LogManager.java:2417)
        at java.logging/java.util.logging.LogManager$RootLogger.accessCheckedHandlers(LogManager.java:2511)
        at java.logging/java.util.logging.Logger.getHandlers(Logger.java:2089)
        at java.logging/java.util.logging.Logger.log(Logger.java:976)
        at java.logging/java.util.logging.Logger.doLog(Logger.java:1006)
        at java.logging/java.util.logging.Logger.log(Logger.java:1029)
        at java.logging/java.util.logging.Logger.info(Logger.java:1802)
        at io.helidon.common.HelidonFeatures.features(HelidonFeatures.java:154)
        at io.helidon.common.HelidonFeatures.lambda$print$4(HelidonFeatures.java:127)
        at java.base/java.lang.Thread.run(Thread.java:834)

Invoking `exec:java` on a Helidon MP project results in a similar stacktrace

    [INFO] --- exec-maven-plugin:1.6.0:java (default-cli) @ helidon-mp-example ---
    Can't load log handler "io.helidon.common.HelidonConsoleHandler"
    java.lang.ClassNotFoundException: io.helidon.common.HelidonConsoleHandler
    java.lang.ClassNotFoundException: io.helidon.common.HelidonConsoleHandler
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at java.logging/java.util.logging.LogManager.createLoggerHandlers(LogManager.java:1000)
        at java.logging/java.util.logging.LogManager$4.run(LogManager.java:970)
        at java.logging/java.util.logging.LogManager$4.run(LogManager.java:966)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.logging/java.util.logging.LogManager.loadLoggerHandlers(LogManager.java:966)
        at java.logging/java.util.logging.LogManager.initializeGlobalHandlers(LogManager.java:2417)
        at java.logging/java.util.logging.LogManager$RootLogger.accessCheckedHandlers(LogManager.java:2511)
        at java.logging/java.util.logging.Logger.getHandlers(Logger.java:2089)
        at java.logging/java.util.logging.Logger.log(Logger.java:976)
        at java.logging/java.util.logging.Logger.doLog(Logger.java:1006)
        at java.logging/java.util.logging.Logger.log(Logger.java:1029)
        at java.logging/java.util.logging.Logger.info(Logger.java:1802)
        at io.helidon.common.LogConfig.doConfigureLogging(LogConfig.java:93)
        at io.helidon.common.LogConfig.configureLogging(LogConfig.java:66)
        at io.helidon.common.LogConfig.<clinit>(LogConfig.java:44)
        at io.helidon.microprofile.cdi.BuildTimeInitializer.<clinit>(BuildTimeInitializer.java:30)
        at io.helidon.microprofile.cdi.ContainerInstanceHolder.fromBuildTimeInitializer(ContainerInstanceHolder.java:58)
        at io.helidon.microprofile.cdi.ContainerInstanceHolder.get(ContainerInstanceHolder.java:50)
        at io.helidon.microprofile.cdi.Main.<clinit>(Main.java:55)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
        at java.base/java.lang.Thread.run(Thread.java:834)

## Steps to reproduce
1. Create a Helidon SE application as suggested in the Helidon SE Quickstart guide
2. invoke `mvn compile exec:java`.
1. Create a Helidon MP application as suggested in the Helidon MP Quickstart guide
2. invoke `mvn compile exec:java`.

**Comment by aalmiray** [comment]
The following plugin configuration solves this problem

            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <configuration>
                    <executable>java</executable>
                    <longClasspath>true</longClasspath>
                    <arguments>
                        <argument>-classpath</argument>
                        <classpath/>
                        <argument>${mainClass}</argument>
                    </arguments>
                </configuration>
            </plugin>

This configures the `exec:exec` goal which runs the application in a forked JVM. The side effect is that `exec:java` may no longer be executed with the default configuration in place.

**Comment by romain-grecourt** [comment]
See also https://github.com/oracle/helidon/issues/1349

**Comment by dalexandrov** [comment]
Fixed with https://github.com/oracle/helidon/pull/3148
