### ISSUE TITLE
webclient.MediaContextTest intermittent failure

### ISSUE THREAD

**Issue by romain-grecourt** [oracle/helidon#2197]
```
Caused by: java.util.concurrent.ExecutionException: io.netty.handler.timeout.ReadTimeoutException
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
	at io.helidon.tests.integration.webclient.MediaContextTest.lambda$testInputStreamSameThreadTestContentAs$21(MediaContextTest.java:208)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:55)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:37)
	at org.junit.jupiter.api.Assertions.assertThrows(Assertions.java:2952)
	at io.helidon.tests.integration.webclient.MediaContextTest.testInputStreamSameThreadTestContentAs(MediaContextTest.java:195)
	... 62 more
Caused by: io.netty.handler.timeout.ReadTimeoutException
```

**Comment by barchetta** [comment]
I've seen this intermittent failure as well.
