### ISSUE TITLE
NullPointerException in ConfigMapperManager.ProviderWrapper

### ISSUE THREAD

**Issue by ljnelson** [oracle/helidon#2206]
The following test code (I'm working on a different issue) produces a `NullPointerException`:
```
        final org.eclipse.microprofile.config.Config mpConfig = ConfigProviderResolver.instance()
            .getBuilder()
            .withSources(MpConfigSources.create(Config.builder() // Helidon Config builder
                                                .sources(ConfigSources.file(Thread.currentThread()
                                                                            .getContextClassLoader()
                                                                            .getResource(this.getClass()
                                                                                         .getSimpleName()
                                                                                         + "/test.yaml") // doesn't matter
                                                                            .getPath()))
                                                .build()))
            .build();
        String bar = mpConfig.getValue("foo", String.class); // Kaboom
```
Partial stack:
```
java.lang.NullPointerException
	at io.helidon.config.ConfigMapperManager$ProviderWrapper.apply(ConfigMapperManager.java:361)
	at io.helidon.config.ConfigMapperManager$ProviderWrapper.apply(ConfigMapperManager.java:350)
	at io.helidon.config.ConfigMapperManager$MapperProviders.lambda$findMapper$0(ConfigMapperManager.java:191)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.LinkedList$LLSpliterator.tryAdvance(LinkedList.java:1256)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at io.helidon.config.ConfigMapperManager$MapperProviders.findMapper(ConfigMapperManager.java:193)
	at io.helidon.config.ConfigMapperManager.findMapper(ConfigMapperManager.java:110)
	at io.helidon.config.ConfigMapperManager.lambda$map$0(ConfigMapperManager.java:84)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at io.helidon.config.ConfigMapperManager.map(ConfigMapperManager.java:84)
	at io.helidon.config.ConfigMapperManager.map(ConfigMapperManager.java:67)
	at io.helidon.config.ConfigValues.lambda$create$0(ConfigValues.java:130)
	at io.helidon.config.ConfigValues$GenericConfigValueImpl.asOptional(ConfigValues.java:228)
	at io.helidon.config.ConfigValue.orElse(ConfigValue.java:304)
	at io.helidon.config.mp.MpHelidonConfigSource.getValue(MpHelidonConfigSource.java:46)
	at io.helidon.config.mp.MpConfigImpl.getStringValue(MpConfigImpl.java:214)
	at io.helidon.config.mp.MpConfigImpl.getOptionalValue(MpConfigImpl.java:145)
	at io.helidon.config.mp.MpConfigImpl.getValue(MpConfigImpl.java:90)
```
In case it matters, this is in an exploratory unit test I'm writing in the `config-mp` project, not in an actual application or server.  I wanted to record this so it wouldn't get lost.

**Comment by ljnelson** [comment]
Ah; fortunately this appears to be restricted to unit tests in this particular project only:

https://github.com/oracle/helidon/blob/32994ed45be94d3fae1bc22ac3aad0245c8daa13/config/config-mp/src/test/resources/META-INF/services/io.helidon.config.spi.ConfigMapperProvider#L17

…leads to:

https://github.com/oracle/helidon/blob/32994ed45be94d3fae1bc22ac3aad0245c8daa13/config/config-mp/src/test/java/io/helidon/config/mp/MpConfigTest.java#L255-L258

…which is what is responsible.  This does impact all unit tests in this project, but is not customer/user-facing.
