### ISSUE TITLE
JAX-RS ContainerRequestContext contract is not adequately fulfilled

### ISSUE THREAD

**Issue by pbull-oracle** [oracle/helidon#2211]
## Environment Details
* Helidon Version: 2.0.0-M3
* Helidon SE or Helidon MP: MP
* JDK version: jdk-11u6-linux-x64
* OS: Linux RHEL 7.4
* Docker version (if applicable): N/A

----------

## Problem Description
In our Helidon MP app, `javax.ws.rs.container.ContainerRequestContext` throws unexpected exceptions for removing properties.

**Expected behavior is clearly outlined in Javadocs, with no mention of deprecation or optional support:**
https://github.com/eclipse-ee4j/jaxrs-api/blob/2.1.6/jaxrs-api/src/main/java/javax/ws/rs/container/ContainerRequestContext.java

1. `ContainerRequestContext.removeProperty(name)`
Actual behavior: 
```
java.lang.UnsupportedOperationException: property removal from the context is not allowed
    at io.helidon.webserver.jersey.JerseySupport$WebServerPropertiesDelegate.removeProperty(JerseySupport.java:353)
    at org.glassfish.jersey.message.internal.TracingAwarePropertiesDelegate.removeProperty(TracingAwarePropertiesDelegate.java:50)
    at org.glassfish.jersey.server.ContainerRequest.removeProperty(ContainerRequest.java:294)
```

2. `ContainerRequestContext.setProperty(name, null)`
Actual behavior:
```
java.lang.NullPointerException: Parameter 'instance' is null!
    at java.util.Objects.requireNonNull(Objects:246)
    at io.helidon.common.context.ListContext.ClassifiedRegistry.register(ListContext:146)
    at io.helidon.common.context.ListContext.register(ListContext:81)
    at io.helidon.common.http.ListContextualRegistry.register(ListContextualRegistry:73)
    at io.helidon.webserver.jersey.JerseySupport$WebServerPropertiesDelegate.setProperty(JerseySupport.java:347)
    at org.glassfish.jersey.message.internal.TracingAwarePropertiesDelegate.setProperty(TracingAwarePropertiesDelegate.java:58)
    at org.glassfish.jersey.server.ContainerRequest.setProperty(ContainerRequest.java:289)
```

## Steps to reproduce

1. Implement one `javax.ws.rs.container.ContainerRequestFilter`. In the filter method, call `ContainerRequestContext.setProperty` twice - once with a non-null property name plus a non-null property value, and once with a (different) non-null property name plus a null property value.
2. Implement a separate `ContainerRequestFilter` with a priority later in the chain than the filter defined previously. In the filter method, call `ContainerRequestContext.removeProperty` for the same properties that were set by the filter defined previously.

**Comment by spericas** [comment]
This is currently implemented using our internal `Context` API. We need to look at how to better support all of the `ContainerRequestContext` methods including those above and `getPropertyNames`.

**Comment by spericas** [comment]
PR #2756
