### ISSUE TITLE
Helidon does not pick identity-uri from providers.oidc.identity-uri & picks up only from security.properties.uri

### ISSUE THREAD

**Issue by PasiPraveen** [oracle/helidon#2278]
## Environment Details
Helidon Version: 1.4.4
Helidon MP
JDK version: 1.8
OS: Windows 10

## Problem Description
Helidon does not pick identity-uri from providers.oidc.identity-uri & picks up only from security.properties.uri

In application.yaml file add entries as below

security:
  config.require-encryption: false
  jersey:
    enabled: true
    use-abort-with: false
  properties:
    uri: ""
    client-id: ""
    client-secret: ""
    # Used as a base for redirects back to us
    frontend-uri: "http://localhost:8080"
    proxy-host: ""
    # scope-audience must always end with '/'
    scope-audience: "http://localhost:8080/"
    audience: "http://localhost:8080/"

  providers:
    - abac:
    - oidc:
        client-id: "095b06a84a40444fbe0096403489c3d1"
        client-secret: "0b6b8ba1-beee-4976-8032-27c0dc8fff3a"
        identity-uri: "https://idcs-749cc3beb8c34a.identity.oraclecloud.com"
        # A prefix used for custom scopes
        scope-audience: "${ALIAS=security.properties.scope-audience}"
        audience: "${ALIAS=security.properties.audience}"
        proxy-host: "${ALIAS=security.properties.proxy-host}"
        frontend-uri: "${ALIAS=security.properties.frontend-uri}"
        cookie-name: "OIDC_SESSION"
        cookie-same-site: "Lax"
        header-use: true
        redirect: false

Though valid uri is present in providers.oidc.identity-uri & since security.properties.uri is blank Helidon throws the following exception while starting application when it looks to load metadata

Exception in thread "main" io.helidon.common.Errors$ErrorMessagesException: [FATAL: Failed to load metadata: java.lang.IllegalArgumentException: URI is not absolute at java.lang.IllegalArgumentException: URI is not absolute, FATAL: When token_endpoint is not explicitly defined, the OIDC metadata must exist at class io.helidon.security.providers.oidc.common.OidcConfig$Builder, FATAL: When authorization_endpoint is not explicitly defined, the OIDC metadata must exist at class io.helidon.security.providers.oidc.common.OidcConfig$Builder, FATAL: When jwks_uri is not explicitly defined, the OIDC metadata must exist at class io.helidon.security.providers.oidc.common.OidcConfig$Builder]
	at io.helidon.common.Errors.checkValid(Errors.java:175)
	at io.helidon.security.providers.oidc.common.OidcConfig$Builder.build(OidcConfig.java:806)
	at io.helidon.security.providers.oidc.common.OidcConfig.create(OidcConfig.java:417)
	at io.helidon.config.ConfigValues.lambda$create$4(ConfigValues.java:146)
	at io.helidon.config.ConfigValues$GenericConfigValueImpl.asOptional(ConfigValues.java:228)
	at io.helidon.config.ConfigValue.ifPresent(ConfigValue.java:228)
	at io.helidon.security.providers.idcs.mapper.IdcsRoleMapperProviderBase$Builder.config(IdcsRoleMapperProviderBase.java:305)
	at io.helidon.security.providers.idcs.mapper.IdcsRoleMapperProvider$Builder.config(IdcsRoleMapperProvider.java:222)
	at io.helidon.security.providers.idcs.mapper.IdcsRoleMapperProvider.create(IdcsRoleMapperProvider.java:96)
	at io.helidon.security.providers.idcs.mapper.IdcsRoleMapperProviderService.providerInstance(IdcsRoleMapperProviderService.java:41)
	at io.helidon.security.Security$Builder.lambda$fromConfig$2(Security.java:884)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at io.helidon.security.Security$Builder.fromConfig(Security.java:844)
	at io.helidon.security.Security$Builder.config(Security.java:799)
	at io.helidon.security.Security.create(Security.java:187)
	at io.helidon.microprofile.security.SecurityMpService.configure(SecurityMpService.java:49)
	at io.helidon.microprofile.server.ServerImpl.lambda$loadExtensions$10(ServerImpl.java:376)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at io.helidon.microprofile.server.ServerImpl.loadExtensions(ServerImpl.java:375)
	at io.helidon.microprofile.server.ServerImpl.<init>(ServerImpl.java:148)
	at io.helidon.microprofile.server.Server$Builder.doBuild(Server.java:273)
	at io.helidon.common.context.Contexts.runInContext(Contexts.java:118)
	at io.helidon.microprofile.server.Server$Builder.build(Server.java:211)
	at io.helidon.microprofile.server.Server.create(Server.java:95)
	at io.helidon.examples.quickstart.mp.Main.startServer(Main.java:59)
	at io.helidon.examples.quickstart.mp.Main.main(Main.java:46)
Weld SE container 9e6019c1-6e2a-4891-85ff-58bf967300c7 shut down by shutdown hook

## Steps to reproduce
1)Create a Helidon MP project using 1.4.4(helidon-quickstart-mp example)
2)Have entries in application.yaml as below

security:
  config.require-encryption: false
  jersey:
    enabled: true
    use-abort-with: false
  properties:
    uri: ""
    client-id: ""
    client-secret: ""
    # Used as a base for redirects back to us
    frontend-uri: "http://localhost:8080"
    proxy-host: ""
    # scope-audience must always end with '/'
    scope-audience: "http://localhost:8080/"
    audience: "http://localhost:8080/"

  providers:
    - abac:
    - oidc:
        client-id: "095b06a84a40444fbe0096403489c3d1"
        client-secret: "0b6b8ba1-beee-4976-8032-27c0dc8fff3a"
        identity-uri: "https://idcs-749cc3beb8c34a.identity.oraclecloud.com"
        # A prefix used for custom scopes
        scope-audience: "${ALIAS=security.properties.scope-audience}"
        audience: "${ALIAS=security.properties.audience}"
        proxy-host: "${ALIAS=security.properties.proxy-host}"
        frontend-uri: "${ALIAS=security.properties.frontend-uri}"
        cookie-name: "OIDC_SESSION"
        cookie-same-site: "Lax"
        header-use: true
        redirect: false

**Comment by tomas-langer** [comment]
Hello,
 Helidon config is a tree structure, and security providers are an ordered list, so they cannot be represented as a map (as maps do not preserve order).
As you can see in `yaml`, the structure is:
```yaml
security:
  providers:
    - oidc:
```
The `- oidc` creates an array.

The reason we have the `security.properties.uri` in the configuration is to enable easy override using other config sources, system properties or environment variables.
If you want to override the full path, you would need to include an index of the `oidc` provider configuration (which is obviously error prone, as it can be easily changed).

How to do this - two options:

1. Override the URI using `security.properties.uri` in a source with higher priority
2. Use `security.providers.0.oidc.identity-uri` if `oidc` is the first provider

I am closing this issue, as this works as designed. Feel free to reopen if I have not answered fully!

**Comment by PasiPraveen** [comment]
My only point is if security.providers.0.oidc.identity-uri is by default referencing a value from security.properties.uri
and if security.providers.0.oidc.identity-uri is overridden then the value for 'security.providers.0.oidc.identity-uri' should take priorty
and also all interactions with OAuth server are done using security.providers.0.oidc.xxxxx[ex:oidc-metadata-well-known,token-endpoint-uri etc].

The issue I posted above is if I have given a value for 'security.providers.0.oidc.identity-uri' & want to configure all OIDC related properties at one place[i.e under security.providers.oidc] Helidon is forcing to give value for identity-uri under security.properties.uri.

If I have overridden the property security.providers.0.oidc.client-id then I guess when interacting with OAuth server Helidon is considering security.providers.0.oidc.client-id & not security.properties.client-id.

If so the priorities seem to be ambiguous(changing) from starting the server[security.properties.uri] to interacting with OAuth server.[security.providers.0.oidc.xxxxxx]

I am fine with closing the issue but the only point we are not users to give all OIDC cnfiguration at one place[except URI] & forcing to give URI under security.properties.uri.
