### ISSUE TITLE
MPOpenAPIBuilder calls Application.getClasses() with unresolved Injection points

### ISSUE THREAD

**Issue by barchetta** [oracle/helidon#2324]
## Environment Details
* Helidon Version: 2.0.1
*  Helidon MP
* JDK version: 11

----------

## Problem Description

If an Application's `getClasses()` method relies on Injected fields, those fields can be null if OpenAPI support is enabled.

## Steps to reproduce

1. Get the reproducer from issue #2270 
2. Build using Java 11: `gradle clean build`
3. `export VAR=foo`
4. `java -jar build/libs/helidon-2-possible-cdi-issue.jar `

You should get a NPE like:

```
2020-09-03 12:38:31,509 [INFO] [:No Correlation ID] org.jboss.weld.Bootstrap Thread[main]: WELD-ENV-002001: Weld SE container fb1ca7ff-1d37-44b3-91f6-c543cb058994 shut down
Exception in thread "main" java.lang.NullPointerException
        at dk.bankdata.drb.api.RestApplication.getClasses(RestApplication.java:25)
        at io.helidon.microprofile.openapi.MPOpenAPIBuilder.classesToScanForApp(MPOpenAPIBuilder.java:131)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at io.helidon.microprofile.openapi.MPOpenAPIBuilder.buildPerAppFilteredIndexViews(MPOpenAPIBuilder.java:103)
        at io.helidon.microprofile.openapi.MPOpenAPIBuilder.perAppFilteredIndexViews(MPOpenAPIBuilder.java:59)
        at io.helidon.openapi.OpenAPISupport.<init>(OpenAPISupport.java:139)
        at io.helidon.openapi.OpenAPISupport$Builder.build(OpenAPISupport.java:648)
        at io.helidon.microprofile.openapi.OpenApiCdiExtension.registerOpenApi(OpenApiCdiExtension.java:111)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95)
        at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:85)
        at org.jboss.weld.injection.MethodInvocationStrategy$SimpleMethodInvocationStrategy.invoke(MethodInvocationStrategy.java:168)
        at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:330)
        at org.jboss.weld.event.ExtensionObserverMethodImpl.sendEvent(ExtensionObserverMethodImpl.java:123)
        at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:308)
        at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:286)
        at javax.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:124)
        at org.jboss.weld.util.Observers.notify(Observers.java:166)
        at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:285)
        at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:273)
        at org.jboss.weld.event.EventImpl.fire(EventImpl.java:96)
        at io.helidon.microprofile.cdi.HelidonContainerImpl.doStart(HelidonContainerImpl.java:335)
        at io.helidon.common.context.Contexts.runInContext(Contexts.java:118)
        at io.helidon.microprofile.cdi.HelidonContainerImpl.start(HelidonContainerImpl.java:245)
        at io.helidon.microprofile.cdi.Main.main(Main.java:80)
```

If you update the `build.gradle` to to have helidon dependencies like this:
```
    implementation enforcedPlatform("io.helidon:helidon-dependencies:${project['io.helidon.version']}")
    //implementation 'io.helidon.microprofile.bundles:helidon-microprofile'
    implementation 'io.helidon.microprofile.bundles:helidon-microprofile-core'
    implementation 'io.helidon.microprofile.tracing:helidon-microprofile-tracing'
    implementation 'io.helidon.microprofile.health:helidon-microprofile-health'
    implementation 'io.helidon.microprofile.metrics:helidon-microprofile-metrics'
    //implementation 'io.helidon.microprofile.openapi:helidon-microprofile-openapi'
    implementation 'io.helidon.tracing:helidon-tracing-jaeger'
```
The application starts up OK because the openapi support is not enabled.

**Comment by tjquinno** [comment]
The OpenAPI support code in Helidon is, in fact, not using CDI to instantiate the `Application` instances. (It instantiates them so it can invoke `getClasses` on each `Application` instance.) We'll need to fix that.
