### ISSUE TITLE
HealthCheck bean is not injectable

### ISSUE THREAD

**Issue by danielkec** [oracle/helidon#2376]
* Helidon Version: 2.0.2
* Helidon MP
* JDK version: Oracle jdk-13
* OS: `Linux vulcan 5.4.0-47-generic #51~18.04.1-Ubuntu`

Reproducer:
```java
@Liveness
@ApplicationScoped
public class NonInjectableHealthCheck implements HealthCheck {
    @Override
    public HealthCheckResponse call() {
        return HealthCheckResponse.up("nonInjectable");
    }
}

@ApplicationScoped
public class OtherBean {
    @Inject
    private NonInjectableHealthCheck healthCheck;
}
```
Ends up with:
```
2020.09.20 20:43:27 INFO org.jboss.weld.Event Thread[main,5,main]: WELD-000411: Observer method [BackedAnnotatedMethod] private io.helidon.microprofile.openapi.OpenApiCdiExtension.processAnnotatedType(@Observes ProcessAnnotatedType<X>) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
2020.09.20 20:43:27 INFO org.jboss.weld.Event Thread[main,5,main]: WELD-000411: Observer method [BackedAnnotatedMethod] public org.glassfish.jersey.ext.cdi1x.internal.ProcessAllAnnotatedTypes.processAnnotatedType(@Observes ProcessAnnotatedType<?>, BeanManager) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
2020.09.20 20:43:27 INFO org.jboss.weld.Bootstrap Thread[main,5,main]: WELD-ENV-002001: Weld SE container 1949b2d8-7e5e-48cf-9fc6-749891b0fb85 shut down
Exception in thread "main" org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type NonInjectableHealthCheck with qualifiers @Default
  at injection point [BackedAnnotatedField] @Inject private great.pkg.name.OtherBean.healthCheck
  at great.pkg.name.OtherBean.healthCheck(OtherBean.java:0)
WELD-001475: The following beans match by type, but none have matching qualifiers:
  - Managed Bean [class great.pkg.name.NonInjectableHealthCheck] with qualifiers [@Liveness @Any]

        at org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:378)
        at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:290)
        at org.jboss.weld.bootstrap.Validator.validateGeneralBean(Validator.java:143)
        at org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:164)
        at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:526)
        at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:64)
        at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:62)
        at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:62)
        at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:55)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1448)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)

```

**Comment by tomas-langer** [comment]
It should work if you annotate your injection point with the qualifier:
```
@Inject
@Liveness
```

**Comment by tomas-langer** [comment]
Nevertheless health checks are not designed for injection into other beans
