### ISSUE TITLE
Running dbClient insert in for loop yields threading issues

### ISSUE THREAD

**Issue by scottsue** [oracle/helidon#2484]
## Environment Details
* Helidon Version: 2.0.2
* Helidon SE or Helidon MP
* JDK version: Java 8
* OS: MacOS
* Docker version (if applicable):

----------

## Problem Description
When attempting to insert 100 rows very quickly (very tight for loop).  There looks to be a threading issue as 100 rows are not inserted into the table.  The observed behaviour is that only a few rows are inserted into the table.

## Steps to reproduce
Reproducer below:
`package io.helidon.examples.dbclient.jdbc;

import io.helidon.dbclient.DbClient;
import io.helidon.dbclient.jdbc.JdbcDbClientProviderBuilder;

import javax.sql.DataSource;
import java.util.HashMap;
import java.util.Map;

public class TestDao {

    private final CreateOrder createOrder;
    private final DbClient dbClient;

    /**
     */
    public TestDao() {
        this.createOrder = new CreateOrder();

        JdbcDbClientProviderBuilder jdbcDbClientProviderBuilder = JdbcDbClientProviderBuilder.create();
        jdbcDbClientProviderBuilder.username("username");
        jdbcDbClientProviderBuilder.password("password");
        jdbcDbClientProviderBuilder.url("jdbc:mysql://mapr-dev.localdomain:3306/pokemon?serverTimezone=UTC&useLegacyDatetimeCode=false&useServerPrepStmts=false&rewriteBatchedStatements=true");

        this.dbClient = jdbcDbClientProviderBuilder.build();

    }

    public final void runTest() throws InterruptedException {

        for (int i = 0; i < 100; i++) {
            String name = "name" + i;
            String type = "type" + i;
            this.createOrder.create(name, type);
        }

        Thread.sleep(60_000);

    }

    private class CreateOrder {

        private final String sql = "INSERT INTO pokemons (name, type) VALUES (:name, :type)";

        private CreateOrder() {
            //do nothing
        }

        final void create(String name, String type) {

            Map<String, Object> underlyingParameterMap = new HashMap<>();
            underlyingParameterMap.put("name", name);
            underlyingParameterMap.put("type", type);

            dbClient.execute(exec -> exec.createInsert(this.sql).params(underlyingParameterMap).execute()).thenAccept(count -> System.out.println("Inserted: " + count + " values")).exceptionally(throwable -> {
                System.out.println("Failed to initialize data");
                return null;
            });
        }
    }

    public static void main(String[] args) throws InterruptedException {
        TestDao testDao = new TestDao();
        testDao.runTest();
    }
}
`

Running this above code also looks to yield db timeout issues as well

`Caused by: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30004ms.
	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:697) ~[HikariCP-3.4.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:196) ~[HikariCP-3.4.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:161) ~[HikariCP-3.4.1.jar:?]
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100) ~[HikariCP-3.4.1.jar:?]
	at io.helidon.dbclient.jdbc.HikariConnectionPool.connection(HikariConnectionPool.java:53) ~[helidon-dbclient-jdbc-2.1.0.jar:2.1.0]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) ~[?:?]
	... 3 more`

**Comment by gargoyle** [comment]
I'm also seeing similar errors on my blog application. At a seemingly random time after starting the application, it become unable to talk to the database. 

```
Nov 07 21:14:45 web02 systemd[1]: Started Helidon Webapp.
Nov 07 21:14:46 web02 java[2103867]: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
Nov 07 21:14:46 web02 java[2103867]: SLF4J: Defaulting to no-operation (NOP) logger implementation
Nov 07 21:14:46 web02 java[2103867]: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Nov 07 21:14:47 web02 java[2103867]: 2020.11.07 21:14:47 INFO io.helidon.common.HelidonFeatures Thread[features-thread,5,main]: Helidon SE 2.0.1 features: [Config, Db Client, Health, Metrics, Security, WebServer]
Nov 07 21:14:47 web02 java[2103867]: 2020.11.07 21:14:47 INFO io.helidon.common.HelidonFeatures.experimental Thread[features-thread,5,main]: You are using experimental features. These APIs may change, please follow changelog!
Nov 07 21:14:47 web02 java[2103867]: 2020.11.07 21:14:47 INFO io.helidon.common.HelidonFeatures.experimental Thread[features-thread,5,main]:         Experimental feature: Db Client (DbClient)
Nov 07 21:14:47 web02 java[2103867]: 2020.11.07 21:14:47 INFO io.helidon.webserver.NettyWebServer Thread[nioEventLoopGroup-2-1,10,main]: Channel '@default' started: [id: 0x73621a2e, L:/[0:0:0:0:0:0:0:0]:8080]
Nov 07 21:14:47 web02 java[2103867]: WEB server is up! http://localhost:8080/
Nov 09 19:39:59 web02 java[2103867]: java.util.concurrent.CompletionException: io.helidon.dbclient.DbClientException: Failed to create a connection to jdbc:mysql://127.0.0.1:3306/blog2?allowPublicKeyRetrieval=true&useSSL=false
Nov 09 19:39:59 web02 java[2103867]:         at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
Nov 09 19:39:59 web02 java[2103867]:         at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
Nov 09 19:39:59 web02 java[2103867]:         at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1766)
Nov 09 19:39:59 web02 java[2103867]:         at io.helidon.common.context.Contexts.runInContext(Contexts.java:98)
Nov 09 19:39:59 web02 java[2103867]:         at io.helidon.common.context.ContextAwareExecutorImpl.lambda$wrap$1(ContextAwareExecutorImpl.java:129)
Nov 09 19:39:59 web02 java[2103867]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
Nov 09 19:39:59 web02 java[2103867]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
Nov 09 19:39:59 web02 java[2103867]:         at java.base/java.lang.Thread.run(Thread.java:832)
Nov 09 19:39:59 web02 java[2103867]: Caused by: io.helidon.dbclient.DbClientException: Failed to create a connection to jdbc:mysql://127.0.0.1:3306/blog2?allowPublicKeyRetrieval=true&useSSL=false
Nov 09 19:39:59 web02 java[2103867]:         at io.helidon.dbclient.jdbc.HikariConnectionPool.connection(HikariConnectionPool.java:56)
Nov 09 19:39:59 web02 java[2103867]:         at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764)
Nov 09 19:39:59 web02 java[2103867]:         ... 5 more
Nov 09 19:39:59 web02 java[2103867]: Caused by: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.
Nov 09 19:39:59 web02 java[2103867]:         at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:697)
Nov 09 19:39:59 web02 java[2103867]:         at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:196)
Nov 09 19:39:59 web02 java[2103867]:         at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:161)
Nov 09 19:39:59 web02 java[2103867]:         at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
Nov 09 19:39:59 web02 java[2103867]:         at io.helidon.dbclient.jdbc.HikariConnectionPool.connection(HikariConnectionPool.java:53)
Nov 09 19:39:59 web02 java[2103867]:         ... 6 more
```
My access log shows nothing unusual for the hour of 09/11/2020 19:00 to 19:59. I think 20 hits across the hour with the fastest volley being 3 hits in 3 seconds for "PetalBot".

**Comment by tomas-langer** [comment]
There is a tiny problem with the way you execute the DB requests. The Db Client is reactive, so executing inserts in a loop without waiting for execution to finish will spawn 100 parallel requests. These are limited by the executor service used by DbClient.
Eventually all threads from the executor service call the database, that can result in up to 100 connections requested from the pool. This can be a problem (depending on database configuration and usage).

I am nevertheless trying to investigate why we would get a timeout. I could not yet reproduce the problem.

**Comment by dansiviter** [comment]
I've encountered a similar issue. As a technical exercise I thought I'd try updating the TechEmpower for Helidon to use v2 and DB client and see what performance improvements it would get. Unfortunately, when running `http://localhost:8080/queries?queries=20` manually it seems fine, including multiple executions. When I step that up to `http://localhost:8080/queries?queries=30` it hangs and eventually times out with the stacktrace below. It's highly possible I have a bug in my code as I'm still getting my head round how to use the Reactive libraries properly, but it does exhibit similar behaviour.

```text
2020.11.20 20:21:14 WARNING io.helidon.webserver.RequestRouting !thread!: Default error handler: Unhandled exception encountered.
java.util.concurrent.ExecutionException: Unhandled 'cause' of this exception encountered.
        at io.helidon.webserver.RequestRouting$RoutedRequest.defaultHandler(RequestRouting.java:397)
        at io.helidon.webserver.RequestRouting$RoutedRequest.nextNoCheck(RequestRouting.java:377)
        at io.helidon.webserver.RequestRouting$RoutedRequest.nextNoCheck(RequestRouting.java:344)
        at io.helidon.webserver.RequestRouting$RoutedResponse.send(RequestRouting.java:483)
        at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:986)
        at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:970)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
        at io.helidon.common.reactive.SingleToFuture.onError(SingleToFuture.java:74)
        at io.helidon.common.reactive.MultiTappedPublisher$MultiTappedSubscriber.onError(MultiTappedPublisher.java:247)
        at io.helidon.common.reactive.MultiMapperPublisher$MapperSubscriber.onError(MultiMapperPublisher.java:89)
        at io.helidon.common.reactive.MultiCollectPublisher$CollectSubscriber.onError(MultiCollectPublisher.java:101)
        at io.helidon.common.reactive.MultiConcatArray$ConcatArraySubscriber.onError(MultiConcatArray.java:73)
        at io.helidon.common.reactive.MultiMapperPublisher$MapperSubscriber.onError(MultiMapperPublisher.java:89)
        at io.helidon.common.reactive.MultiMapperPublisher$MapperSubscriber.onError(MultiMapperPublisher.java:89)
        at io.helidon.common.reactive.MultiTappedPublisher$MultiTappedSubscriber.onError(MultiTappedPublisher.java:247)
        at io.helidon.common.reactive.DeferredScalarSubscription.error(DeferredScalarSubscription.java:132)
        at io.helidon.common.reactive.MultiFromCompletionStage$CompletionStageSubscription.accept(MultiFromCompletionStage.java:70)
        at io.helidon.common.reactive.MultiFromCompletionStage$CompletionStageSubscription.accept(MultiFromCompletionStage.java:52)
        at io.helidon.common.reactive.MultiFromCompletionStage$AtomicBiConsumer.accept(MultiFromCompletionStage.java:95)
        at io.helidon.common.reactive.MultiFromCompletionStage$AtomicBiConsumer.accept(MultiFromCompletionStage.java:88)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:883)
        at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2251)
        at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:143)
        at io.helidon.common.reactive.MultiFromCompletionStage.subscribe(MultiFromCompletionStage.java:49)
        at io.helidon.common.reactive.SingleFromCompletionStage.subscribe(SingleFromCompletionStage.java:38)
        at io.helidon.common.reactive.SingleTappedPublisher.subscribe(SingleTappedPublisher.java:67)
        at io.helidon.common.reactive.SingleMapperPublisher.subscribe(SingleMapperPublisher.java:41)
        at io.helidon.common.reactive.SingleMapperPublisher.subscribe(SingleMapperPublisher.java:41)
        at io.helidon.common.reactive.MultiConcatArray$ConcatArraySubscriber.nextSource(MultiConcatArray.java:92)
        at io.helidon.common.reactive.MultiConcatArray$ConcatArraySubscriber.onComplete(MultiConcatArray.java:83)
        at io.helidon.common.reactive.MultiMapperPublisher$MapperSubscriber.onComplete(MultiMapperPublisher.java:98)
        at io.helidon.common.reactive.MultiMapperPublisher$MapperSubscriber.onComplete(MultiMapperPublisher.java:98)
        at io.helidon.common.reactive.MultiTappedPublisher$MultiTappedSubscriber.onComplete(MultiTappedPublisher.java:264)
        at io.helidon.common.reactive.DeferredScalarSubscription.complete(DeferredScalarSubscription.java:92)
        at io.helidon.common.reactive.MultiFromCompletionStage$CompletionStageSubscription.accept(MultiFromCompletionStage.java:72)
        at io.helidon.common.reactive.MultiFromCompletionStage$CompletionStageSubscription.accept(MultiFromCompletionStage.java:52)
        at io.helidon.common.reactive.MultiFromCompletionStage$AtomicBiConsumer.accept(MultiFromCompletionStage.java:95)
        at io.helidon.common.reactive.MultiFromCompletionStage$AtomicBiConsumer.accept(MultiFromCompletionStage.java:88)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
        at io.helidon.common.reactive.SingleToOptionalFuture.onComplete(SingleToOptionalFuture.java:77)
        at io.helidon.common.reactive.SingleFromPublisher$SingleSubscriber.onComplete(SingleFromPublisher.java:88)
        at io.helidon.common.reactive.SingleFlatMapMulti$FlatMapSubscriber$InnerSubscriber.onComplete(SingleFlatMapMulti.java:170)
        at io.helidon.common.reactive.SingleFlatMapMulti$FlatMapSubscriber$InnerSubscriber.onComplete(SingleFlatMapMulti.java:170)
        at io.helidon.common.reactive.SingleFlatMapMulti$FlatMapSubscriber$InnerSubscriber.onComplete(SingleFlatMapMulti.java:170)
        at io.helidon.dbclient.jdbc.JdbcStatementQuery$RowPublisher.lambda$subscribe$0(JdbcStatementQuery.java:309)
        at io.helidon.common.context.Contexts.runInContext(Contexts.java:98)
        at io.helidon.common.context.ContextAwareExecutorImpl.lambda$wrap$1(ContextAwareExecutorImpl.java:129)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: io.helidon.dbclient.DbClientException: Failed to create a connection to jdbc:postgresql://localhost:5432/hello_world
        at io.helidon.dbclient.jdbc.HikariConnectionPool.connection(HikariConnectionPool.java:56)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
        at io.helidon.common.context.Contexts.runInContext(Contexts.java:98)
        at io.helidon.common.context.ContextAwareExecutorImpl.lambda$wrap$1(ContextAwareExecutorImpl.java:129)
        ... 3 more
Caused by: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30001ms.
        at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:697)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:196)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:161)
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
        at io.helidon.dbclient.jdbc.HikariConnectionPool.connection(HikariConnectionPool.java:53)
``` 

The draft PR is here: TechEmpower/FrameworkBenchmarks#6153

**Comment by dansiviter** [comment]
FYI I've upgraded to v2.2.0 and this is still an issue.

**Comment by dansiviter** [comment]
So after having dug into this, the problem is essentially the current design permits [`Connection#close()`](/oracle/helidon/blob/2.3.0/dbclient/jdbc/src/main/java/io/helidon/dbclient/jdbc/JdbcDbClient.java#L372) operations to be queued up in the thread pool. Unfortunately, if the thread pool is exhausted by blocking requests for connections we have a race condition between borrowing and returning to the pool.

From the thread dump:
```
"helidon-1" #15 daemon prio=5 os_prio=0 cpu=46.88ms elapsed=20.82s tid=0x000001e63ee82000 nid=0x2fcc waiting on condition  [0x00000055798fe000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@11.0.9.1/Native Method)
        - parking to wait for  <0x0000000713f43fb8> (a java.util.concurrent.SynchronousQueue$TransferQueue)
        at java.util.concurrent.locks.LockSupport.parkNanos(java.base@11.0.9.1/LockSupport.java:234)
        at java.util.concurrent.SynchronousQueue$TransferQueue.awaitFulfill(java.base@11.0.9.1/SynchronousQueue.java:761)
        at java.util.concurrent.SynchronousQueue$TransferQueue.transfer(java.base@11.0.9.1/SynchronousQueue.java:689)
        at java.util.concurrent.SynchronousQueue.poll(java.base@11.0.9.1/SynchronousQueue.java:937)
        at com.zaxxer.hikari.util.ConcurrentBag.borrow(ConcurrentBag.java:152)  <-- blocking call
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:180)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
        at io.helidon.dbclient.jdbc.HikariConnectionPool.connection(HikariConnectionPool.java:53)
        at io.helidon.dbclient.jdbc.JdbcDbClient$JdbcExecute$$Lambda$458/0x000000080030b440.get(Unknown Source)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(java.base@11.0.9.1/CompletableFuture.java:1700)
        at io.helidon.common.context.Contexts.runInContext(Contexts.java:117)
        at io.helidon.common.context.ContextAwareExecutorImpl.lambda$wrap$5(ContextAwareExecutorImpl.java:154)
        at io.helidon.common.context.ContextAwareExecutorImpl$$Lambda$460/0x000000080030ac40.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.9.1/ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.9.1/ThreadPoolExecutor.java:628)
        at java.lang.Thread.run(java.base@11.0.9.1/Thread.java:834)

   Locked ownable synchronizers:
        - <0x000000071434f3e8> (a java.util.concurrent.ThreadPoolExecutor$Worker)
```

**Comment by klustria** [comment]
I have reproduced the issue and are seeing occurrences of this exception:

`
Nov 18, 2021 5:34:40 PM io.helidon.examples.dbclient.jdbc.TestDao$CreateOrder lambda$create$2
WARNING: Failed to insert data with name: name4
java.util.concurrent.CompletionException: io.helidon.dbclient.DbClientException: Failed to create a connection to jdbc:mysql://127.0.0.1:3306/pokemon?useSSL=false
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1702)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: io.helidon.dbclient.DbClientException: Failed to create a connection to jdbc:mysql://127.0.0.1:3306/pokemon?useSSL=false
        at io.helidon.dbclient.jdbc.HikariConnectionPool.connection(HikariConnectionPool.java:60)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
        ... 3 more
Caused by: java.sql.SQLTransientConnectionException: mysql - Connection is not available, request timed out after 30005ms.
        at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:696)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:181)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:146)
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
        at io.helidon.dbclient.jdbc.HikariConnectionPool.connection(HikariConnectionPool.java:57)
        ... 4 more

`

**Comment by klustria** [comment]
From this nice writeup about Hiraki Connection Pool: https://medium.com/@rajchandak1993/understanding-hikaricps-connection-pooling-behaviour-467c5a1a1506, it looks like it is indeed either because pool size is not enough or connection initialization timeout is not enough hence causing an error like` [HikariCP]: connection not available, request timed out after <elapsed timeout> ms`.

**Comment by klustria** [comment]
The default pool size is only set to 10: https://github.com/openbouquet/HikariCP/blob/master/src/main/java/com/zaxxer/hikari/HikariConfig.java#L110

**Comment by klustria** [comment]
Putting a delay on each of the iteration to as little as 3 ms seems to help with the contention.

**Comment by klustria** [comment]
A loop reduced to 20 iterations also works and connection reuse is observed:

```
Connection is created: HikariProxyConnection@753915838 wrapping com.mysql.cj.jdbc.ConnectionImpl@2ea6e30c
Connection is created: HikariProxyConnection@1051557354 wrapping com.mysql.cj.jdbc.ConnectionImpl@2ea6e30c
Connection is created: HikariProxyConnection@290968107 wrapping com.mysql.cj.jdbc.ConnectionImpl@1f903e71
Connection is created: HikariProxyConnection@1164235984 wrapping com.mysql.cj.jdbc.ConnectionImpl@4ba3320c
Connection is created: HikariProxyConnection@1826968267 wrapping com.mysql.cj.jdbc.ConnectionImpl@6222a127
Connection is created: HikariProxyConnection@417848573 wrapping com.mysql.cj.jdbc.ConnectionImpl@16203191
Connection is created: HikariProxyConnection@1103094720 wrapping com.mysql.cj.jdbc.ConnectionImpl@4f781587
Connection is created: HikariProxyConnection@2073605235 wrapping com.mysql.cj.jdbc.ConnectionImpl@6e218997
Connection is created: HikariProxyConnection@812291151 wrapping com.mysql.cj.jdbc.ConnectionImpl@3455169a
Connection is created: HikariProxyConnection@304068493 wrapping com.mysql.cj.jdbc.ConnectionImpl@571d3baa
Connection is created: HikariProxyConnection@1122458481 wrapping com.mysql.cj.jdbc.ConnectionImpl@5970d6ab
Connection is created: HikariProxyConnection@1908082048 wrapping com.mysql.cj.jdbc.ConnectionImpl@3455169a
Connection is created: HikariProxyConnection@1629476932 wrapping com.mysql.cj.jdbc.ConnectionImpl@4ba3320c
Connection is created: HikariProxyConnection@1322270744 wrapping com.mysql.cj.jdbc.ConnectionImpl@1f903e71
Connection is created: HikariProxyConnection@521817291 wrapping com.mysql.cj.jdbc.ConnectionImpl@16203191
Connection is created: HikariProxyConnection@1399911901 wrapping com.mysql.cj.jdbc.ConnectionImpl@6e218997
Connection is created: HikariProxyConnection@900428815 wrapping com.mysql.cj.jdbc.ConnectionImpl@6222a127
Connection is created: HikariProxyConnection@1901567604 wrapping com.mysql.cj.jdbc.ConnectionImpl@2ea6e30c
Connection is created: HikariProxyConnection@408546631 wrapping com.mysql.cj.jdbc.ConnectionImpl@4f781587
Connection is created: HikariProxyConnection@1711279775 wrapping com.mysql.cj.jdbc.ConnectionImpl@5970d6ab
Connection is created: HikariProxyConnection@1103993334 wrapping com.mysql.cj.jdbc.ConnectionImpl@571d3baa
```

**Comment by klustria** [comment]
After further analysis, it is observed that the issue is caused either due to thread starvation or connection pool exhaustion. As mentioned above, the Hikari DataSource Pool has a default pool size of only 10 with no flexibility to increase it. At the same time, the ThreadPoolSupplier has a default core pool size of 10 also is not configurable. In a tight loop of 100 iterations, the DS getConnection() will compete with the Datasource statement execution followed by close connection. The getConnection and closeConnection are running on different threads with getConnection mostly holding on to the thread until a connection becomes available from the pool or if it times out at which time, the operation just fail. However, with only 10 max connection available from the pool, the competition becomes more intense as the number of operations increase and hence there will be not be enough time to put the connection back to the pool via the closeConnection call. With 20 iterations, this will work fine as it will have enough time for the various datasource operations to share the available threads and/or connection pool. Also, if there is a delay between iteration even with as little as 5 ms will be good enough help to allow the 100 iterations to share between the available thread and or DS connection.

**Comment by klustria** [comment]
There is actually a way to increase pool size for ThreadPool that is used by the JDBCDbClientProviderBuilder class, by using the `executor-service` property in application config. For example, specific to this use case you can specify growth rate of 10% (defaults to 0 meaning no growth) on a pool with default core pool size of 10 and max pool size of 50 to encourage increase in pool size as the need grows:

```
db:
  executor-service:
    growth-rate: 10
  source: jdbc
  connection:
    url: jdbc:mysql://127.0.0.1:3306/pokemon?useSSL=false
    username: user
    password: password
    poolName: mysql
```
Alternatively, the core-pool can also be increased to allow the parallelism to happen:
```
db:
  executor-service:
     core-pool-size: 100
     max-pool-size: 100
  source: jdbc
  connection:
    url: jdbc:mysql://127.0.0.1:3306/pokemon?useSSL=false
    username: user
    password: password
    poolName: mysql
```

**Comment by dansiviter** [comment]
To fix this issue, the connection should be closed synchronously rather than being placed separately and asynchronously on the executor. That would return the connection back to the pool and fix the thread exhaustion issue.

**Comment by klustria** [comment]
Test reproducer code to validate the fix using mysql db:

```java
package io.helidon.examples.dbclient.jdbc;

import io.helidon.dbclient.DbClient;
import io.helidon.dbclient.DbRow;
import io.helidon.config.Config;
import io.helidon.common.reactive.Multi;

import java.util.logging.Level;
import java.util.logging.Logger;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Iterator;
import java.util.stream.Collectors;

public class TestDao {
    private static final Logger LOGGER = Logger.getLogger(TestDao.class.getName());

    private final ProcessPokemon processPokemon;
    private final DbClient dbClient;

    /**
     */
    public TestDao() {

        this.processPokemon = new ProcessPokemon();

        Config config = Config.create();
        Config dbConfig = config.get("db");

        // Client services are added through a service loader - see mongoDB example for explicit services
        this.dbClient = DbClient.builder(dbConfig).build();
        dbClient.execute(handle -> handle.namedDml("create-table"))
                .thenAccept(System.out::println)
                .exceptionally(throwable -> {
                    LOGGER.log(Level.WARNING, "Failed to create table, maybe it already exists?", throwable);
                    return null;
                });
        System.out.println("Create table completed...");
        try {
            Thread.sleep(5000);
        } catch(InterruptedException ie) {
        }
    }

    public final void runTest() throws InterruptedException {
        // Insert
        for (int i = 0; i < 100; i++) {
            String name = "name" + i;
            String type = "type" + i;
            this.processPokemon.insert(name, type);
        }
        Thread.sleep(10000);
        this.processPokemon.printAll();

        // Update
        for (int i = 0; i < 100; i++) {
            String name = "name" + i;
            String type = "newtype" + i;
            this.processPokemon.update(name, type);
        }
        Thread.sleep(10000);
        this.processPokemon.printAll();

        // Delete
        for (int i = 0; i < 100; i++) {
            String name = "name" + i;
            this.processPokemon.delete(name);
        }
        Thread.sleep(10000);
        this.processPokemon.printAll();
    }

    private class ProcessPokemon {

        private final String insertSql = "INSERT INTO pokemons (name, type) VALUES (:name, :type)";
        private final String updateSql = "UPDATE pokemons SET type = :type WHERE name = :name";
        private final String deleteSql = "DELETE FROM pokemons WHERE name = :name";

        private ProcessPokemon() {
            //do nothing
        }

        final void insert(String name, String type) {
            Map<String, Object> underlyingParameterMap = new HashMap<>();
            underlyingParameterMap.put("name", name);
            underlyingParameterMap.put("type", type);
            dbClient.execute(exec -> exec.createInsert(this.insertSql).params(underlyingParameterMap).execute())
                    // dbClient.inTransaction(tx -> tx.createInsert(this.sql).params(underlyingParameterMap).execute())
                    .thenAccept(
                            count -> System.out.println("Inserted: " + count + " values" + " with name: " + name + " for thread name: " + java.lang.Thread.currentThread().getName() + " and thread id: " + java.lang.Thread.currentThread().getId())
                    )
                    .exceptionally(throwable -> {
                        LOGGER.log(Level.WARNING, "Failed to insert data with name: " + name + ", and error message:" + throwable.getMessage());
                        return null;
                    });
        }

       final void delete(String name) {
            Map<String, Object> underlyingParameterMap = new HashMap<>();
            underlyingParameterMap.put("name", name);
            dbClient.execute(exec -> exec.createDelete(this.deleteSql).params(underlyingParameterMap).execute())
                    // dbClient.inTransaction(tx -> tx.createDelete(this.sql).params(underlyingParameterMap).execute())
                    .thenAccept(
                            count -> System.out.println("Deleted: " + count + " values" + " with name: " + name + " for thread name: " + java.lang.Thread.currentThread().getName() +" and thread id: " + java.lang.Thread.currentThread().getId())
                    )
                    .exceptionally(throwable -> {
                        LOGGER.log(Level.WARNING, "Failed to delete data with name: " + name + ", and error message:" + throwable.getMessage());
                        return null;
                    });
        }

        final void update(String name, String type) {
            Map<String, Object> underlyingParameterMap = new HashMap<>();
            underlyingParameterMap.put("name", name);
            underlyingParameterMap.put("type", type);
            dbClient.execute(exec -> exec.createUpdate(this.updateSql).params(underlyingParameterMap).execute())
                    // dbClient.inTransaction(tx -> tx.createDelete(this.sql).params(underlyingParameterMap).execute())
                    .thenAccept(
                            count -> System.out.println("Updated: " + count + " values" + " with name: " + name + " for thread name: " + java.lang.Thread.currentThread().getName() +" and thread id: " + java.lang.Thread.currentThread().getId())
                    )
                    .exceptionally(throwable -> {
                        LOGGER.log(Level.WARNING, "Failed to update data with name: " + name + ", and error message:" + throwable.getMessage());
                        return null;
                    });
        }

        final void printAll() {
            System.out.println("Printing all records in Pokemon table");
            Multi<DbRow> rows = dbClient.execute(exec -> exec.namedQuery("select-all"));
            List<DbRow> rowsList = rows.collectList().await();
            for (DbRow row : rowsList) {
                String name = row.column(1).as(String.class);
                String type = row.column(2).as(String.class);
                System.out.println(String.format("Name=%s, Type=%s", name, type));
            }
        }
    }


    public static void main(String[] args) throws InterruptedException {
        TestDao testDao = new TestDao();
        testDao.runTest();
    }
}
```

**Comment by klustria** [comment]
Backported to v2.4.2 via https://github.com/oracle/helidon/pull/3860

**Comment by ieuan-richards** [comment]
Hi, I'm still seeing a very similar issue to this but with DBExecute.createNamedQuery where it looks like the connection is returned to the pool in a different thread than it's created it. Is it possible it hasn't been resolved in all cases?
