### ISSUE TITLE
Request Scope ServerRequest injection error in Fallback 

### ISSUE THREAD

**Issue by bunto76** [oracle/helidon#2532]
## Environment Details
* Helidon Version: 2.1.1-snapshot
* Helidon MP
* JDK version: 11.0.6
* OS: macOS 10.15.5

----------

## Problem Description
When using a Request Scope bean which has ServerRequest context injected in a Fallback method an exception is thrown: java.lang.IllegalStateException: Proxiable context org.glassfish.jersey.inject.hk2.RequestContext@1ff3ff84 findOrCreate returned a null for descriptor SystemDescriptor. 
Full stack trace:

```
A MultiException has 1 exceptions.  They are:
1. java.lang.IllegalStateException: Proxiable context org.glassfish.jersey.inject.hk2.RequestContext@1ff3ff84 findOrCreate returned a null for descriptor SystemDescriptor(
	implementation=org.glassfish.jersey.inject.hk2.SupplierFactoryBridge
	contracts={io.helidon.webserver.ServerRequest}
	scope=org.glassfish.jersey.process.internal.RequestScoped
	qualifiers={}
	descriptorType=PROVIDE_METHOD
	descriptorVisibility=NORMAL
	metadata=
	rank=0
	loader=org.glassfish.hk2.utilities.binding.AbstractBinder$2@49c232f0
	proxiable=true
	proxyForSameScope=false
	analysisName=null
	id=20
	locatorId=0
	identityHashCode=299563377
	reified=true) and handle ServiceHandle(SystemDescriptor(
	implementation=org.glassfish.jersey.inject.hk2.SupplierFactoryBridge
	contracts={io.helidon.webserver.ServerRequest}
	scope=org.glassfish.jersey.process.internal.RequestScoped
	qualifiers={}
	descriptorType=PROVIDE_METHOD
	descriptorVisibility=NORMAL
	metadata=
	rank=0
	loader=org.glassfish.hk2.utilities.binding.AbstractBinder$2@49c232f0
	proxiable=true
	proxyForSameScope=false
	analysisName=null
	id=20
	locatorId=0
	identityHashCode=299563377
	reified=true),297619282)

MultiException stack 1 of 1
java.lang.IllegalStateException: Proxiable context org.glassfish.jersey.inject.hk2.RequestContext@1ff3ff84 findOrCreate returned a null for descriptor SystemDescriptor(
	implementation=org.glassfish.jersey.inject.hk2.SupplierFactoryBridge
	contracts={io.helidon.webserver.ServerRequest}
	scope=org.glassfish.jersey.process.internal.RequestScoped
	qualifiers={}
	descriptorType=PROVIDE_METHOD
	descriptorVisibility=NORMAL
	metadata=
	rank=0
	loader=org.glassfish.hk2.utilities.binding.AbstractBinder$2@49c232f0
	proxiable=true
	proxyForSameScope=false
	analysisName=null
	id=20
	locatorId=0
	identityHashCode=299563377
	reified=true) and handle ServiceHandle(SystemDescriptor(
	implementation=org.glassfish.jersey.inject.hk2.SupplierFactoryBridge
	contracts={io.helidon.webserver.ServerRequest}
	scope=org.glassfish.jersey.process.internal.RequestScoped
	qualifiers={}
	descriptorType=PROVIDE_METHOD
	descriptorVisibility=NORMAL
	metadata=
	rank=0
	loader=org.glassfish.hk2.utilities.binding.AbstractBinder$2@49c232f0
	proxiable=true
	proxyForSameScope=false
	analysisName=null
	id=20
	locatorId=0
	identityHashCode=299563377
	reified=true),297619282)
	at org.jvnet.hk2.internal.MethodInterceptorImpl.internalInvoke(MethodInterceptorImpl.java:68)
	at org.jvnet.hk2.internal.MethodInterceptorImpl.invoke(MethodInterceptorImpl.java:101)
	at org.jvnet.hk2.internal.MethodInterceptorInvocationHandler.invoke(MethodInterceptorInvocationHandler.java:39)
	at com.sun.proxy.$Proxy87.headers(Unknown Source)
	at test.TenantContext.getTenantId(TenantContext.java:56)
	at test.TenantContext$Proxy$_$$_WeldClientProxy.getTenantId(Unknown Source)
	at test.SomeService.testFallback(SomeService.java:77)
	at test.SomeService$Proxy$_$$_WeldSubclass.testFallback(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.helidon.microprofile.faulttolerance.CommandFallback.execute(CommandFallback.java:104)
	at io.helidon.microprofile.faulttolerance.MethodInvoker.lambda$requestContextSupplier$11(MethodInvoker.java:466)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:219)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:314)
	at io.helidon.microprofile.faulttolerance.MethodInvoker.lambda$requestContextSupplier$12(MethodInvoker.java:462)
	at io.helidon.microprofile.faulttolerance.MethodInvoker.lambda$toCompletionStageSupplier$19(MethodInvoker.java:637)
	at io.helidon.microprofile.faulttolerance.MethodInvoker.lambda$createMethodHandler$14(MethodInvoker.java:558)
	at io.helidon.faulttolerance.FallbackImpl.lambda$invoke$2(FallbackImpl.java:67)
	at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:986)
	at java.base/java.util.concurrent.CompletableFuture.uniExceptionallyStage(CompletableFuture.java:1004)
	at java.base/java.util.concurrent.CompletableFuture.exceptionally(CompletableFuture.java:2307)
	at java.base/java.util.concurrent.CompletableFuture.exceptionally(CompletableFuture.java:143)
	at io.helidon.faulttolerance.FallbackImpl.invoke(FallbackImpl.java:62)
	at io.helidon.faulttolerance.FaultTolerance$TypedBuilder$FtHandlerTypedImpl.lambda$invoke$1(FaultTolerance.java:276)
	at io.helidon.faulttolerance.FaultTolerance$TypedBuilder$FtHandlerTypedImpl.invoke(FaultTolerance.java:279)
	at io.helidon.microprofile.faulttolerance.MethodInvoker.lambda$get$7(MethodInvoker.java:383)
	at io.helidon.common.context.Contexts.runInContextWithThrow(Contexts.java:142)
	at io.helidon.microprofile.faulttolerance.MethodInvoker.lambda$get$8(MethodInvoker.java:382)
	at io.helidon.microprofile.faulttolerance.MethodInvoker.get(MethodInvoker.java:435)
	at io.helidon.microprofile.faulttolerance.CommandInterceptor.interceptCommand(CommandInterceptor.java:54)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.weld.interceptor.reader.SimpleInterceptorInvocation$SimpleMethodInvocation.invoke(SimpleInterceptorInvocation.java:73)
	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeAroundInvoke(InterceptorMethodHandler.java:84)
	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeInterception(InterceptorMethodHandler.java:72)
	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.invoke(InterceptorMethodHandler.java:56)
	at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:79)
	at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:68)
	at test.SomeService$Proxy$_$$_WeldSubclass.test(Unknown Source)
	at test.SomeService$Proxy$_$$_WeldClientProxy.test(Unknown Source)
	at test.MultiTenantService.getTenantResource(MultiTenantService.java:66)
	at test.MultiTenantService$Proxy$_$$_WeldSubclass.getTenantResource$$super(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:51)
	at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:78)
	at io.helidon.metrics.HelidonSimpleTimer$SimpleTimerImpl.time(HelidonSimpleTimer.java:184)
	at io.helidon.metrics.HelidonSimpleTimer.time(HelidonSimpleTimer.java:64)
	at io.helidon.microprofile.metrics.InterceptorSyntheticSimplyTimed.interceptRestEndpoint(InterceptorSyntheticSimplyTimed.java:72)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.weld.interceptor.reader.SimpleInterceptorInvocation$SimpleMethodInvocation.invoke(SimpleInterceptorInvocation.java:73)
	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeAroundInvoke(InterceptorMethodHandler.java:84)
	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeInterception(InterceptorMethodHandler.java:72)
	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.invoke(InterceptorMethodHandler.java:56)
	at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:79)
	at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:68)
	at test.MultiTenantService$Proxy$_$$_WeldSubclass.getTenantResource(Unknown Source)
	at test.MultiTenantService$Proxy$_$$_WeldClientProxy.getTenantResource(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
	at io.helidon.webserver.jersey.JerseySupport$JerseyHandler.lambda$doAccept$3(JerseySupport.java:265)
	at io.helidon.common.context.Contexts.runInContext(Contexts.java:98)
	at io.helidon.common.context.ContextAwareExecutorImpl.lambda$wrap$1(ContextAwareExecutorImpl.java:129)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
This is specfic to the Fallback and to the ServerRequest rather than RequestScoped more generally. I found the issue is seen with Fallback by itself, as well as Fallback for a Retry or CircuitBreaker. The example below is a contrived CircuitBreaker and Fallback scenario, with half of requests failing. I couldn't reproduce this issue on the 2.1.0 release.

## Steps to reproduce

A simple Resource:
```
@Path("/test")
@RequestScoped
public class MultiTenantService {

  @Inject
  SomeService someService;

  @GET
  public String getTenantResource() {
    return someService.test();
  }

}
```

Service with CircuitBreaker and Fallback:
```
@ApplicationScoped
public class SomeService {

  private AtomicLong counter = new AtomicLong(0);

  @Inject
  TenantContext tenantContext;

  @CircuitBreaker(successThreshold = 2, requestVolumeThreshold = 4)
  @Fallback(fallbackMethod = "testFallback")
  public String test() throws Exception {
    maybeFail();
    return tenantContext.getTenantId();
  }

  public String testFallback() throws Exception {
    String tenantId = tenantContext.getTenantId();
    // use the tenant ID in the Fallback,
    return " Please try again later!";
  }

  private void maybeFail() {
    final Long invocationNumber = counter.getAndIncrement();
    if (invocationNumber % 4 > 1) { // alternate 2 successful and 2 failing invocations
      throw new RuntimeException("Service failed.");
    }
  }
}

```
The Request Scoped bean invoked that contains the ServerRequest context:
```
@RequestScoped
public class TenantContext {

  @Context
  private ServerRequest mRequest;

  public String getTenantId() {
    return mRequest.headers().value("x-tenant-id").orElse(null);
  }
}
```

**Comment by spericas** [comment]
PR #2534
