### ISSUE TITLE
Please improve the log message when using Single#map in your route's handler and by mistake return null

### ISSUE THREAD

**Issue by FWiesner** [oracle/helidon#2554]
```
java.util.concurrent.CompletionException: java.lang.NullPointerException: The mapper returned a null value.
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:743)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:731)
	at java.base/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2108)
	at java.base/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:143)
	at io.helidon.common.reactive.CompletionAwaitable.thenAccept(CompletionAwaitable.java:68)
	at io.helidon.common.reactive.Single.forSingle(Single.java:682)
        <your code here>
```
`The mapper returned a null value` is a very generic error message. Probably replace it with something like `The map pipeline step has returned a null reference which is illegal. Consider returning an empty Optional`

**Comment by danielkec** [comment]
I am not really sure its a good idea to go for something that exotic, developers used to work with reactive libraries are probably used to describe mapping function as a mapper. 

Comparison with other implementations:
```
Helidon: The mapper returned a null value.
RxJava : The mapper function returned a null value.
Reactor: The mapper returned a null value.
Mutiny : The mapper returned `null`
Akka   : Element must not be null, rule 2.13
```

**Comment by tomas-langer** [comment]
@FWiesner could you please post the code that causes this issue? Thanks
