### ISSUE TITLE
HTTP/2 stream error with high number of concurrent request

### ISSUE THREAD

**Issue by spericas** [oracle/helidon#2587]
Environment Details
·        Helidon Version: 2.1.0
·        Helidon MP
·        JDK version: 11
·        OS: Windows or linux
·        Docker version (if applicable): NA
Problem Description

·        Helidon MP application has simple GET /great api configured with http2 protocol, which we are trying to hit with 100+ user using JavaScript client. Out of 100 request very few request are getting failed and  Failure rate varies every run.

·        We have tested Concurrent user request with Gatling , JMeter, Chrome, Firefox. concurrency working with Gatling and JMeter . but when its tested with browser very few request getting errored out giving HTTP2_server_refused_stream or ERR_CONNECTION_CLOSED on browser. this issue occurring only with http2, not with http1.

State if the problem is easily reproducible or happens intermittently

·        Reproducible

Steps to reproduce

·        download the code from Attachment.

·        unzip helidon-quickstart-mp.zip

·        cd helidon-quickstart-mp/target

·        java -jar helidon-quickstart-mp.jar

·        run sync_client_test_1.html in browser

·        open network tab and select XHR from the filter

·        refresh the page again. will start seeing out of 100 request few request be shown as failed with error "connection closed" or "HTTP2 server refused stream" or ERR:NET_FAILED.

·        Note: in case you are not able to find any failure reload the page several time.
or else open sync_client_test_1.js with notepad, edit below number from 100 to 200 or more and reload the page
var arr_list = new Array(100);

 

Include stack traces or command outputs

```
java.util.concurrent.CompletionException: java.lang.IllegalStateException: An exception occurred when writing last http content.
at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:632)
at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
at io.helidon.common.reactive.SingleToFuture.onError(SingleToFuture.java:74)
at io.helidon.common.reactive.DeferredScalarSubscription.error(DeferredScalarSubscription.java:132)
at io.helidon.common.reactive.MultiFromCompletionStage$CompletionStageSubscription.accept(MultiFromCompletionStage.java:70)
at io.helidon.common.reactive.MultiFromCompletionStage$CompletionStageSubscription.accept(MultiFromCompletionStage.java:52)
at io.helidon.common.reactive.MultiFromCompletionStage$AtomicBiConsumer.accept(MultiFromCompletionStage.java:95)
at io.helidon.common.reactive.MultiFromCompletionStage$AtomicBiConsumer.accept(MultiFromCompletionStage.java:88)
at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
at io.helidon.webserver.BareResponseImpl.completeResponseFuture(BareResponseImpl.java:202)
at io.helidon.webserver.BareResponseImpl.lambda$completeOnFailureListener$8(BareResponseImpl.java:287)
at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)
at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)
at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608)
at io.netty.util.concurrent.DefaultPromise.setFailure(DefaultPromise.java:109)
at io.netty.channel.DefaultChannelPromise.setFailure(DefaultChannelPromise.java:89)
at io.netty.handler.codec.http2.Http2CodecUtil$SimpleChannelPromiseAggregator.setPromise(Http2CodecUtil.java:375)
at io.netty.handler.codec.http2.Http2CodecUtil$SimpleChannelPromiseAggregator.doneAllocatingPromises(Http2CodecUtil.java:294)
at io.netty.handler.codec.http2.HttpToHttp2ConnectionHandler.write(HttpToHttp2ConnectionHandler.java:128)
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1071)
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalStateException: An exception occurred when writing last http content.
... 22 common frames omitted
Caused by: java.lang.IllegalArgumentException: Stream no longer exists: 53
at io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder.requireStream(DefaultHttp2ConnectionEncoder.java:419)
at io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder.writeData(DefaultHttp2ConnectionEncoder.java:125)
at io.netty.handler.codec.http2.DecoratingHttp2FrameWriter.writeData(DecoratingHttp2FrameWriter.java:39)
at io.netty.handler.codec.http2.HttpToHttp2ConnectionHandler.write(HttpToHttp2ConnectionHandler.java:113)
... 10 common frames omitted
```

**Comment by spericas** [comment]
[tesing.zip](https://github.com/oracle/helidon/files/5659799/tesing.zip)

**Comment by spericas** [comment]
Related to PR #2591
