### ISSUE TITLE
Documentation Helidon SE: Polling strategy of type watch is not supported

### ISSUE THREAD

**Issue by tvallin** [oracle/helidon#2609]
Into Helidon SE Config Guide, section Reacting to configuration updates: When starting the application it throws

`Exception in thread "main" java.lang.IllegalArgumentException: Polling strategy of type watch is not supported. Supported types: [regular]
	at io.helidon.config.MetaProviders.lambda$pollingStrategy$16(MetaProviders.java:144)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at io.helidon.config.MetaProviders.pollingStrategy(MetaProviders.java:144)
	at io.helidon.config.MetaConfig.pollingStrategy(MetaConfig.java:117)
	at io.helidon.config.ConfigValues.lambda$create$4(ConfigValues.java:146)
	at io.helidon.config.ConfigValues$GenericConfigValueImpl.asOptional(ConfigValues.java:228)
	at io.helidon.config.ConfigValue.ifPresent(ConfigValue.java:227)
	at io.helidon.config.AbstractSourceBuilder.config(AbstractSourceBuilder.java:89)
	at io.helidon.config.AbstractConfigSourceBuilder.config(AbstractConfigSourceBuilder.java:70)
	at io.helidon.config.FileConfigSource$Builder.config(FileConfigSource.java:205)
	at io.helidon.config.FileConfigSource.create(FileConfigSource.java:80)
	at io.helidon.config.MetaProviders$BuiltInConfigSourcesProvider.create(MetaProviders.java:289)
	at io.helidon.config.MetaProviders$BuiltInConfigSourcesProvider.create(MetaProviders.java:259)
	at io.helidon.config.MetaProviders.lambda$configSource$6(MetaProviders.java:116)
	at java.base/java.util.Optional.map(Optional.java:265)
	at io.helidon.config.MetaProviders.configSource(MetaProviders.java:116)
	at io.helidon.config.MetaConfig.configSource(MetaConfig.java:172)
	at io.helidon.config.BuilderImpl.lambda$config$3(BuilderImpl.java:361)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at io.helidon.config.BuilderImpl.lambda$config$4(BuilderImpl.java:361)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.helidon.config.ConfigValue.ifPresent(ConfigValue.java:227)
	at io.helidon.config.BuilderImpl.config(BuilderImpl.java:361)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.helidon.config.Config$Builder.metaConfig(Config.java:1566)
	at io.helidon.config.Config.create(Config.java:313)
	at io.helidon.examples.quickstart.se.Main.startServer(Main.java:41)
	at io.helidon.examples.quickstart.se.Main.main(Main.java:29)`

REPRODUCER:

```
mvn -U archetype:generate -DinteractiveMode=false \
    -DarchetypeGroupId=io.helidon.archetypes \
    -DarchetypeArtifactId=helidon-quickstart-se \
    -DarchetypeVersion=2.1.1-SNAPSHOT \
    -DgroupId=io.helidon.examples \
    -DartifactId=helidon-quickstart-se \
    -Dpackage=io.helidon.examples.quickstart.se
```

- Create `config-file.properties` with content `app.greeting=HelloFrom-config-file.properties` into /helidon-quickstart-se directory
- Create `meta-config.yaml` into /helidon-quickstart-se directory with this content:
```
sources:
  - type: "file"
    properties:
      path: "./config-file.properties"
      polling-strategy:
        type: "watch"
  - type: "classpath"
    properties:
      resource: "application.yaml"
```
- Update the GreetService class 
```
import java.util.function.Consumer;
...

    GreetService(Config config) {
        Config greetingConfig = config.get("app.greeting"); // (1)
        greeting.set(greetingConfig.asString().orElse("Ciao"));
        greetingConfig.onChange((Consumer<Config>) cfg -> greeting.set(cfg.asString().orElse("Ciao"))); // (2)
    }
```
- Build and run the application
```
mvn package -DskipTests=true
java -jar target/helidon-quickstart-se.jar
```

**Comment by bluetree24** [comment]
I seem that it was array list.
please try it.

```
polling-strategy:
        type: 
          - "watch"
```
or
```
polling-strategy:
        type: [watch]
```

**Comment by tvallin** [comment]
Hi @bluetree24,

I think it is more than just syntax issue. The polling strategy "watch" was removed and it uses now `ChangeWatcher` mechanism. 

Please have a look at this PR: https://github.com/oracle/helidon/pull/1417 where the changes were made.
