### ISSUE TITLE
Too many open files error from Helidon/Netty NIOServerSocket Channel 

### ISSUE THREAD

**Issue by mchakrav** [oracle/helidon#2663]
## Environment Details
* Helidon Version: **1.4.4**
* Helidon SE or Helidon MP: **Helidon MP**
* JDK version: **11.0.7**
* OS**: Oracle Linux - 4.14.35-1902.301.1.el7uek.x86_64**
* Docker version (if applicable): NA

----------

## Problem Description
This is a Helidon MP based REST application which serves API requests. It starts up successfully and after a few days, the server was not responding and while checking the log files, found this error for each unserviced request:

**2021-01-14 14:51:35.093+0000 | ioEventLoopGroup-2-1 |  WARN | .c.DefaultChannelPipeline |  | An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.io.IOException: Too many open files**
	at java.base/sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:533)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:285)
	at io.netty.util.internal.SocketUtils$5.run(SocketUtils.java:111)
	at io.netty.util.internal.SocketUtils$5.run(SocketUtils.java:108)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at io.netty.util.internal.SocketUtils.accept(SocketUtils.java:108)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doReadMessages(NioServerSocketChannel.java:147)
	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:75)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)

At first, I increased the ulimit to 4096 and after restart the problem went away but again resurfaced after a few days. It looks like the NIO Socket Channel is not releasing the socket connection at linux level and it fills up the limit of linux open files. 
I have not written any directly using the NIO Socket Channel but rely on Helidon/Netty to open Socket Channel for every server request.

Any pointers would be appreciated. 

Thanks.

**Comment by spericas** [comment]
@mchakrav Could you provide more information about the business logic in your application? Are you using Helidon's static content support? Have you tried running `lsof` on your Linux system to get more info?

**Comment by mchakrav** [comment]
The Java (Helidon) Application does not have this problem when the request
is routed correctly to the service controller so that business logic
gets applied correctly either with OK response or any other error response.
There is no issue with that flow at all.
2021-01-26 08:29:55.313+0000 | oEventLoopGroup-3-15 | ERROR |
i.h.w.RequestRouting      |  | Unexpected error occurred during routing!
java.lang.IllegalArgumentException: Could not parse ****** (masked)

When helidon is unable to parse the header information and after the above
error the nio socket channel is not released and linux level socket files
does not get released. Here is the list:
(removed the user and group from the ls)
/proc/702/fd
lrwx------. 1  64 Jan 21 08:59 990 -> socket:[27589049]
lrwx------. 1 64 Jan 21 08:59 991 -> socket:[27589072]
lrwx------. 1  64 Jan 21 08:59 992 -> socket:[27598186]
lrwx------. 1  64 Jan 21 08:59 993 -> socket:[27589097]
lrwx------. 1  64 Jan 21 08:59 994 -> socket:[27589118]
lrwx------. 1 64 Jan 21 08:59 995 -> socket:[27598148]
lrwx------. 1  64 Jan 21 08:59 996 -> socket:[27598218]
lrwx------. 1  64 Jan 21 08:59 997 -> socket:[27598019]
lrwx------. 1  64 Jan 21 08:59 998 -> socket:[27598257]
lrwx------. 1 64 Jan 21 08:59 999 -> socket:[27598288]

Eventually runs out of max open files limit at the linux level.

**Comment by spericas** [comment]
@mchakrav Thanks for the additional information. Is it at all possible for you to upgrade to a more recent version than 1.4.4? This issue should be fixed in the 2.X codebase.

**Comment by spericas** [comment]
Inactive for about a month. Please re-open if necessary.
