### ISSUE TITLE
HoconConfigParser does not support null values

### ISSUE THREAD

**Issue by romain-grecourt** [oracle/helidon#2720]
Parsing a JSON config file with a `null` value results in a NPE:

```
Exception in thread "main" io.helidon.config.spi.ConfigParserException: Cannot read from source: null
	at io.helidon.config.hocon.HoconConfigParser.parse(HoconConfigParser.java:139)
	at io.helidon.config.ConfigSourceRuntimeImpl$ParsableConfigSourceReloader.lambda$get$0(ConfigSourceRuntimeImpl.java:477)
	at java.base/java.util.Optional.map(Optional.java:265)
	at io.helidon.config.ConfigSourceRuntimeImpl$ParsableConfigSourceReloader.get(ConfigSourceRuntimeImpl.java:460)
	at io.helidon.config.ConfigSourceRuntimeImpl$ParsableConfigSourceReloader.get(ConfigSourceRuntimeImpl.java:443)
	at java.base/java.util.Optional.orElseGet(Optional.java:369)
	at io.helidon.config.ConfigSourceRuntimeImpl.initialLoad(ConfigSourceRuntimeImpl.java:218)
	at io.helidon.config.ConfigSourceRuntimeImpl.load(ConfigSourceRuntimeImpl.java:173)
	at io.helidon.config.ConfigSourcesRuntime.load(ConfigSourcesRuntime.java:140)
	at io.helidon.config.ProviderImpl.newConfig(ProviderImpl.java:87)
	at io.helidon.config.BuilderImpl.build(BuilderImpl.java:333)
	at io.helidon.config.BuilderImpl.build(BuilderImpl.java:51)
	at io.helidon.config.Config.create(Config.java:339)
	at io.helidon.config.examples.basics.Main.main(Main.java:40)
Caused by: java.lang.NullPointerException
	at io.helidon.config.hocon.HoconConfigParser.lambda$fromConfig$0(HoconConfigParser.java:152)
	at java.base/java.util.Map.forEach(Map.java:661)
	at io.helidon.config.hocon.HoconConfigParser.fromConfig(HoconConfigParser.java:145)
	at io.helidon.config.hocon.HoconConfigParser.lambda$fromList$1(HoconConfigParser.java:164)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at io.helidon.config.hocon.HoconConfigParser.fromList(HoconConfigParser.java:160)
	at io.helidon.config.hocon.HoconConfigParser.lambda$fromConfig$0(HoconConfigParser.java:148)
	at java.base/java.util.Map.forEach(Map.java:661)
	at io.helidon.config.hocon.HoconConfigParser.fromConfig(HoconConfigParser.java:145)
	at io.helidon.config.hocon.HoconConfigParser.lambda$fromConfig$0(HoconConfigParser.java:150)
	at java.base/java.util.Map.forEach(Map.java:661)
	at io.helidon.config.hocon.HoconConfigParser.fromConfig(HoconConfigParser.java:145)
	at io.helidon.config.hocon.HoconConfigParser.lambda$fromConfig$0(HoconConfigParser.java:150)
	at java.base/java.util.Map.forEach(Map.java:661)
	at io.helidon.config.hocon.HoconConfigParser.fromConfig(HoconConfigParser.java:145)
	at io.helidon.config.hocon.HoconConfigParser.parse(HoconConfigParser.java:135)
	... 13 more

```

The culprit is this statement: `value.unwrapped().toString()` ; `value.unwrapped()` returns `null`.

Seems like `YamlConfigParser` handles `null` as a value that holds an empty string:

```java
String strValue = v == null ? "" : v.toString();
builder.addValue(strKey, strValue);
```

We probably want to do the same here to remain consistent (even though it seems odd).

**Comment by tomas-langer** [comment]
The problem of missing/`null`/empty...

We treat it as follows:
- property does not exist -> it does not exist in the configuration
- property has a null value -> value is empty string (as properties files cannot do this, we merge the two states)
- property has an empty string value -> value is empty string
- property has a value -> value is used
