### ISSUE TITLE
Kafka connector with SASL doesn't work in native image

### ISSUE THREAD

**Issue by danielkec** [oracle/helidon#2774]
```
org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
        at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:825)
        at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:631)
        at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:612)
        at io.helidon.messaging.connectors.kafka.KafkaPublisher$Builder.lambda$config$0(KafkaPublisher.java:364)
        at io.helidon.messaging.connectors.kafka.KafkaPublisher.start(KafkaPublisher.java:118)
        at io.helidon.messaging.connectors.kafka.KafkaPublisher.subscribe(KafkaPublisher.java:292)
        at org.reactivestreams.FlowAdapters$FlowPublisherFromReactive.subscribe(FlowAdapters.java:373)
        at io.helidon.common.reactive.MultiFromPublisher.subscribe(MultiFromPublisher.java:39)
        at org.reactivestreams.FlowAdapters$ReactivePublisherFromFlow.subscribe(FlowAdapters.java:355)
        at io.helidon.messaging.Channel.connect(Channel.java:44)
        at java.util.HashMap$Values.forEach(HashMap.java:976)
        at io.helidon.messaging.MessagingImpl.start(MessagingImpl.java:64)
        at me.kec.se.bare.Main.main(Main.java:54)
Caused by: org.apache.kafka.common.KafkaException: org.apache.kafka.common.KafkaException: Could not find a public no-argument constructor for org.apache.kafka.common.security.authenticator.SaslClientCallbackHandler
        at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:172)
        at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:157)
        at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:73)
        at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:105)
        at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:743)
        ... 12 more
Caused by: org.apache.kafka.common.KafkaException: Could not find a public no-argument constructor for org.apache.kafka.common.security.authenticator.SaslClientCallbackHandler
        at org.apache.kafka.common.utils.Utils.newInstance(Utils.java:310)
        at org.apache.kafka.common.network.SaslChannelBuilder.createClientCallbackHandler(SaslChannelBuilder.java:293)
        at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:136)
        ... 16 more
Caused by: java.lang.NoSuchMethodException: org.apache.kafka.common.security.authenticator.SaslClientCallbackHandler.<init>()
        at java.lang.Class.getConstructor0(DynamicHub.java:3349)
        at java.lang.Class.getDeclaredConstructor(DynamicHub.java:2553)
        at org.apache.kafka.common.utils.Utils.newInstance(Utils.java:308)
        ... 18 more

```

**Comment by danielkec** [comment]
Problem cause is in `org.apache.kafka.common.security.authenticator.SaslClientCallbackHandler` where `Subject.getSubject(AccessController.getContext());` doesn't return subject. Root cause seems to be oracle/graal/issues/2745.
