### ISSUE TITLE
Unable to inject MetricRegistry when using Graal native-image

### ISSUE THREAD

**Issue by dansiviter** [oracle/helidon#2892]
## Environment Details
* Helidon Version: 2.2.1
* Helidon SE or Helidon MP: MP
* JDK version: Graal 21.0.0 native-image
* OS: scratch
* Docker version (if applicable): Docker for Desktop Windows 3.2.2

----------

## Problem Description
Unable to inject any of the `org.eclipse.microprofile.metrics.MetricRegistry` instances resulting in:

```
Exception in thread "main" org.jboss.weld.exceptions.IllegalArgumentException: WELD-001456: Argument resolvedBean 
must not be null
        at org.jboss.weld.util.Preconditions.checkArgumentNotNull(Preconditions.java:40)
        at org.jboss.weld.manager.BeanManagerImpl.getInjectableReference(BeanManagerImpl.java:746)
        at org.jboss.weld.injection.FieldInjectionPoint.inject(FieldInjectionPoint.java:92)
        at org.jboss.weld.util.Beans.injectBoundFields(Beans.java:336)
        at org.jboss.weld.util.Beans.injectFieldsAndInitializers(Beans.java:347)
        at org.jboss.weld.injection.producer.ResourceInjector$1.proceed(ResourceInjector.java:69)
        at org.jboss.weld.injection.InjectionContextImpl.run(InjectionContextImpl.java:48)
        at org.jboss.weld.injection.producer.ResourceInjector.inject(ResourceInjector.java:71)
        at org.jboss.weld.injection.producer.BasicInjectionTarget.inject(BasicInjectionTarget.java:117)
        at org.jboss.weld.bean.ManagedBean.create(ManagedBean.java:161)
        at org.jboss.weld.contexts.AbstractContext.get(AbstractContext.java:96)
        at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:100)
        at org.jboss.weld.bean.ContextualInstanceStrategy$ApplicationScopedContextualInstanceStrategy.get(ContextualInstanceStrategy.java:140)
        at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:67)
        at org.jboss.weld.event.ObserverMethodImpl.getReceiver(ObserverMethodImpl.java:360)
        at org.jboss.weld.event.ObserverMethodImpl.getReceiverIfExists(ObserverMethodImpl.java:347)
        at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:305)
        at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:286)
        at javax.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:124)
        at org.jboss.weld.util.Observers.notify(Observers.java:166)
        at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:285)
        at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:273)
        at org.jboss.weld.event.EventImpl.fire(EventImpl.java:96)
        at io.helidon.microprofile.cdi.HelidonContainerImpl.doStart(HelidonContainerImpl.java:339)
        at io.helidon.common.context.Contexts.runInContext(Contexts.java:137)
        at io.helidon.microprofile.cdi.HelidonContainerImpl.start(HelidonContainerImpl.java:249)
        at io.helidon.microprofile.cdi.Main.main(Main.java:80)
```

## Steps to reproduce
1. Use Helidon MP Quickstart,
2. Inject a `MetricRegistry` (any Type) 

## Workaround
Add the following into `reflect-config.json`:
```json
[
  {
    "name":"io.helidon.microprofile.metrics.RegistryProducer",
    "allDeclaredFields":true,
    "allDeclaredMethods":true,
    "allPublicMethods":true,
    "allDeclaredConstructors":true
  },{
    "name":"org.eclipse.microprofile.metrics.MetricRegistry",
    "allDeclaredMethods":true,
    "methods":[{"name":"<init>","parameterTypes":[] }]
  },{
    "name":"org.eclipse.microprofile.metrics.annotation.RegistryType",
    "allDeclaredFields":true,
    "allDeclaredMethods":true,
    "allDeclaredConstructors":true
  }
]
```
Not sure if all of them are needed, but it got it working.

**Comment by dansiviter** [comment]
After a bit of trial and error, it seems just this is needed:

```json
[
  {
		"name":"org.eclipse.microprofile.metrics.annotation.RegistryType",
		"allDeclaredFields":true,
		"allDeclaredMethods":true,
		"allDeclaredConstructors":true
	}
]
```

**Comment by tomas-langer** [comment]
The error message is not very friendly...
Thanks for reporting this, looking into the problem. I will also add this to the Mp1 native image integration test.

**Comment by tomas-langer** [comment]
As the `RegistryType` is an annotation, it is sufficient to enable methods for reflection:
```json
    {
        "name":"org.eclipse.microprofile.metrics.annotation.RegistryType",
        "allDeclaredMethods":true
    }
```
