### ISSUE TITLE
Internal server error when serving favicon.ico

### ISSUE THREAD

**Issue by zimmi** [oracle/helidon#2893]
## Environment Details
* Helidon Version: 2.3.0-SNAPSHOT
* Helidon SE
* JDK version: 16
* OS: debian

----------

## Problem Description

I'm serving static content like this:

```java
var staticContent = StaticContentSupport.builder("META-INF/frontend", ClassLoader.getSystemClassLoader())
        .welcomeFileName("index.html")
        .build();

Routing.builder()
        .register(staticContent)
        .build();
```
When the browser tries to access the favicon by itself (or manually request it via /favicon.ico, doesn't matter), the following exception occurs and a 500 error (with message: "Cannot access static resource!") is returned:

```
2021.03.28 20:33:14 FINE io.helidon.webserver.staticcontent.ClassPathContentHandler: Sending static content from classpath: jar:file:///example-1.0.0-SNAPSHOT.jar!/META-INF/frontend/favicon.ico
2021.03.28 20:33:14 FINE io.helidon.webserver.staticcontent.StaticContentHandler: Failed to access static resource
java.lang.IllegalArgumentException: Could not parse 'vnd.microsoft.icon'
	at io.helidon.common.http@2.3.0-SNAPSHOT/io.helidon.common.http.MediaType.parse(MediaType.java:348)
	at java.base/java.util.Optional.map(Optional.java:260)
	at io.helidon.webserver.staticcontent@2.3.0-SNAPSHOT/io.helidon.webserver.staticcontent.FileBasedContentHandler.lambda$detectType$0(FileBasedContentHandler.java:100)
	at java.base/java.util.Optional.or(Optional.java:313)
	at io.helidon.webserver.staticcontent@2.3.0-SNAPSHOT/io.helidon.webserver.staticcontent.FileBasedContentHandler.detectType(FileBasedContentHandler.java:99)
	at io.helidon.webserver.staticcontent@2.3.0-SNAPSHOT/io.helidon.webserver.staticcontent.FileBasedContentHandler.processContentType(FileBasedContentHandler.java:88)
	at io.helidon.webserver.staticcontent@2.3.0-SNAPSHOT/io.helidon.webserver.staticcontent.ClassPathContentHandler.sendJar(ClassPathContentHandler.java:169)
	at io.helidon.webserver.staticcontent@2.3.0-SNAPSHOT/io.helidon.webserver.staticcontent.ClassPathContentHandler.doHandle(ClassPathContentHandler.java:140)
	at io.helidon.webserver.staticcontent@2.3.0-SNAPSHOT/io.helidon.webserver.staticcontent.StaticContentHandler.handle(StaticContentHandler.java:103)
	at io.helidon.webserver.staticcontent@2.3.0-SNAPSHOT/io.helidon.webserver.staticcontent.StaticContentHandler.lambda$update$1(StaticContentHandler.java:59)
	at io.helidon.webserver@2.3.0-SNAPSHOT/io.helidon.webserver.RequestRouting$RoutedRequest.next(RequestRouting.java:323)
	at io.helidon.metrics@2.3.0-SNAPSHOT/io.helidon.metrics.MetricsSupport$MetricsContextHandler.accept(MetricsSupport.java:619)
	at io.helidon.webserver@2.3.0-SNAPSHOT/io.helidon.webserver.RequestRouting$RoutedRequest.next(RequestRouting.java:323)
	at io.helidon.metrics@2.3.0-SNAPSHOT/io.helidon.metrics.MetricsSupport.lambda$configureVendorMetrics$7(MetricsSupport.java:364)
	at io.helidon.webserver@2.3.0-SNAPSHOT/io.helidon.webserver.RequestRouting$RoutedRequest.next(RequestRouting.java:323)
	at io.helidon.webserver@2.3.0-SNAPSHOT/io.helidon.webserver.WebTracingConfig$RequestSpanHandler.accept(WebTracingConfig.java:247)
	at io.helidon.webserver@2.3.0-SNAPSHOT/io.helidon.webserver.RequestRouting$RoutedRequest.next(RequestRouting.java:323)
	at io.helidon.common.context@2.3.0-SNAPSHOT/io.helidon.common.context.Contexts.runInContext(Contexts.java:117)
	at io.helidon.webserver@2.3.0-SNAPSHOT/io.helidon.webserver.RequestRouting.route(RequestRouting.java:89)
	at io.helidon.webserver@2.3.0-SNAPSHOT/io.helidon.webserver.ForwardingHandler.channelRead0(ForwardingHandler.java:264)
	at io.netty.transport@4.1.59.Final/io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.transport@4.1.59.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.transport@4.1.59.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.transport@4.1.59.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.codec@4.1.59.Final/io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.codec@4.1.59.Final/io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
	at io.netty.transport@4.1.59.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.transport@4.1.59.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.transport@4.1.59.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.codec@4.1.59.Final/io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.codec@4.1.59.Final/io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.transport@4.1.59.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.transport@4.1.59.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.transport@4.1.59.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.transport@4.1.59.Final/io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.transport@4.1.59.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.transport@4.1.59.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.transport@4.1.59.Final/io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.transport@4.1.59.Final/io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.transport@4.1.59.Final/io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.transport@4.1.59.Final/io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:620)
	at io.netty.transport@4.1.59.Final/io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:583)
	at io.netty.transport@4.1.59.Final/io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.common@4.1.59.Final/io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.common@4.1.59.Final/io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.common@4.1.59.Final/io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.IllegalStateException: No more elements!
	at io.helidon.common.http@2.3.0-SNAPSHOT/io.helidon.common.http.Tokenizer.checkState(Tokenizer.java:172)
	at io.helidon.common.http@2.3.0-SNAPSHOT/io.helidon.common.http.Tokenizer.checkState(Tokenizer.java:157)
	at io.helidon.common.http@2.3.0-SNAPSHOT/io.helidon.common.http.Tokenizer.consumeCharacter(Tokenizer.java:107)
	at io.helidon.common.http@2.3.0-SNAPSHOT/io.helidon.common.http.MediaType.parse(MediaType.java:318)
	... 46 more
```

It seems like Helidon is unable to parse [it's default media types](https://github.com/oracle/helidon/blob/3d9a3f944a4971273085c4b5164cab3c7f68f0ed/common/media-type/src/main/resources/io/helidon/common/media/type/default-media-types.properties#L71). The line should read [image/vnd.microsoft.icon](https://www.iana.org/assignments/media-types/image/vnd.microsoft.icon) instead of `vnd.microsoft.icon`.

**Comment by tomas-langer** [comment]
Also verify that we do not parse the file multiple times.
