### ISSUE TITLE
MP ReST Client & Graal Static Native results in ClassCastException

### ISSUE THREAD

**Issue by dansiviter** [oracle/helidon#2913]
## Environment Details
* Helidon Version: 2.2.2
* Helidon SE or Helidon MP: MP
* JDK version: 11
* OS: N/A
* Docker version (if applicable): Docker for Windows

----------

## Problem Description
Creating a Graal static native image using Microprofile ReST Client results in ClassCastException:

```
#11 22.27 [WARNING] WARNING: Feature 'REST Client' for path 'RESTClient' has limited support in native image: Does not support execution of default methods on interfaces.
#11 23.84 [WARNING] Fatal error:java.lang.ClassCastException
#11 23.84 [WARNING]     at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
#11 23.85 [WARNING]     at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
#11 23.85 [WARNING]     at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
#11 23.85 [WARNING]     at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
#11 23.85 [WARNING]     at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:603)
#11 23.85 [WARNING]     at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
#11 23.85 [WARNING]     at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:488)
#11 23.85 [WARNING]     at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:370)
#11 23.85 [WARNING]     at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:529)
#11 23.85 [WARNING]     at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:119)
#11 23.85 [WARNING]     at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:561)
#11 23.85 [WARNING] Caused by: java.lang.ClassCastException: class io.github.classgraph.BaseTypeSignature cannot be cast to class io.github.classgraph.ClassRefTypeSignature (io.github.classgraph.BaseTypeSignature and io.github.classgraph.ClassRefTypeSignature are in unnamed module of loader java.net.URLClassLoader @7823a2f9)
#11 23.86 [WARNING]     at io.helidon.integrations.graal.nativeimage.extension.HelidonReflectionFeature.getSimpleType(HelidonReflectionFeature.java:275)
#11 23.86 [WARNING]     at io.helidon.integrations.graal.nativeimage.extension.HelidonReflectionFeature.getSimpleType(HelidonReflectionFeature.java:259)
#11 23.86 [WARNING]     at io.helidon.integrations.graal.nativeimage.extension.HelidonReflectionFeature.lambda$addJaxRsConversions$16(HelidonReflectionFeature.java:237)
#11 23.86 [WARNING]     at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
#11 23.86 [WARNING]     at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
... truncated ...
#11 23.88 [WARNING]     at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:476)
#11 23.88 [WARNING]     at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
#11 23.88 [WARNING]     at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
#11 23.88 [WARNING]     at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
#11 23.89 [WARNING]     at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
#11 23.89 [WARNING]     at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
#11 23.89 [WARNING]     at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
#11 23.91 [WARNING] Error: Image build request failed with exit status 1
```

## Steps to reproduce
1. Use `helidon-mp-quickstart`
2. Create a basic ReST Client:
```

@RegisterRestClient(baseUri = "https://jsonplaceholder.typicode.com/")
@Consumes(MediaType.APPLICATION_JSON)
public interface JsonPlaceholderService {
	@GET
	@Path("posts/{id}")
	CompletionStage<Optional<Post>> post(@PathParam("id") int id);
}
```
3. Build native image and observe above exception.

**Comment by dansiviter** [comment]
I've figured out it's due to usage of primitives (in my case `int`) as a `@PathParam`.

**Comment by dansiviter** [comment]
Closing as 2.3.0 includes #2917.
