### ISSUE TITLE
Support underscores in named parameters

### ISSUE THREAD

**Issue by zimmi** [oracle/helidon#2922]
## Environment Details
* Helidon Version: 2.3.0-SNAPSHOT
* Helidon SE
* JDK version: 16
* OS: debian

----------

## Problem Description

Right now, named parameters only allow letters. I usually name my parameters like my columns, with underscores. As of now, given this (PostgreSQL) query:
```yaml
db:
  statements:
    insert-example: |
      INSERT INTO example (created_at)
      VALUES (:created_at)
      RETURNING example_id, created_at;
```
and this Java-Code:
```java
Example example = exec.createNamedGet("insert-example")
                    .addParam("created_at", Timestamp.from(createdAt))
                    .execute()
                    .map(row -> row.get().as(Example.class))
                    .await();
```
results in an exception like this:
```
Caused by: io.helidon.dbclient.DbClientException: Query parameters missing in Map: created
	at io.helidon.dbclient.jdbc@2.3.0-SNAPSHOT/io.helidon.dbclient.jdbc.JdbcStatement.prepareNamedStatement(JdbcStatement.java:128)
	at io.helidon.dbclient.jdbc@2.3.0-SNAPSHOT/io.helidon.dbclient.jdbc.JdbcStatement.lambda$build$3(JdbcStatement.java:76)
	at java.base/java.util.Optional.map(Optional.java:260)
	at io.helidon.dbclient.jdbc@2.3.0-SNAPSHOT/io.helidon.dbclient.jdbc.JdbcStatement.build(JdbcStatement.java:76)
	at io.helidon.dbclient.jdbc@2.3.0-SNAPSHOT/io.helidon.dbclient.jdbc.JdbcStatementQuery.lambda$doExecute$2(JdbcStatementQuery.java:95)
	at io.helidon.common.context@2.3.0-SNAPSHOT/io.helidon.common.context.Contexts.runInContext(Contexts.java:117)
	at io.helidon.common.context@2.3.0-SNAPSHOT/io.helidon.common.context.ContextAwareExecutorImpl.lambda$wrap$5(ContextAwareExecutorImpl.java:154)
	... 5 more
```

Note: I also registered mappers to convert between `java.sql.Timestamp` <-> `java.time.Instant`, but those seem to only be used when mapping query results, not parameters, making the manual `Timestamp.from(createdAt)` necessary at every callsite. But that's perhaps another issue.

**Comment by spericas** [comment]
PR #3023
