### ISSUE TITLE
fault tolerance 3.0 with retry and fallback prevents execution

### ISSUE THREAD

**Issue by constantind** [oracle/helidon#2928]
Fault tolerance 3 with @retry and @fallback method from a background thread not executing due to null pointer exception in hk2 request scope is null

## Environment Details
* Helidon Version: 2.2.2
* Helidon MP
* JDK version: 11.0.10
* OS: OL7 latest
* Docker version (if applicable): latest

----------

## Problem Description
null pointer exception for requestScope on RequestScopeHelper.save() from referenceCurrent() here: https://github.com/oracle/helidon/blob/ac64239ad10a385d40d2e7d4624b25767dedcc79/mi[…]/io/helidon/microprofile/faulttolerance/RequestScopeHelper.java and throws here: https://github.com/oracle/helidon/blob/ac64239ad10a385d40d2e7d4624b25767dedcc79/microprofile/fault-tolerance/src/main/java/io/helidon/microprofile/faulttolerance/MethodInvoker.java#L608

The same works with Helidon MP 2.2.1

the problem is easily reproducible every time:

`java.lang.NullPointerException
	at org.glassfish.jersey.process.internal.RequestScope.release(RequestScope.java:246)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:316)
	at io.helidon.microprofile.faulttolerance.RequestScopeHelper.lambda$wrapInScope$1(RequestScopeHelper.java:96)
	at io.helidon.microprofile.faulttolerance.MethodInvoker.lambda$toCompletionStageSupplier$15(MethodInvoker.java:608)
	at io.helidon.faulttolerance.DelayedTask$2.execute(DelayedTask.java:114)
	at io.helidon.faulttolerance.RetryImpl.retrySingle(RetryImpl.java:92)
	at io.helidon.faulttolerance.RetryImpl.invoke(RetryImpl.java:63)
	at io.helidon.faulttolerance.FaultTolerance$TypedBuilder$TypedWrapper.invoke(FaultTolerance.java:302)
	at io.helidon.faulttolerance.FaultTolerance$TypedBuilder$FtHandlerTypedImpl.lambda$invoke$1(FaultTolerance.java:276)
	at io.helidon.faulttolerance.FallbackImpl.invoke(FallbackImpl.java:60)
	at io.helidon.faulttolerance.FaultTolerance$TypedBuilder$FtHandlerTypedImpl.lambda$invoke$1(FaultTolerance.java:276)
	at io.helidon.faulttolerance.FaultTolerance$TypedBuilder$FtHandlerTypedImpl.invoke(FaultTolerance.java:279)
	at io.helidon.microprofile.faulttolerance.MethodInvoker.lambda$get$6(MethodInvoker.java:367)
	at io.helidon.common.context.Contexts.runInContextWithThrow(Contexts.java:161)
	at io.helidon.microprofile.faulttolerance.MethodInvoker.lambda$get$7(MethodInvoker.java:366)
	at io.helidon.microprofile.faulttolerance.MethodInvoker.get(MethodInvoker.java:422)
	at io.helidon.microprofile.faulttolerance.CommandInterceptor.interceptCommand(CommandInterceptor.java:54)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.weld.interceptor.reader.SimpleInterceptorInvocation$SimpleMethodInvocation.invoke(SimpleInterceptorInvocation.java:73)
	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeAroundInvoke(InterceptorMethodHandler.java:84)
	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeInterception(InterceptorMethodHandler.java:72)
	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.invoke(InterceptorMethodHandler.java:56)
	at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:79)
	at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:68)
`

## Steps to reproduce
User the following class to start a thread then CDI is ready:

```

@ApplicationScoped
public class StartupServices  {
    private static Logger log = LogManager.getLogger(StartupServices.class.getName());
    private static ScheduledExecutorService execServiceApis;
    private static StartupServices self;

    public StartupServices() {
    }

    protected Logger getLogger() {
        return log;
    }

    private static void onStartup(@Observes @Priority(Interceptor.Priority.PLATFORM_AFTER+101) @Initialized(ApplicationScoped.class) final Object event, StartupServices self) {
    	log.info("INITIALIZING threads");
    	StartupServices.self = self; 
    	startThread_Apis();
	}

    private static void rightBeforeShutdown(@Observes @BeforeDestroyed(ApplicationScoped.class) final Object event) {
    	log.info("DESTROYING threads");
        shutdownThread_Apis();
	}
 
    private static void startThread_Apis() {
    	log.info("Starting Apis thread");
    	execServiceApis = Executors.newSingleThreadScheduledExecutor();
    	//setting this to 12 hours
    	execServiceApis.scheduleAtFixedRate(apisThread(), 43200, 43200, TimeUnit.SECONDS);
    	execServiceApis.execute(new Runnable() {
            @Override
            public void run() {
                try {
                    log.info("Running Apis thread");
                    self.loadApis();
                    //on first run during startup wait for APIs to load and mark the pod ready
                    if(Main.isK8SEnvironment()) {
                        Files.createFile(Paths.get(Main.readinessFile));
                    }
                } catch (Exception e) {
                    log.warn("Failed all attempts to get data. It will try again in 12 hours, due to: " + e.getMessage());
                }
            }
    	});
    }
	
    private static void shutdownThread_Apis() {
    	log.info("Shutting down Apis thread");
    	execServiceApis.shutdown();
    }
	
    private static Runnable apisThread() {
        return new Runnable() {
            @Override
            public void run() {
                try {
                    log.info("Running Apis thread");
                    self.loadApis();
                } catch (Exception e) {
                    log.warn("Failed all attempts to get data. It will try again in 12 hours, due to: " + e.getMessage());
                }
            }
        };
    }
	
    @Retry(delay = 2, delayUnit = ChronoUnit.SECONDS, maxDuration = 60, durationUnit = ChronoUnit.SECONDS, maxRetries = 10, abortOn = abortOn = javax.ws.rs.ClientErrorException.class)
    @Fallback(fallbackMethod = "loadApisFromDisk")
    protected void loadApis() throws Exception {
        //// -> does not enter here
        log.info("Loading APIs ...");
        //// in another application scoped bean make a request using:
		RestClientBuilder.newBuilder()
			.baseUri(URI.create(nonavailableurl)) //such that it throws javax.ws.rs.ProcessingException
			.register(ClientExceptionMapper.class)
			.build(Client.class);
    }

    protected void loadApisFromDisk() throws Exception {
          ////  -> does not enter here either
    }
}

```

**Comment by spericas** [comment]
PR #2933
