### ISSUE TITLE
@Context injection with multiple JAX-RS applications

### ISSUE THREAD

**Issue by martin-sladecek** [oracle/helidon#2932]
## Environment Details
* Helidon Version: 2.2.2
* Helidon MP
* JDK version: 11
* OS: Linux
* Docker version (if applicable):

----------

## Problem Description
@Context injection does not work correctly with multiple JAX-RS Applications. Any shared @ApplicationScoped bean will have the @Context injections injected from the ServiceLocator of the first JAX-RS Application that access it. When using the bean from another application, it will fail with something like:
```
java.lang.IllegalStateException: Not inside a request scope.
	at org.glassfish.jersey.internal.guava.Preconditions.checkState(Preconditions.java:169) ~[jersey-common-2.31.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.current(RequestScope.java:153) ~[jersey-common-2.31.jar:?]
	at org.glassfish.jersey.inject.hk2.RequestContext.findOrCreate(RequestContext.java:55) ~[jersey-hk2-2.31.jar:?]
	at org.jvnet.hk2.internal.MethodInterceptorImpl.internalInvoke(MethodInterceptorImpl.java:65) ~[hk2-locator-2.6.1.jar:?]
	at org.jvnet.hk2.internal.MethodInterceptorImpl.invoke(MethodInterceptorImpl.java:101) ~[hk2-locator-2.6.1.jar:?]
	at org.jvnet.hk2.internal.MethodInterceptorInvocationHandler.invoke(MethodInterceptorInvocationHandler.java:39) ~[hk2-locator-2.6.1.jar:?]
```

## Steps to reproduce
1. Create two JAX-RS applications
2. Create an @ApplicationScoped resource class that injects @Context HttpHeaders into a field.
3. Try to access the headers from one application and then from the other one.

**Comment by spericas** [comment]
I have an example that shows the problem with 2 apps, a bean in `@ApplicationScope` and access from different resources. Here is the exception reported:

```2021.04.21 14:47:29 WARNING io.helidon.microprofile.server.JaxRsCdiExtension Thread[helidon-2,5,server]: Internal server error
java.lang.IllegalStateException: Not inside a request scope.
	at org.glassfish.jersey.internal.guava.Preconditions.checkState(Preconditions.java:169)
	at org.glassfish.jersey.process.internal.RequestScope.current(RequestScope.java:153)
	at org.glassfish.jersey.inject.hk2.RequestContext.findOrCreate(RequestContext.java:55)
	at org.jvnet.hk2.internal.MethodInterceptorImpl.internalInvoke(MethodInterceptorImpl.java:65)
	at org.jvnet.hk2.internal.MethodInterceptorImpl.invoke(MethodInterceptorImpl.java:101)
	at org.jvnet.hk2.internal.MethodInterceptorInvocationHandler.invoke(MethodInterceptorInvocationHandler.java:39)
	at com.sun.proxy.$Proxy89.toString(Unknown Source)
	at java.base/java.lang.StringConcatHelper.stringOf(StringConcatHelper.java:439)
	at java.base/java.lang.StringConcatHelper.simpleConcat(StringConcatHelper.java:418)
	at me.spericas.mp.quickstart.GreetResource2.getDefaultMessage(GreetResource2.java:61)

**Comment by spericas** [comment]
The crux of the problem is that Jersey creates an injection manager per JAX-RS application, and each injection manager has its own set of scopes (application, request, etc.). Trying to cross inject a CDI bean with request scope objects from different applications results in the exception.

The following test would show the problem: two applications each one holding a single resource and a separate CDI bean in application scope that injects a request scope object such as `HttpHeaders`, an is also injected and accessed from each resource instance. A request that comes for application 1/resource 1 will successfully inject `HttpHeaders` into the application scope bean; a following request that comes for application 2/resource 2 will fail attempting to do the same.

The workaround at this time is to merge the applications that require this form of cross injection to avoid exceptions like the one described in this issue.

**Comment by spericas** [comment]
PR #2988
