### ISSUE TITLE
Unable to handle malformed URLs

### ISSUE THREAD

**Issue by vanyle** [oracle/helidon#2941]
## Environment Details
* Helidon Version: 1.1.1
* Helidon SE
* JDK version: 12.0.1
* OS: Windows 10
* Docker: not used, not relevant

----------

## Problem Description
When parsing URLs, there is no way to handle exception for malformed URLs.
When accessing a malformed URL (Malformed escape pair), the server always returns an empty response.
One might want to respond with a better error message than this. (at least a 500 error instead of an empty response)

## Steps to reproduce
1. Run the helidon-quickstart-se
2. Go at the following URL: http://localhost:8080/%0z

## Stack trace

2021.04.15 21:41:28 SEVERE io.helidon.webserver.RequestRouting Thread[nioEventLoopGroup-3-10,10,main]: Unexpected error occurred during routing!
java.lang.IllegalArgumentException: Malformed escape pair at index 1: /%0z
	at java.base/java.net.URI.create(URI.java:906)
	at io.helidon.webserver.BareRequestImpl.uri(BareRequestImpl.java:79)
	at io.helidon.webserver.RequestRouting.createRequestSpan(RequestRouting.java:134)
	at io.helidon.webserver.RequestRouting.route(RequestRouting.java:70)
	at io.helidon.webserver.ForwardingHandler.channelRead0(ForwardingHandler.java:127)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: java.net.URISyntaxException: Malformed escape pair at index 1: /%0z
	at java.base/java.net.URI$Parser.fail(URI.java:2936)
	at java.base/java.net.URI$Parser.scanEscape(URI.java:3064)
	at java.base/java.net.URI$Parser.scan(URI.java:3087)
	at java.base/java.net.URI$Parser.checkChars(URI.java:3105)
	at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3189)
	at java.base/java.net.URI$Parser.parse(URI.java:3148)
	at java.base/java.net.URI.<init>(URI.java:623)
	at java.base/java.net.URI.create(URI.java:904)
	... 25 more

**Comment by romain-grecourt** [comment]
See also #2941

**Comment by barchetta** [comment]
This bug is filed against 1.1.1. I just tried 1.4.8 and 2.2.2 and the behavior is improved. In those cases the server returns a 400 with the body `Malformed escape pair at index 1: /%0z`

Issue #1893 is a request to support a configurable response. So that enhancement is already being track.

Therefore I'm closing this issue.
