### ISSUE TITLE
JPA integration: huge first query initialization time

### ISSUE THREAD

**Issue by antonio-petricca** [oracle/helidon#2999]
Hello everybody!

I integrated Hibernate inside my Helidon application, and I observed that the first time I execute a query or a find on the entity manager it must be initialized taking a lot of time to return the result set (I discovered that by increasing the log verbosity). The subsequent queries are fast.

In constrast with the above scenario, Weblogic initializes Hibernate and JPA at deploy time, and the first query takes the minimum execution time, like for the subsequent queries.

How could I pre-initialize the JPA entity manager at boot time?

Thank you so much!

**Comment by antonio-petricca** [comment]
Thank you Laird for your suggestion!

Could you explain how to arrange a CDI observer method to achieve that goal?

Il Ven 7 Mag 2021, 19:05 Laird Nelson ***@***.***> ha scritto:

**Comment by antonio-petricca** [comment]
Thank you so much!

I will try it on next Monday and I'll give you a feedback!

Il Ven 7 Mag 2021, 23:33 Laird Nelson ***@***.***> ha scritto:

**Comment by antonio-petricca** [comment]
Hi @ljnelson, unfortunately it does not work,

I wrote the following class:

```java
@Slf4j
public class HibernateInitializer {

    //@Inject
    //private EntityManager em;

    private static void onStartup(
        @Observes
        @Initialized(ApplicationScoped.class)
        Object event
    ) {
        log.warn("Hibernate initializer fired.");
        //em.clear(); // arbitrary method that hopefully will cause Hibernate to initialize

        EntityManagerFactory entityManagerFactory = Persistence.createEntityManagerFactory("defaultPU");
        EntityManager        entityManager        = entityManagerFactory.createEntityManager();

        entityManager.clear();
    }

}
```

I commented your injected entity manager because it cannot be referenced inside a static method. I transformed it in a direct entity manager creation.

Regardless of this, not even my code works, infact I get this exception:

```shell
[2021-05-10 10:27:07,445] [INFO ] [i.h.m.cdi.HelidonContainerImpl$HelidonCdi.close:391] WELD-ENV-002001: Weld SE container 017799af-6eb3-4c36-bd23-e761dd35db15 shut down
Exception in thread "main" org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:275)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:237)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:214)
	at org.hibernate.id.factory.internal.DefaultIdentifierGeneratorFactory.injectServices(DefaultIdentifierGeneratorFactory.java:152)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.injectDependencies(AbstractServiceRegistryImpl.java:286)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:243)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:214)
	at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.<init>(InFlightMetadataCollectorImpl.java:176)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:127)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:1224)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1255)
	at org.hibernate.jpa.HibernatePersistenceProvider.createEntityManagerFactory(HibernatePersistenceProvider.java:56)
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:80)
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
	at it.sisal.betting.api.demo.common.persistence.HibernateInitializer.onStartup(HibernateInitializer.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:85)
	at org.jboss.weld.injection.MethodInvocationStrategy$SimpleMethodInvocationStrategy.invoke(MethodInvocationStrategy.java:168)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:330)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:296)
	at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:286)
	at javax.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:124)
	at org.jboss.weld.util.Observers.notify(Observers.java:166)
	at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:285)
	at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:273)
	at org.jboss.weld.event.EventImpl.fire(EventImpl.java:96)
	at io.helidon.microprofile.cdi.HelidonContainerImpl.doStart(HelidonContainerImpl.java:339)
	at io.helidon.common.context.Contexts.runInContext(Contexts.java:137)
	at io.helidon.microprofile.cdi.HelidonContainerImpl.start(HelidonContainerImpl.java:249)
	at io.helidon.microprofile.server.ServerImpl.start(ServerImpl.java:85)
	at it.sisal.betting.api.demo.logic.application.Main.main(Main.java:17)
Caused by: org.hibernate.engine.jndi.JndiException: Error parsing JNDI name [defaultDS]
	at org.hibernate.engine.jndi.internal.JndiServiceImpl.parseName(JndiServiceImpl.java:124)
	at org.hibernate.engine.jndi.internal.JndiServiceImpl.locate(JndiServiceImpl.java:95)
	at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.configure(DatasourceConnectionProviderImpl.java:98)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:107)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:246)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:214)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.buildJdbcConnectionAccess(JdbcEnvironmentInitiator.java:145)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:66)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:35)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:101)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:263)
	... 34 more
Caused by: javax.naming.NoInitialContextException: Need to specify class name in environment or system property, or in an application resource file: java.naming.factory.initial
	at java.naming/javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:702)
	at java.naming/javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:305)
	at java.naming/javax.naming.InitialContext.getURLOrDefaultInitCtx(InitialContext.java:342)
	at java.naming/javax.naming.InitialContext.getNameParser(InitialContext.java:497)
	at org.hibernate.engine.jndi.internal.JndiServiceImpl.parseName(JndiServiceImpl.java:118)
	... 44 more
```

The exception refers to the datasource **defaultDS** which is defined inside `application.yaml` as follow:

```yaml
javax:
  sql:
    DataSource:
      defaultDS:
        # com.zaxxer.hikari.HikariConfig

        # https://www.baeldung.com/hikaricp
        # https://stackoverflow.com/a/46117164/418599

        driverClassName: ${jpa.driver}
        jdbcUrl: ${jpa.url}

        #FIXME maximumPoolSize: ${jpa.pool.max}
        #FIXME minimumIdle: ${jpa.pool.min}

        dataSource:
          user: ${jpa.user}
          password: ${jpa.password}
```

The datasource is managed by the library **Hikari Connection Pool**, so I suspect I should manually initialize it before trying to get an entity manager instance.

Do you agree with me?

**Comment by ljnelson** [comment]
There are many, many issues going on here.  Most of them have to do with JPA basics.

First, JPA can be used in "application managed mode" or "container managed mode" (this is part of the JPA specification).  If you call `Persistence#createEntityManagerFactory()`, then you are using JPA in "application managed mode" and you are deliberately bypassing all integration with Helidon.  You can of course do this, but then you are responsible for starting transactions, stopping them, maintaining thread safety, acquiring drivers and handling errors.  I am going to guess that you didn't know this and that this is not what you want.  This is part of why Hibernate isn't coming up properly in your code excerpt above.

To use JPA in "container managed mode" in Helidon, you follow [our guide for such things](https://helidon.io/docs/v2/#/mp/guides/09_jpa) and you use the JPA annotations.

Second, I apologize for the `static` method; it was a typo since I was typing untested code (as noted).  Here is more untested code, using container-mode JPA.  My intent is not to provide battle-tested production code here, but rather to sketch what you can try:
```
@PersistenceContext
private EntityManager em;

private void onStartup(@Observes @Initialized(ApplicationScoped.class) Object event) {
  em.clear(); // or something else harmless
}
```

Good luck.
