### ISSUE TITLE
NullPointerException on Helidon MP 2.3.0

### ISSUE THREAD

**Issue by antonio-petricca** [oracle/helidon#3019]
## Environment Details

* Helidon Version: 2.3.0
* Helidon MP
* JDK version: 11
* OS: Linux Mint 19.3 (Ubuntu 18.04)

----------

## Problem Description

I just upgraded my working project to Helidon MP 2.3.0 and I get the below exception on any REST invoke.

Thank you!

Here the exception message:

```shell
[2021-05-14 09:41:04,295] [DEBUG] [io.netty.util.Recycler.<clinit>:104] -Dio.netty.recycler.delayedQueue.ratio: 8
Exception in thread "helidon-1" java.lang.NullPointerException
	at java.base/java.util.HashMap.putMapEntries(HashMap.java:496)
	at java.base/java.util.HashMap.putAll(HashMap.java:780)
	at java.base/java.util.Collections$SynchronizedMap.putAll(Collections.java:2604)
	at ch.qos.logback.classic.util.LogbackMDCAdapter.setContextMap(LogbackMDCAdapter.java:197)
	at org.slf4j.MDC.setContextMap(MDC.java:264)
	at io.helidon.logging.slf4j.Slf4jMdcPropagator.propagateData(Slf4jMdcPropagator.java:37)
	at io.helidon.logging.slf4j.Slf4jMdcPropagator.propagateData(Slf4jMdcPropagator.java:28)
	at io.helidon.common.context.ContextAwareExecutorImpl.lambda$wrap$4(ContextAwareExecutorImpl.java:153)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at io.helidon.common.context.ContextAwareExecutorImpl.lambda$wrap$5(ContextAwareExecutorImpl.java:153)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

## Steps to reproduce

Here are the dependencies of my standalone project:

```xml
<!-- Helidon dependencies -->

<!-- - helidon-dependencies-x.y.z -->

<helidon.version>2.2.0</helidon.version>

<helidon-lib.version.hibernate>5.4.29.Final</helidon-lib.version.hibernate>
<helidon-lib.version.ojdbc8>19.8.0.0</helidon-lib.version.ojdbc8>

<!-- helidon-project-x.y.z -->

<helidon-plugin.version.exec>1.6.0</helidon-plugin.version.exec>
<helidon-plugin.version.failsafe>3.0.0-M5</helidon-plugin.version.failsafe>
<helidon-plugin.version.build-tools>2.2.1</helidon-plugin.version.build-tools>
<helidon-plugin.version.helidon-cli>2.1.2</helidon-plugin.version.helidon-cli>
<helidon-plugin.version.jandex>1.0.6</helidon-plugin.version.jandex>
<helidon-plugin.version.surefire>3.0.0-M5</helidon-plugin.version.surefire>
```

**Comment by antonio-petricca** [comment]
Problem solved, it was a typo in  `<helidon.version>2.2.0</helidon.version>` which must be `<helidon.version>2.3.0</helidon.version>`.

Sorry!
