### ISSUE TITLE
1.4.8: libthrift version incompatible with jaeger-client

### ISSUE THREAD

**Issue by barchetta** [oracle/helidon#3052]
## Environment Details
* Helidon Version: 1.4.8
* Helidon MP
* JDK version: 11.0.9

----------

## Problem Description
If you try to use jaeger tracing with Helidon 1.4.8 you get the following exception:
```
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.thrift.transport.AutoExpandingBufferWriteTransport.<init>(ID)V
	at io.jaegertracing.thrift.internal.senders.ThriftSenderBase.<init>(ThriftSenderBase.java:67)
	at io.jaegertracing.thrift.internal.senders.ThriftSender.<init>(ThriftSender.java:41)
	at io.jaegertracing.thrift.internal.senders.HttpSender.<init>(HttpSender.java:43)
	at io.jaegertracing.thrift.internal.senders.HttpSender$Builder.build(HttpSender.java:126)
	at io.jaegertracing.thrift.internal.senders.ThriftSenderFactory.getSender(ThriftSenderFactory.java:30)
	at io.jaegertracing.internal.senders.SenderResolver.getSenderFromFactory(SenderResolver.java:97)
	at io.jaegertracing.internal.senders.SenderResolver.resolve(SenderResolver.java:81)
	at io.jaegertracing.Configuration$SenderConfiguration.getSender(Configuration.java:693)
	at io.jaegertracing.Configuration$ReporterConfiguration.getReporter(Configuration.java:583)
	at io.jaegertracing.Configuration$ReporterConfiguration.access$000(Configuration.java:543)
	at io.jaegertracing.Configuration.getTracerBuilder(Configuration.java:224)
	at io.jaegertracing.Configuration.getTracer(Configuration.java:247)
	at io.helidon.tracing.jaeger.JaegerTracerBuilder.build(JaegerTracerBuilder.java:460)
	at io.helidon.microprofile.tracing.MpTracingService.configure(MpTracingService.java:40)
	at io.helidon.microprofile.server.ServerImpl.lambda$loadExtensions$10(ServerImpl.java:377)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at io.helidon.microprofile.server.ServerImpl.loadExtensions(ServerImpl.java:376)
	at io.helidon.microprofile.server.ServerImpl.<init>(ServerImpl.java:148)
	at io.helidon.microprofile.server.Server$Builder.doBuild(Server.java:273)
	at io.helidon.common.context.Contexts.runInContext(Contexts.java:118)
	at io.helidon.microprofile.server.Server$Builder.build(Server.java:211)
	at io.helidon.microprofile.server.Server.create(Server.java:95)
	at io.helidon.examples.quickstart.mp.Main.startServer(Main.java:59)
	at io.helidon.examples.quickstart.mp.Main.main(Main.java:46)
```
## Steps to reproduce
1. Using the 1.4.8 Helidon MP quickstart create a project.
2. Add the following to `pom.xml`:
```
        <dependency>
            <groupId>io.helidon.microprofile.tracing</groupId>
            <artifactId>helidon-microprofile-tracing</artifactId>
        </dependency>
        <dependency>
            <groupId>io.helidon.tracing</groupId>
            <artifactId>helidon-tracing-jaeger</artifactId>
        </dependency>
```
3. Add the following to `microprofile-config.properties`:
```
tracing.service=helidon-full-http
```
4. Build and run the project and you will get the above exception.

**Comment by barchetta** [comment]
## Workaround

Add the following to `pom.xml` to force downgrade of libthrfit:
```
        <dependency>
            <groupId>org.apache.thrift</groupId>
            <artifactId>libthrift</artifactId>
            <version>0.12.0</version>
        </dependency>
```

**Comment by barchetta** [comment]
The root cause of the problem is that in 1.4.8 we force an upgrade of libthrift to 0.13.0 which had a breaking constructor signature change. In fact the signature changed again in libthrift 0.14.0:
```
public AutoExpandingBufferWriteTransport(int initialCapacity, double growthCoefficient) { // libthrift 0.12.0
public AutoExpandingBufferWriteTransport(int initialCapacity, int frontReserve) { //libthrift 0.13.0
public AutoExpandingBufferWriteTransport(TConfiguration config, int initialCapacity, int frontReserve) throws TTransportException { //libthrift 0.14.0
```
And `jaeger-client` uses this constructor, so the versions must be aligned. In 2.x we have some tests that catch this, but we don't in 1.x. So to fix this:

1. Either remove libthrift upgrade from `dependencies/pom.xml` and/or upgrade `jaeger-client`
2. Add a test or example that would catch this (for example test `mp-gh-2461` catches this in 2.x)

**Comment by barchetta** [comment]
Fixed and test added.
