### ISSUE TITLE
Intermittent MultiFlatMapPublisherTest#multi

### ISSUE THREAD

**Issue by danielkec** [oracle/helidon#3066]
```java
org.opentest4j.AssertionFailedError: expected: <1000> but was: <996>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
	at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:510)
	at io.helidon.common.reactive.MultiFlatMapPublisherTest.multi(MultiFlatMapPublisherTest.java:322)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

```

Confirmed dropped items, failure happens around 1:250 runs
```java
    @RepeatedTest(1000)
    public void multi() throws ExecutionException, InterruptedException {
        assertEquals(4, Multi.just(1, 2)
                .flatMap(MultiFlatMapPublisherTest::asyncFlowPublisher, 1, false, 1)
                .peek(System.out::println)
                .collectList()
                .await()
                .size());
    }

    private static Flow.Publisher<? extends String> asyncFlowPublisher(Integer i) {
        SubmissionPublisher<String> pub = new SubmissionPublisher<>();
        new Thread(() -> {
            for (int o = 0; o < 2; o++) {
                pub.submit(i + "#" + o);
            }
            pub.close();
        }).start();
        return pub;
    }
```

```bash
# Expected
1#0
1#1
2#0
2#1

# Actual 1
2#0
2#1

# Actual 2
1#0
1#1
2#1

```

**Comment by danielkec** [comment]
Issue seems to in the test as SubmissionPublisher.close doesn't wait for internal buffer to be drained. This is expectable behavior and can be replicated with:

```java
    @RepeatedTest(1000)
    public void test() throws ExecutionException, InterruptedException, TimeoutException {
        AtomicInteger nextCnt = new AtomicInteger();
        AtomicInteger act = new AtomicInteger();
        CompletableFuture<Void> completed = new CompletableFuture<>();
        SubmissionPublisher<Integer> pub = new SubmissionPublisher<>();
        CompletableFuture.runAsync(() -> {
            for (var i = 0; i < 100; i++){
                pub.submit(i);
            }
            pub.close();
        });
        pub.subscribe(new Flow.Subscriber<>() {
            @Override
            public void onSubscribe(Flow.Subscription subscription) {
                subscription.request(Long.MAX_VALUE);
            }

            @Override
            public void onNext(Integer item) {
                nextCnt.incrementAndGet();
            }

            @Override
            public void onError(Throwable throwable) {

            }

            @Override
            public void onComplete() {
                act.set(nextCnt.get());
                completed.complete(null);
            }
        });

        completed.get(800, TimeUnit.MILLISECONDS);
        assertEquals(100, act.get());
    }
```

**Comment by akarnokd** [comment]
> SubmissionPublisher.close doesn't wait for internal buffer to be drained

Would explain the rare cases where SP randomly didn't work as I expected.
