### ISSUE TITLE
Intermittent rest client tck test 

### ISSUE THREAD

**Issue by danielkec** [oracle/helidon#3073]
default / build / org.eclipse.microprofile.rest.client.tck.sse.ReactiveStreamsPublisherTckTest.required_spec313_cancelMustMakeThePublisherEventuallyDropAllReferencesToTheSubscriber (from TestSuite)

## Error Message
Publisher GenericType{class org.glassfish.jersey.media.sse.InboundEvent} did not drop reference to test subscriber after subscription cancellation
### Stacktrace
```java
java.lang.AssertionError: Publisher GenericType{class org.glassfish.jersey.media.sse.InboundEvent} did not drop reference to test subscriber after subscription cancellation
	at org.testng.Assert.fail(Assert.java:96)
	at org.reactivestreams.tck.TestEnvironment.flop(TestEnvironment.java:229)
	at org.reactivestreams.tck.PublisherVerification$27.run(PublisherVerification.java:1025)
	at org.reactivestreams.tck.PublisherVerification.activePublisherTest(PublisherVerification.java:1142)
	at org.reactivestreams.tck.PublisherVerification.required_spec313_cancelMustMakeThePublisherEventuallyDropAllReferencesToTheSubscriber(PublisherVerification.java:1014)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.runSuites(TestNG.java:1028)
	at org.testng.TestNG.run(TestNG.java:996)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:284)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:119)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
```
### Standard Output
```java
Configuring TestNG with: TestNG60Configurator
Standard Error
Jun 03, 2021 2:59:00 PM org.eclipse.jetty.server.Server doStart
INFO: jetty-9.2.28.v20190418
Jun 03, 2021 2:59:00 PM org.eclipse.jetty.server.AbstractConnector doStart
INFO: Started ServerConnector@2c81495c{HTTP/1.1}{0.0.0.0:10000}
Jun 03, 2021 2:59:00 PM org.eclipse.jetty.server.Server doStart
INFO: Started @115872ms
Jun 03, 2021 2:59:00 PM org.eclipse.jetty.server.AbstractConnector doStop
INFO: Stopped ServerConnector@2c81495c{HTTP/1.1}{0.0.0.0:10000}
```

**Comment by tomas-langer** [comment]
This did not happen for a long time, closing.
