### ISSUE TITLE
helidon-tests-integration-mp-grpc fails with JDK 17

### ISSUE THREAD

**Issue by barchetta** [oracle/helidon#3099]
## Environment Details
* Helidon Version: 2.3.1-SNAPSHOT
* MP
* JDK version: java 17-ea 2021-09-14 LTS
* OS: Oracle Linux Server release 7.7

----------

## Problem Description
The test `tests/integration/mp-grpc` fails when built with JDK 17.

## Steps to reproduce
1. Set `JAVA_HOME` to JDK 11 and do priming build of helidon repo: `mvn clean install -DskipTests`
2. Set `JAVA_HOME` to JDK 17 and build test:
```
cd tests/integration/mp-grpc
mvn clean install
```

Lots of exceptions from the test. Here are some hilights:
```
[ERROR] io.helidon.microprofile.grpc.server.InterceptorsTest.shouldUseSpecificMethodInterceptorBean  Time elapsed: 0.25 s  <<< ERROR!
java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: 
module java.base does not "opens java.lang" to unnamed module @164a08fd
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	at org.jboss.weld.util.bytecode.ClassFileUtils$1.run(ClassFileUtils.java:67)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.jboss.weld.util.bytecode.ClassFileUtils.makeClassLoaderMethodsAccessible(ClassFileUtils.java:60)
	at org.jboss.weld.bootstrap.WeldStartup.startContainer(WeldStartup.java:220)
. . .
[ERROR] io.helidon.microprofile.grpc.server.InterceptorsTest.shouldDiscoverServiceInterceptor  Time elapsed: 0.385 s  <<< ERROR!
org.jboss.weld.exceptions.WeldException: WELD-001524: Unable to load proxy class for bean Implicit Bean 
[javax.enterprise.inject.Instance] with qualifiers [@Default] with class interface javax.enterprise.inject.Instance
	at org.jboss.weld.bean.proxy.ProxyFactory.getProxyClass(ProxyFactory.java:507)
. . .
Caused by: java.lang.RuntimeException: java.lang.IllegalAccessException: class org.jboss.weld.util.bytecode.ClassFileUtils
 cannot access a member of class java.lang.ClassLoader (in module java.base) with modifiers "protected final"
	at org.jboss.weld.util.bytecode.ClassFileUtils.toClass(ClassFileUtils.java:118)
	at org.jboss.weld.bean.proxy.ProxyFactory.createProxyClass(ProxyFactory.java:610)
	at org.jboss.weld.bean.proxy.ProxyFactory.getProxyClass(ProxyFactory.java:496)
	... 62 more
Caused by: java.lang.IllegalAccessException: class org.jboss.weld.util.bytecode.ClassFileUtils 
cannot access a member of class java.lang.ClassLoader (in module java.base) with modifiers "protected final"
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:392)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:674)
	at java.base/java.lang.reflect.Method.invoke(Method.java:560)
	at org.jboss.weld.util.bytecode.ClassFileUtils.toClass2(ClassFileUtils.java:143)
	at org.jboss.weld.util.bytecode.ClassFileUtils.toClass(ClassFileUtils.java:112)
	... 64 more
```

**Comment by tomas-langer** [comment]
This can be fixed by updating the plugin configuration to
```xml
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <argLine>
                        -Dgrpc.marshaller.java.enabled=true
                        --add-opens=java.base/java.lang=ALL-UNNAMED
                    </argLine>
                </configuration>
            </plugin>
```
