### ISSUE TITLE
Test mp-1 intermittently throws exception on shutdown

### ISSUE THREAD

**Issue by barchetta** [oracle/helidon#3235]
## Environment Details
* Helidon Version: 2.4.0-SNAPSHOT

----------

## Problem Description

While working on PR #3233 I built and ran `tests/integration/native-image/mp-1` multiple times including building and running the native image. Intermittently when running the native image it would report the following error when the VM was shutting down. This would happen maybe  1 out of 5 runs:

```
2021.07.30 11:38:19 INFO io.helidon.tests.integration.nativeimage.mp1.JaxRsResource Thread[helidon-9,5,server]: This message is here to make sure runtime logging configuration works
Tests finished in 1516 millis
2021.07.30 11:38:20 SEVERE io.jaegertracing.internal.reporters.RemoteReporter Thread[main,5,main]: Remote reporter error
io.jaegertracing.internal.exceptions.SenderException: Failed to flush spans.
	at io.jaegertracing.thrift.internal.senders.ThriftSender.flush(ThriftSender.java:116)
	at io.jaegertracing.thrift.internal.senders.ThriftSender.close(ThriftSender.java:126)
	at io.jaegertracing.internal.reporters.RemoteReporter.close(RemoteReporter.java:105)
	at io.jaegertracing.internal.JaegerTracer.close(JaegerTracer.java:237)
	at io.opentracing.util.GlobalTracer.close(GlobalTracer.java:219)
	at io.helidon.tests.integration.nativeimage.mp1.Mp1Main.main(Mp1Main.java:123)
Caused by: io.jaegertracing.internal.exceptions.SenderException: Could not send 3 spans
	at io.jaegertracing.thrift.internal.senders.HttpSender.send(HttpSender.java:70)
	at io.jaegertracing.thrift.internal.senders.ThriftSender.flush(ThriftSender.java:114)
	... 5 more
Caused by: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:14268
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:265)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:183)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
	at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
	at okhttp3.RealCall.execute(RealCall.java:81)
	at io.jaegertracing.thrift.internal.senders.HttpSender.send(HttpSender.java:68)
	... 6 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Ljava_net_ConnectException_2_0002e_0003cinit_0003e_00028Ljava_lang_String_2_00029V(JNIJavaCallWrappers.java:0)
	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:609)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.java:130)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:263)
	... 25 more

2021.07.30 11:38:20 INFO io.helidon.microprofile.server.ServerCdiExtension Thread[main,5,main]: Server stopped in 2 milliseconds.
```

**Comment by barchetta** [comment]
I can no longer reproduce this. Closing.
