### ISSUE TITLE
2.3.3 staged: native-image build fails for helidon-quickstart-se

### ISSUE THREAD

**Issue by barchetta** [oracle/helidon#3371]
I'm testing the staged bits for 2.3.3 and hit this issue. Note that it does NOT seem to be an issue on the 2.4.0 (master) branch. So maybe we missed something in a backport.

JDK: Java 11.0.12
GraalVM: graalvm-ce-java11-21.1.0 and graalvm-ce-java11-21.0.0.2

Building native image for `examples/quickstarts/helidon-quickstart-se` (and likely others) fails. See errors below. To reproduce:

```
git checkout tags/2.3.3
mvn clean install -DskipTests
cd examples/quickstarts/helidon-quickstart-se
mvn clean install -Pnative-image 
```
Errors:

```
[INFO] --- helidon-maven-plugin:2.2.3:native-image (native-image) @ helidon-quickstart-se ---
[INFO] Building native image :/Users/jdipol/GitHub/barchetta/helidon/examples/quickstarts/helidon-quickstart-se/target/helidon-quickstart-se
[INFO] [helidon-quickstart-se:78761]    classlist:   1,548.15 ms,  0.96 GB
[INFO] [helidon-quickstart-se:78761]        (cap):   2,039.95 ms,  0.96 GB
[INFO] [helidon-quickstart-se:78761]        setup:   3,934.08 ms,  0.96 GB
[INFO] 2021.09.04 13:00:02 INFO io.helidon.common.LogConfig Thread[ForkJoinPool-4-worker-3,5,main]: Logging at initialization configured using classpath: /logging.properties
[INFO] [helidon-quickstart-se:78761]     (clinit):     622.19 ms,  3.24 GB
[INFO] [helidon-quickstart-se:78761]   (typeflow):  14,477.40 ms,  3.24 GB
[INFO] [helidon-quickstart-se:78761]    (objects):  14,591.91 ms,  3.24 GB
[INFO] [helidon-quickstart-se:78761]   (features):   1,258.22 ms,  3.24 GB
[INFO] [helidon-quickstart-se:78761]     analysis:  32,295.08 ms,  3.24 GB
[WARNING] Error: Unsupported features in 3 methods
[WARNING] Detailed message:
[WARNING] Error: Detected a started Thread in the image heap. Threads running in the image generator are no longer running at image runtime.  To see how this object got instantiated use --trace-object-instantiation=java.lang.Thread. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
[WARNING] Trace: Object was reached by
[WARNING] 	reading field java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.leader of
[WARNING] 		constant java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue@314c3331 reached by
[WARNING] 	reading field java.util.concurrent.ThreadPoolExecutor.workQueue of
[WARNING] 		constant java.util.concurrent.ScheduledThreadPoolExecutor@6051e655 reached by
[WARNING] 	reading field java.util.concurrent.Executors$DelegatedExecutorService.e of
[WARNING] 		constant java.util.concurrent.Executors$DelegatedScheduledExecutorService@2fa9e950 reached by
[WARNING] 	scanning method io.helidon.metrics.ExponentiallyDecayingReservoir.onServerShutdown(ExponentiallyDecayingReservoir.java:79)
[WARNING] Call path from entry point to io.helidon.metrics.ExponentiallyDecayingReservoir.onServerShutdown():
[WARNING] 	at io.helidon.metrics.ExponentiallyDecayingReservoir.onServerShutdown(ExponentiallyDecayingReservoir.java:79)
[WARNING] 	at io.helidon.metrics.MetricsSupport.onShutdown(MetricsSupport.java:435)
[WARNING] 	at io.helidon.servicecommon.rest.HelidonRestServiceSupport.webServerStopped(HelidonRestServiceSupport.java:114)
[WARNING] 	at io.helidon.servicecommon.rest.HelidonRestServiceSupport$$Lambda$1198/0x00000007c10f6c40.run(Unknown Source)
[WARNING] 	at com.oracle.svm.core.jdk.RuntimeSupport.executeHooks(RuntimeSupport.java:125)
[WARNING] 	at com.oracle.svm.core.jdk.RuntimeSupport.executeStartupHooks(RuntimeSupport.java:75)
[WARNING] 	at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:137)
[WARNING] 	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:182)
[WARNING] 	at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
[WARNING] Error: Detected a started Thread in the image heap. Threads running in the image generator are no longer running at image runtime.  To see how this object got instantiated use --trace-object-instantiation=java.lang.Thread. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
[WARNING] Trace: Object was reached by
[WARNING] 	reading field java.util.concurrent.ThreadPoolExecutor$Worker.thread of
[WARNING] 		constant java.util.concurrent.ThreadPoolExecutor$Worker@2cb46cfb reached by
[WARNING] 	reading field java.util.HashMap$Node.key of
[WARNING] 		constant java.util.HashMap$Node@e8a03e1 reached by
[WARNING] 	indexing into array
[WARNING] 		constant java.util.HashMap$Node[]@4936b3d0 reached by
[WARNING] 	reading field java.util.HashMap.table of
[WARNING] 		constant java.util.HashMap@4ce83e22 reached by
[WARNING] 	reading field java.util.HashSet.map of
[WARNING] 		constant java.util.HashSet@7dc67139 reached by
[WARNING] 	reading field java.util.concurrent.ThreadPoolExecutor.workers of
[WARNING] 		constant java.util.concurrent.ScheduledThreadPoolExecutor@6051e655 reached by
[WARNING] 	reading field java.util.concurrent.Executors$DelegatedExecutorService.e of
[WARNING] 		constant java.util.concurrent.Executors$DelegatedScheduledExecutorService@2fa9e950 reached by
[WARNING] 	scanning method io.helidon.metrics.ExponentiallyDecayingReservoir.onServerShutdown(ExponentiallyDecayingReservoir.java:79)
[WARNING] Call path from entry point to io.helidon.metrics.ExponentiallyDecayingReservoir.onServerShutdown():
[WARNING] 	at io.helidon.metrics.ExponentiallyDecayingReservoir.onServerShutdown(ExponentiallyDecayingReservoir.java:79)
[WARNING] 	at io.helidon.metrics.MetricsSupport.onShutdown(MetricsSupport.java:435)
[WARNING] 	at io.helidon.servicecommon.rest.HelidonRestServiceSupport.webServerStopped(HelidonRestServiceSupport.java:114)
[WARNING] 	at io.helidon.servicecommon.rest.HelidonRestServiceSupport$$Lambda$1198/0x00000007c10f6c40.run(Unknown Source)
[WARNING] 	at com.oracle.svm.core.jdk.RuntimeSupport.executeHooks(RuntimeSupport.java:125)
[WARNING] 	at com.oracle.svm.core.jdk.RuntimeSupport.executeStartupHooks(RuntimeSupport.java:75)
[WARNING] 	at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:137)
[WARNING] 	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:182)
[WARNING] 	at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
[WARNING] Error: Detected a started Thread in the image heap. Threads running in the image generator are no longer running at image runtime.  To see how this object got instantiated use --trace-object-instantiation=java.lang.Thread. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
[WARNING] Trace: Object was reached by
[WARNING] 	reading field java.util.concurrent.locks.AbstractQueuedSynchronizer$Node.thread of
[WARNING] 		constant java.util.concurrent.locks.AbstractQueuedSynchronizer$Node@11e8bafe reached by
[WARNING] 	reading field java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.firstWaiter of
[WARNING] 		constant java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@3af3d3f0 reached by
[WARNING] 	reading field java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.available of
[WARNING] 		constant java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue@314c3331 reached by
[WARNING] 	reading field java.util.concurrent.ThreadPoolExecutor.workQueue of
[WARNING] 		constant java.util.concurrent.ScheduledThreadPoolExecutor@6051e655 reached by
[WARNING] 	reading field java.util.concurrent.Executors$DelegatedExecutorService.e of
[WARNING] 		constant java.util.concurrent.Executors$DelegatedScheduledExecutorService@2fa9e950 reached by
[WARNING] 	scanning method io.helidon.metrics.ExponentiallyDecayingReservoir.onServerShutdown(ExponentiallyDecayingReservoir.java:79)
[WARNING] Call path from entry point to io.helidon.metrics.ExponentiallyDecayingReservoir.onServerShutdown():
[WARNING] 	at io.helidon.metrics.ExponentiallyDecayingReservoir.onServerShutdown(ExponentiallyDecayingReservoir.java:79)
[WARNING] 	at io.helidon.metrics.MetricsSupport.onShutdown(MetricsSupport.java:435)
[WARNING] 	at io.helidon.servicecommon.rest.HelidonRestServiceSupport.webServerStopped(HelidonRestServiceSupport.java:114)
[WARNING] 	at io.helidon.servicecommon.rest.HelidonRestServiceSupport$$Lambda$1198/0x00000007c10f6c40.run(Unknown Source)
[WARNING] 	at com.oracle.svm.core.jdk.RuntimeSupport.executeHooks(RuntimeSupport.java:125)
[WARNING] 	at com.oracle.svm.core.jdk.RuntimeSupport.executeStartupHooks(RuntimeSupport.java:75)
[WARNING] 	at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:137)
[WARNING] 	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:182)
[WARNING] 	at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
[WARNING]
[WARNING] com.oracle.svm.core.util.UserError$UserException: Unsupported features in 3 methods
[WARNING] Detailed message:
[WARNING] Error: Detected a started Thread in the image heap. Threads running in the image generator are no longer running at image runtime.  To see how this object got instantiated use --trace-object-instantiation=java.lang.Thread. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
[WARNING] Trace: Object was reached by
[WARNING] 	reading field java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.leader of
[WARNING] 		constant java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue@314c3331 reached by
[WARNING] 	reading field java.util.concurrent.ThreadPoolExecutor.workQueue of
[WARNING] 		constant java.util.concurrent.ScheduledThreadPoolExecutor@6051e655 reached by
[WARNING] 	reading field java.util.concurrent.Executors$DelegatedExecutorService.e of
[WARNING] 		constant java.util.concurrent.Executors$DelegatedScheduledExecutorService@2fa9e950 reached by
[WARNING] 	scanning method io.helidon.metrics.ExponentiallyDecayingReservoir.onServerShutdown(ExponentiallyDecayingReservoir.java:79)
[WARNING] Call path from entry point to io.helidon.metrics.ExponentiallyDecayingReservoir.onServerShutdown():
[WARNING] 	at io.helidon.metrics.ExponentiallyDecayingReservoir.onServerShutdown(ExponentiallyDecayingReservoir.java:79)
[WARNING] 	at io.helidon.metrics.MetricsSupport.onShutdown(MetricsSupport.java:435)
[WARNING] 	at io.helidon.servicecommon.rest.HelidonRestServiceSupport.webServerStopped(HelidonRestServiceSupport.java:114)
[WARNING] 	at io.helidon.servicecommon.rest.HelidonRestServiceSupport$$Lambda$1198/0x00000007c10f6c40.run(Unknown Source)
[WARNING] 	at com.oracle.svm.core.jdk.RuntimeSupport.executeHooks(RuntimeSupport.java:125)
[WARNING] 	at com.oracle.svm.core.jdk.RuntimeSupport.executeStartupHooks(RuntimeSupport.java:75)
[WARNING] 	at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:137)
[WARNING] 	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:182)
[WARNING] 	at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
[WARNING] Error: Detected a started Thread in the image heap. Threads running in the image generator are no longer running at image runtime.  To see how this object got instantiated use --trace-object-instantiation=java.lang.Thread. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
[WARNING] Trace: Object was reached by
[WARNING] 	reading field java.util.concurrent.ThreadPoolExecutor$Worker.thread of
[WARNING] 		constant java.util.concurrent.ThreadPoolExecutor$Worker@2cb46cfb reached by
[WARNING] 	reading field java.util.HashMap$Node.key of
[WARNING] 		constant java.util.HashMap$Node@e8a03e1 reached by
[WARNING] 	indexing into array
[WARNING] 		constant java.util.HashMap$Node[]@4936b3d0 reached by
[WARNING] 	reading field java.util.HashMap.table of
[WARNING] 		constant java.util.HashMap@4ce83e22 reached by
[WARNING] 	reading field java.util.HashSet.map of
[WARNING] 		constant java.util.HashSet@7dc67139 reached by
[WARNING] 	reading field java.util.concurrent.ThreadPoolExecutor.workers of
[WARNING] 		constant java.util.concurrent.ScheduledThreadPoolExecutor@6051e655 reached by
[WARNING] 	reading field java.util.concurrent.Executors$DelegatedExecutorService.e of
[WARNING] 		constant java.util.concurrent.Executors$DelegatedScheduledExecutorService@2fa9e950 reached by
[WARNING] 	scanning method io.helidon.metrics.ExponentiallyDecayingReservoir.onServerShutdown(ExponentiallyDecayingReservoir.java:79)
[WARNING] Call path from entry point to io.helidon.metrics.ExponentiallyDecayingReservoir.onServerShutdown():
[WARNING] 	at io.helidon.metrics.ExponentiallyDecayingReservoir.onServerShutdown(ExponentiallyDecayingReservoir.java:79)
[WARNING] 	at io.helidon.metrics.MetricsSupport.onShutdown(MetricsSupport.java:435)
[WARNING] 	at io.helidon.servicecommon.rest.HelidonRestServiceSupport.webServerStopped(HelidonRestServiceSupport.java:114)
[WARNING] 	at io.helidon.servicecommon.rest.HelidonRestServiceSupport$$Lambda$1198/0x00000007c10f6c40.run(Unknown Source)
[WARNING] 	at com.oracle.svm.core.jdk.RuntimeSupport.executeHooks(RuntimeSupport.java:125)
[WARNING] 	at com.oracle.svm.core.jdk.RuntimeSupport.executeStartupHooks(RuntimeSupport.java:75)
[WARNING] 	at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:137)
[WARNING] 	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:182)
[WARNING] 	at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
[WARNING] Error: Detected a started Thread in the image heap. Threads running in the image generator are no longer running at image runtime.  To see how this object got instantiated use --trace-object-instantiation=java.lang.Thread. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
[WARNING] Trace: Object was reached by
[WARNING] 	reading field java.util.concurrent.locks.AbstractQueuedSynchronizer$Node.thread of
[WARNING] 		constant java.util.concurrent.locks.AbstractQueuedSynchronizer$Node@11e8bafe reached by
[WARNING] 	reading field java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.firstWaiter of
[WARNING] 		constant java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@3af3d3f0 reached by
[WARNING] 	reading field java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.available of
[WARNING] 		constant java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue@314c3331 reached by
[WARNING] 	reading field java.util.concurrent.ThreadPoolExecutor.workQueue of
[WARNING] 		constant java.util.concurrent.ScheduledThreadPoolExecutor@6051e655 reached by
[WARNING] 	reading field java.util.concurrent.Executors$DelegatedExecutorService.e of
[WARNING] 		constant java.util.concurrent.Executors$DelegatedScheduledExecutorService@2fa9e950 reached by
[WARNING] 	scanning method io.helidon.metrics.ExponentiallyDecayingReservoir.onServerShutdown(ExponentiallyDecayingReservoir.java:79)
[WARNING] Call path from entry point to io.helidon.metrics.ExponentiallyDecayingReservoir.onServerShutdown():
[WARNING] 	at io.helidon.metrics.ExponentiallyDecayingReservoir.onServerShutdown(ExponentiallyDecayingReservoir.java:79)
[WARNING] 	at io.helidon.metrics.MetricsSupport.onShutdown(MetricsSupport.java:435)
[WARNING] 	at io.helidon.servicecommon.rest.HelidonRestServiceSupport.webServerStopped(HelidonRestServiceSupport.java:114)
[WARNING] 	at io.helidon.servicecommon.rest.HelidonRestServiceSupport$$Lambda$1198/0x00000007c10f6c40.run(Unknown Source)
[WARNING] 	at com.oracle.svm.core.jdk.RuntimeSupport.executeHooks(RuntimeSupport.java:125)
[WARNING] 	at com.oracle.svm.core.jdk.RuntimeSupport.executeStartupHooks(RuntimeSupport.java:75)
[WARNING] 	at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:137)
[WARNING] 	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:182)
[WARNING] 	at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
[WARNING]
[WARNING] 	at com.oracle.svm.core.util.UserError.abort(UserError.java:82)
[WARNING] 	at com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:233)
[WARNING] 	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:798)
[WARNING] 	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:582)
[WARNING] 	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$2(NativeImageGenerator.java:495)
[WARNING] 	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
[WARNING] 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[WARNING] 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[WARNING] 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[WARNING] 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[WARNING] 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[WARNING] Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Unsupported features in 3 methods
[WARNING] Detailed message:
[WARNING] Error: Detected a started Thread in the image heap. Threads running in the image generator are no longer running at image runtime.  To see how this object got instantiated use --trace-object-instantiation=java.lang.Thread. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
[WARNING] Trace: Object was reached by
[WARNING] 	reading field java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.leader of
[WARNING] 		constant java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue@314c3331 reached by
[WARNING] 	reading field java.util.concurrent.ThreadPoolExecutor.workQueue of
[WARNING] 		constant java.util.concurrent.ScheduledThreadPoolExecutor@6051e655 reached by
[WARNING] 	reading field java.util.concurrent.Executors$DelegatedExecutorService.e of
[WARNING] 		constant java.util.concurrent.Executors$DelegatedScheduledExecutorService@2fa9e950 reached by
[WARNING] 	scanning method io.helidon.metrics.ExponentiallyDecayingReservoir.onServerShutdown(ExponentiallyDecayingReservoir.java:79)
[WARNING] Call path from entry point to io.helidon.metrics.ExponentiallyDecayingReservoir.onServerShutdown():
[WARNING] 	at io.helidon.metrics.ExponentiallyDecayingReservoir.onServerShutdown(ExponentiallyDecayingReservoir.java:79)
[WARNING] 	at io.helidon.metrics.MetricsSupport.onShutdown(MetricsSupport.java:435)
[WARNING] 	at io.helidon.servicecommon.rest.HelidonRestServiceSupport.webServerStopped(HelidonRestServiceSupport.java:114)
[WARNING] 	at io.helidon.servicecommon.rest.HelidonRestServiceSupport$$Lambda$1198/0x00000007c10f6c40.run(Unknown Source)
[WARNING] 	at com.oracle.svm.core.jdk.RuntimeSupport.executeHooks(RuntimeSupport.java:125)
[WARNING] 	at com.oracle.svm.core.jdk.RuntimeSupport.executeStartupHooks(RuntimeSupport.java:75)
[WARNING] 	at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:137)
[WARNING] 	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:182)
[WARNING] 	at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
[WARNING] Error: Detected a started Thread in the image heap. Threads running in the image generator are no longer running at image runtime.  To see how this object got instantiated use --trace-object-instantiation=java.lang.Thread. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
[WARNING] Trace: Object was reached by
[WARNING] 	reading field java.util.concurrent.ThreadPoolExecutor$Worker.thread of
[WARNING] 		constant java.util.concurrent.ThreadPoolExecutor$Worker@2cb46cfb reached by
[WARNING] 	reading field java.util.HashMap$Node.key of
[WARNING] 		constant java.util.HashMap$Node@e8a03e1 reached by
[WARNING] 	indexing into array
[WARNING] 		constant java.util.HashMap$Node[]@4936b3d0 reached by
[WARNING] 	reading field java.util.HashMap.table of
[WARNING] 		constant java.util.HashMap@4ce83e22 reached by
[WARNING] 	reading field java.util.HashSet.map of
[WARNING] 		constant java.util.HashSet@7dc67139 reached by
[WARNING] 	reading field java.util.concurrent.ThreadPoolExecutor.workers of
[WARNING] 		constant java.util.concurrent.ScheduledThreadPoolExecutor@6051e655 reached by
[WARNING] 	reading field java.util.concurrent.Executors$DelegatedExecutorService.e of
[WARNING] 		constant java.util.concurrent.Executors$DelegatedScheduledExecutorService@2fa9e950 reached by
[WARNING] 	scanning method io.helidon.metrics.ExponentiallyDecayingReservoir.onServerShutdown(ExponentiallyDecayingReservoir.java:79)
[WARNING] Call path from entry point to io.helidon.metrics.ExponentiallyDecayingReservoir.onServerShutdown():
[WARNING] 	at io.helidon.metrics.ExponentiallyDecayingReservoir.onServerShutdown(ExponentiallyDecayingReservoir.java:79)
[WARNING] 	at io.helidon.metrics.MetricsSupport.onShutdown(MetricsSupport.java:435)
[WARNING] 	at io.helidon.servicecommon.rest.HelidonRestServiceSupport.webServerStopped(HelidonRestServiceSupport.java:114)
[WARNING] 	at io.helidon.servicecommon.rest.HelidonRestServiceSupport$$Lambda$1198/0x00000007c10f6c40.run(Unknown Source)
[WARNING] 	at com.oracle.svm.core.jdk.RuntimeSupport.executeHooks(RuntimeSupport.java:125)
[WARNING] 	at com.oracle.svm.core.jdk.RuntimeSupport.executeStartupHooks(RuntimeSupport.java:75)
[WARNING] 	at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:137)
[WARNING] 	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:182)
[WARNING] 	at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
[WARNING] Error: Detected a started Thread in the image heap. Threads running in the image generator are no longer running at image runtime.  To see how this object got instantiated use --trace-object-instantiation=java.lang.Thread. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
[WARNING] Trace: Object was reached by
[WARNING] 	reading field java.util.concurrent.locks.AbstractQueuedSynchronizer$Node.thread of
[WARNING] 		constant java.util.concurrent.locks.AbstractQueuedSynchronizer$Node@11e8bafe reached by
[WARNING] 	reading field java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.firstWaiter of
[WARNING] 		constant java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@3af3d3f0 reached by
[WARNING] 	reading field java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.available of
[WARNING] 		constant java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue@314c3331 reached by
[WARNING] 	reading field java.util.concurrent.ThreadPoolExecutor.workQueue of
[WARNING] 		constant java.util.concurrent.ScheduledThreadPoolExecutor@6051e655 reached by
[WARNING] 	reading field java.util.concurrent.Executors$DelegatedExecutorService.e of
[WARNING] 		constant java.util.concurrent.Executors$DelegatedScheduledExecutorService@2fa9e950 reached by
[WARNING] 	scanning method io.helidon.metrics.ExponentiallyDecayingReservoir.onServerShutdown(ExponentiallyDecayingReservoir.java:79)
[WARNING] Call path from entry point to io.helidon.metrics.ExponentiallyDecayingReservoir.onServerShutdown():
[WARNING] 	at io.helidon.metrics.ExponentiallyDecayingReservoir.onServerShutdown(ExponentiallyDecayingReservoir.java:79)
[WARNING] 	at io.helidon.metrics.MetricsSupport.onShutdown(MetricsSupport.java:435)
[WARNING] 	at io.helidon.servicecommon.rest.HelidonRestServiceSupport.webServerStopped(HelidonRestServiceSupport.java:114)
[WARNING] 	at io.helidon.servicecommon.rest.HelidonRestServiceSupport$$Lambda$1198/0x00000007c10f6c40.run(Unknown Source)
[WARNING] 	at com.oracle.svm.core.jdk.RuntimeSupport.executeHooks(RuntimeSupport.java:125)
[WARNING] 	at com.oracle.svm.core.jdk.RuntimeSupport.executeStartupHooks(RuntimeSupport.java:75)
[WARNING] 	at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:137)
[WARNING] 	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:182)
[WARNING] 	at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
[WARNING]
[WARNING] 	at com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:129)
[WARNING] 	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:795)
[WARNING] 	... 8 more
[WARNING] Error: Image build request failed with exit status 1
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  57.821 s
[INFO] Finished at: 2021-09-04T13:00:35-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.helidon.build-tools:helidon-maven-plugin:2.2.3:native-image (native-image) on project helidon-quickstart-se: Image generation failed, exit code: 1 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by tjquinno** [comment]
This is part of the metrics performance improvements. 

IIUC the thread cannot start when it is, but needs to start later--at "true" runtime as native sees it.

I'll look at a way to start that thread later.
