### ISSUE TITLE
Intermittent NPE in Jersey BasicRequestTest

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#3375]
Happened on PR against 2.3.3 branch (#3373).

```
java.lang.NullPointerException
	at io.helidon.common.reactive.BufferedEmittingPublisher$1.request(BufferedEmittingPublisher.java:96)
	at io.helidon.media.common.DataChunkInputStream.read(DataChunkInputStream.java:164)
	at io.helidon.media.common.DataChunkInputStream.read(DataChunkInputStream.java:109)
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:83)
	at org.glassfish.jersey.message.internal.EntityInputStream.read(EntityInputStream.java:69)
	at io.helidon.jersey.connector.BasicRequestTest.testInputStreamEntity(BasicRequestTest.java:262)
```

No further information found.

**Comment by danielkec** [comment]
Caused by RC between request
https://github.com/oracle/helidon/blob/bdf53d6d974b1d8bcecea36ce2f5c789a55788df/common/reactive/src/main/java/io/helidon/common/reactive/BufferedEmittingPublisher.java#L95-L97
and terminal clean up
https://github.com/oracle/helidon/blob/bdf53d6d974b1d8bcecea36ce2f5c789a55788df/common/reactive/src/main/java/io/helidon/common/reactive/BufferedEmittingPublisher.java#L470-L473
