### ISSUE TITLE
Intermittent TckLRATypeTests.supportsWithLRAAtSuperclass

### ISSUE THREAD

**Issue by danielkec** [oracle/helidon#3400]
https://builds.helidon.io/E37845ACF20524805CB8C9F66506E60A/tests/15

```
at org.junit.Assert.assertTrue(Assert.java:53)
	at org.eclipse.microprofile.lra.tck.TckLRATypeTests.resourceRequest(TckLRATypeTests.java:623)
	at org.eclipse.microprofile.lra.tck.TckLRATypeTests.supportsWithLRAAtSuperclass(TckLRATypeTests.java:431)
```

[tck-lra.zip](https://github.com/oracle/helidon/files/7142281/tck-lra.zip)

**Comment by danielkec** [comment]
@spericas just confirmed it with another incident
```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.eclipse.microprofile.lra.tck.TckLRATypeTests.resourceRequest(TckLRATypeTests.java:623)
	at org.eclipse.microprofile.lra.tck.TckLRATypeTests.requiredWithLRA(TckLRATypeTests.java:93)
```

**Comment by m0mus** [comment]
Cannot reproduce

**Comment by romain-grecourt** [comment]
Saw it against 2.x [here](https://github.com/helidon-io/helidon/actions/runs/5182826251/jobs/9340028485)

```
[ERROR] org.eclipse.microprofile.lra.tck.TckLRATypeTests.requiredWithLRAAtInterface  Time elapsed: 0.045 s  <<< FAILURE!
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.eclipse.microprofile.lra.tck.TckLRATypeTests.resourceRequest(TckLRATypeTests.java:623)
	at org.eclipse.microprofile.lra.tck.TckLRATypeTests.requiredWithLRAAtInterface(TckLRATypeTests.java:244)
```
