### ISSUE TITLE
Intermittent test failure in io.helidon.webserver.PrematureConnectionCutTest.cutConnectionBefore100Continue

### ISSUE THREAD

**Issue by ljnelson** [oracle/helidon#3413]
Stack seen in a recent pipeline build:
```
io.helidon.webserver.PrematureConnectionCutTest.cutConnectionBefore100Continue  Time elapsed: 3.012 s  <<< FAILURE!
java.lang.AssertionError: 

Expected: is <5>
     but: was <4>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at io.helidon.webserver.PrematureConnectionCutTest.cutConnectionBefore100Continue(PrematureConnectionCutTest.java:94)
```

**Comment by ljnelson** [comment]
Looks like https://github.com/oracle/helidon/pull/3365 is maybe? supposed to fix this?

**Comment by tomas-langer** [comment]
Happened to me today on local machine
