### ISSUE TITLE
Config metadata annotation processing throws NPE when @ConfiguredOption annotates method with Iterable argument

### ISSUE THREAD

**Issue by tjquinno** [oracle/helidon#3542]
## Environment Details
* Helidon Version: 2.x
* Helidon SE or Helidon MP
* JDK version:
* OS:
* Docker version (if applicable):

----------

## Problem Description
A builder method with an `Iterable` as a parameter causes the config annotation processor to throw an NPE. 

Changing the parameter type to `List` is a workaround, but the processor should handle `Iterable` (and perhaps `Iterator`, others??) or at least issue a more helpful error message.

## Steps to reproduce
Create an interface with a builder like this:

```java
public interface XXX {
...
    @Configured(prefix = "xxx")
    interface Builder extends io.helidon.common.Builder<XXX> {

        @ConfiguredOption(key = "things", description = "...")
        Builder things(Iterable<String> stuff);
    }
}
```
Trying to build the project triggers the NPE. (relevant portion below)
```
java.lang.NullPointerException
	at io.helidon.config.metadata.processor.ConfigMetadataHandler.allowedValues(ConfigMetadataHandler.java:700)
	at io.helidon.config.metadata.processor.ConfigMetadataHandler.allowedValues(ConfigMetadataHandler.java:716)
	at io.helidon.config.metadata.processor.ConfigMetadataHandler.processBuilderMethod(ConfigMetadataHandler.java:516)
	at io.helidon.config.metadata.processor.ConfigMetadataHandler.lambda$processBuilderType$9(ConfigMetadataHandler.java:330)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at io.helidon.config.metadata.processor.ConfigMetadataHandler.processBuilderType(ConfigMetadataHandler.java:330)
	at io.helidon.config.metadata.processor.ConfigMetadataHandler.processConfiguredAnnotation(ConfigMetadataHandler.java:206)
	at io.helidon.config.metadata.processor.ConfigMetadataHandler.lambda$processClass$0(ConfigMetadataHandler.java:146)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.helidon.config.metadata.processor.ConfigMetadataHandler.processClass(ConfigMetadataHandler.java:146)
	at io.helidon.config.metadata.processor.ConfigMetadataHandler.doProcess(ConfigMetadataHandler.java:131)
	at io.helidon.config.metadata.processor.ConfigMetadataHandler.process(ConfigMetadataHandler.java:119)
	at io.helidon.config.metadata.processor.ConfigMetadataProcessor.process(ConfigMetadataProcessor.java:66)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:980)
```

**Comment by dalexandrov** [comment]
Fixed with https://github.com/oracle/helidon/pull/3600
