### ISSUE TITLE
WebClient seems to have race condition

### ISSUE THREAD

**Issue by tjquinno** [oracle/helidon#3562]
## Environment Details
* Helidon Version: 2.x
* Helidon SE or Helidon MP
* JDK version:
* OS:
* Docker version (if applicable):

----------

## Steps to reproduce
1. Start the Helidon MP QuickStart app at port 8080.
2. Expand the attached zip [myproject.zip](https://github.com/oracle/helidon/files/7368816/myproject.zip)
3. `cd myproject`
4. `mvn clean test -Dtest=DefaultApiTest`

Running locally on my Mac, two of the three tests fail:
```
[INFO] Running io.helidon.examples.openapi.webclient.api.DefaultApiTest
[ERROR] Tests run: 3, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.827 s <<< FAILURE! - in io.helidon.examples.openapi.webclient.api.DefaultApiTest
[ERROR] getPersonalizedGreetingTest(io.helidon.examples.openapi.webclient.api.DefaultApiTest)  Time elapsed: 0.498 s  <<< ERROR!
io.helidon.examples.openapi.webclient.ApiException: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Value supplier not yet set
	at io.helidon.examples.openapi.webclient.api.DefaultApiTest.getPersonalizedGreetingTest(DefaultApiTest.java:77)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Value supplier not yet set
	at io.helidon.examples.openapi.webclient.api.DefaultApiTest.getPersonalizedGreetingTest(DefaultApiTest.java:77)
Caused by: java.lang.IllegalStateException: Value supplier not yet set
	at io.helidon.examples.openapi.webclient.api.DefaultApiTest.getPersonalizedGreetingTest(DefaultApiTest.java:77)

```
Running the test methods individually works for all of them.

Now, comment out line 66 in `pom.xml` (the line specifying `<parallel>`). The tests run successfully, with the possible exception of getting 
```
org.junit.ComparisonFailure: Returned default greeting expected:<H[ello] World!> but was:<H[ola] World!>
```
because of test ordering. But the original problem is gone with the tests running serially instead of in parallel.

It seems running the tests  _in parallel_ exposes a race condition somewhere. I do not think it is in the example project.

**Comment by tomas-langer** [comment]
```
Caused by: java.lang.IllegalStateException: Value supplier not yet set
	at io.helidon.webclient.NettyClient.lambda$static$1(NettyClient.java:75)
	at io.helidon.common.LazyValueImpl.get(LazyValueImpl.java:118)
	at io.helidon.webclient.WebClientRequestBuilderImpl.lambda$invoke$21(WebClientRequestBuilderImpl.java:571)
	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2333)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:144)
	at io.helidon.webclient.WebClientRequestBuilderImpl.invoke(WebClientRequestBuilderImpl.java:543)
	at io.helidon.webclient.WebClientRequestBuilderImpl.lambda$request$13(WebClientRequestBuilderImpl.java:400)
	at io.helidon.common.context.Contexts.runInContext(Contexts.java:137)
	at io.helidon.webclient.WebClientRequestBuilderImpl.request(WebClientRequestBuilderImpl.java:400)
	at io.helidon.webclient.WebClientRequestBuilderImpl.submit(WebClientRequestBuilderImpl.java:405)
```

**Comment by tomas-langer** [comment]
This seems to be incorrect initialization of client:
```java
    // shared by all client instances
    private static LazyValue<NioEventLoopGroup> eventGroup = LazyValue.create(() -> {
        throw new IllegalStateException("Value supplier not yet set");
    });
```

**Comment by tomas-langer** [comment]
Issue is in `NettyClient`, line 144:
```
    static void configureDefaults(Config globalConfig) {
        if (DEFAULTS_CONFIGURED.compareAndSet(false, true)) {
```

First constructor that hits this starts configuring the defaults, then another thread hits the same and immediately returns, invoking on uninitialized client.
