### ISSUE TITLE
Error 502 when client sets invalid Content-Type in POST request

### ISSUE THREAD

**Issue by mkuchtiak** [oracle/helidon#3673]
## Environment Details
* Helidon Version: 2.3.0
* Helidon SE or Helidon MP: Helidon MP
* JDK version: 11.0.3
* OS: Linux Ubuntu
* Docker version (if applicable):

----------

## Problem Description
We are using helidon in our microserviecs. Our microservices usually provide JAX-RS (Jersey) endpoints, and these endpoints are consumed either by UI or by other microservices via REST requests.

Our (UI) client set incorrectly Content-Type header in the REST request to:

Content-Type: application/json; (semicolon in the end)

This request ended with 502 error, and the user had no idea what's wrong.
We would expect, the request ends with 415 (Unsupported Media Type) error, rather than 5** error. 
Or some other 4** error with some error message.

## Steps to reproduce
1.:Provide some (JAX-RS) POST endpoint (whatever)
2. Use the following client code that calls this endpoint, in java (or use Postman to call this endpoint).

        HttpURLConnection http = (HttpURLConnection) endpointUrl.openConnection();
        http.setDoOutput(true);
        http.setRequestMethod("POST");

        ObjectNode payload = JsonNodeFactory.instance.objectNode()
                              .put("firstName", "John").put("lastName", "Smith");                             // doesn't matter what's here

        byte[] out = payload.toString().getBytes(StandardCharsets.UTF_8);
        int length = out.length;

        http.setFixedLengthStreamingMode(length);
        http.setRequestProperty("Content-Type", "application/json;");                                   // see the semicolon (;) in content-type value
        http.connect();

        try(OutputStream os = http.getOutputStream()) {
            os.write(out);
        }

        System.out.println(http.getResponseCode());                                                            //  here the error is thrown
        System.out.println(http.getResponseMessage());

        try(InputStream is = http.getErrorStream()) {
            String result = IOUtils.toString(is, StandardCharsets.UTF_8);
            System.out.println(result);
        }
        
 This ends with the following IllegalArgumentException (from Helidon):
 
 The error:
SEVERE: Unexpected error occurred during routing!
java.lang.IllegalArgumentException: Could not parse 'application/json;'
	at io.helidon.common.http.MediaType.parse(MediaType.java:348)
	at java.base/java.util.Optional.map(Optional.java:265)
	at io.helidon.webserver.HashRequestHeaders.contentType(HashRequestHeaders.java:82)
	at io.helidon.webserver.Request.<init>(Request.java:83)
	at io.helidon.webserver.RequestRouting$RoutedRequest.<init>(RequestRouting.java:255)
	at io.helidon.webserver.RequestRouting.route(RequestRouting.java:86)
	at io.helidon.webserver.ForwardingHandler.lambda$channelRead0$13(ForwardingHandler.java:272)
	at io.helidon.webserver.RequestContext.lambda$runInScope$3(RequestContext.java:64)
	at io.helidon.common.context.Contexts.runInContext(Contexts.java:117)
	at io.helidon.webserver.RequestContext.runInScope(RequestContext.java:62)
	at io.helidon.webserver.ForwardingHandler.channelRead0(ForwardingHandler.java:272)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalStateException: No more elements!
	at io.helidon.common.http.Tokenizer.checkState(Tokenizer.java:172)
	at io.helidon.common.http.Tokenizer.checkState(Tokenizer.java:157)
	at io.helidon.common.http.Tokenizer.consumeTokenIfPresent(Tokenizer.java:54)
	at io.helidon.common.http.MediaType.parse(MediaType.java:324)
	... 34 more

Unexpected end of file from server
java.net.SocketException: Unexpected end of file from server
	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:862)
	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1604)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
	...
 
 Problematic there is the Content-Type header value, ending with semicolon(;):
http.setRequestProperty("Content-Type", "**application/json;"**);   
 
The same error is there when **semicolon(;)** is replaced with **colon(:)**, **question mark(?)**, **comma(,)**, ...

**Comment by mkuchtiak** [comment]
I've tested this also with PATCH request and got the same error. I expect the same error would be also thrown for PUT request.

**Comment by dalexandrov** [comment]
Hello,
I have made an investigation and I can confirm this issue for Helidon 2.3.0.
But this issue is **fixed** in Helidon **2.4.0** so I highly encourage you to upgrade Helidon to 2.4.0.

Best regards,
Dmitry
