### ISSUE TITLE
Intermittent config test failure (ConfigSupplierTest.testSupplierSubscribeOnLeafNode)

### ISSUE THREAD

**Issue by tjquinno** [oracle/helidon#369]
## Environment Details
* Helidon Version: 0.11.0
* Helidon SE
* JDK version: 9.0.4
* OS: wercker node
* Docker version (if applicable): n/a

----------

## Problem Description
Saw a failure of this test; rerunning the failed `build` wercker did not show the error (with no code changes)

```
Tests run: 5, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.05 sec <<< FAILURE! - in io.helidon.config.ConfigSupplierTest
testSupplierSubscribeOnLeafNode  Time elapsed: 0.019 sec  <<< ERROR!
java.lang.IllegalStateException: Recursive update
	at io.helidon.config.ConfigSupplierTest.lambda$testSupplierSubscribeOnLeafNode$3(ConfigSupplierTest.java:93)
	at io.helidon.config.ConfigSupplierTest.testSupplierSubscribeOnLeafNode(ConfigSupplierTest.java:93)
```
----
````
Results :

Tests in error: 
  ConfigSupplierTest.testSupplierSubscribeOnLeafNode:93->lambda$testSupplierSubscribeOnLeafNode$3:93 » IllegalState

Tests run: 1409, Failures: 0, Errors: 1, Skipped: 17

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Helidon Project 0.11.1-SNAPSHOT .................... SUCCESS [  2.445 s]
[INFO] Helidon Common Project ............................. SUCCESS [  0.191 s]
[INFO] Helidon Common ..................................... SUCCESS [ 17.356 s]
[INFO] Helidon Common Reactive ............................ SUCCESS [ 21.601 s]
[INFO] Helidon Config Project ............................. SUCCESS [  1.522 s]
[INFO] Helidon Config Test Infrastructure ................. SUCCESS [  9.270 s]
[INFO] Helidon Config ..................................... FAILURE [ 31.397 s]
````

## Steps to reproduce
Intermittent

**Comment by tomas-langer** [comment]
Same test, different issue, also intermittent:
```
Failed tests: 
  ConfigSupplierTest.testSupplierSubscribeOnLeafNode:107 
Expected: is "new value"
     but: was "string value"
```

**Comment by tomas-langer** [comment]
This test no longer fails. In 2.0 the approach has changed altogether.
