### ISSUE TITLE
ForwardingHandler silently swallows exception with default logging

### ISSUE THREAD

**Issue by barchetta** [oracle/helidon#3783]
## Environment Details
* Helidon Version: 2.4.1
* Helidon SE 
* JDK version: 11.0.12
----------

## Problem Description
While investigating an issue that involved constraining native image max heap size my Helidon SE application started to silently fail connections with nothing logged from the server. If I set `io.helidon.webserver.level=FINE` in logging.properties I got:

```
2022.01.04 17:13:37 FINE io.helidon.webserver.ForwardingHandler Thread[nioEventLoopGroup-3-5,10,main]: [Handler: 301500701, Channel: 0x9fc6ba64] Exception caught: java.lang.OutOfMemoryError: Direct buffer memory
```
But no stack trace.  

Here is the code: https://github.com/oracle/helidon/blob/50239a037d2d1eae463f43a4cfa7446e954ae295/webserver/webserver/src/main/java/io/helidon/webserver/ForwardingHandler.java#L478

Maybe this code is deferring reporting of the exception to `failPublisher(cause);`

## Steps to reproduce
1. Generate `bare-se` project (quickstart should work too)
2.  `mvn clean install -Pnative-image`
3.  `target/bare-se -Xmx32m`
4. Run `curl -X GET http://localhost:8080/greet` a couple times and it will start to fail with nothing reported by the server.

**Comment by danielkec** [comment]
Stack trace:
```java
java.lang.OutOfMemoryError: Cannot reserve 16777216 bytes of direct buffer memory (allocated: 7, limit: 16777216)
        at java.nio.Bits.reserveMemory(Bits.java:178)
        at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:121)
        at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:332)
        at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:632)
        at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:607)
        at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:202)
        at io.netty.buffer.PoolArena.tcacheAllocateSmall(PoolArena.java:172)
        at io.netty.buffer.PoolArena.allocate(PoolArena.java:134)
        at io.netty.buffer.PoolArena.allocate(PoolArena.java:126)
        at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:395)
        at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187)
        at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:178)
        at io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:139)
        at io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:114)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:150)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:833)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:596)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)

```
