### ISSUE TITLE
3.0: Quickstart MP fails to start in native image

### ISSUE THREAD

**Issue by dalexandrov** [oracle/helidon#3802]
## Environment Details
* Helidon Version: 3.0.0-SNAPSHOT
* Helidon MP
* JDK version: GraalVM 21.3.0 Java 17 CE (Java Version 17.0.1+12-jvmci-21.3-b05)
* OS: MacOS 

----------

Quickstart MP fails to start when compiled to native image with the following exception in Health Module:

```
Exception in thread "main" org.jboss.weld.exceptions.DeploymentException   test-classes/                                                                                 
        at org.jboss.weld.bootstrap.events.AbstractDeploymentContainerEvent.fire(AbstractDeploymentContainerEvent.java:38)
        at org.jboss.weld.bootstrap.events.AfterDeploymentValidationImpl.fire(AfterDeploymentValidationImpl.java:28)
        at org.jboss.weld.bootstrap.WeldStartup.validateBeans(WeldStartup.java:510)
        at org.jboss.weld.bootstrap.WeldBootstrap.validateBeans(WeldBootstrap.java:93)
        at io.helidon.microprofile.cdi.HelidonContainerImpl.doStart(HelidonContainerImpl.java:298)
        at io.helidon.common.context.Contexts.runInContext(Contexts.java:137)
        at io.helidon.microprofile.cdi.HelidonContainerImpl.start(HelidonContainerImpl.java:250)
        at io.helidon.microprofile.cdi.Main.main(Main.java:80)
Caused by: jakarta.enterprise.event.ObserverException
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at java.lang.Class.newInstance(DynamicHub.java:920)
        at org.jboss.weld.security.NewInstanceAction.run(NewInstanceAction.java:33)
        at java.security.AccessController.doPrivileged(AccessController.java:123)
        at org.jboss.weld.injection.Exceptions.rethrowException(Exceptions.java:40)
        at org.jboss.weld.injection.Exceptions.rethrowException(Exceptions.java:86)
        at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:105)
        at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:85)
        at org.jboss.weld.injection.MethodInvocationStrategy$SimpleMethodInvocationStrategy.invoke(MethodInvocationStrategy.java:168)
        at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:330)
        at org.jboss.weld.event.ExtensionObserverMethodImpl.sendEvent(ExtensionObserverMethodImpl.java:123)
        at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:308)
        at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:286)
        at jakarta.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:125)
        at org.jboss.weld.util.Observers.notify(Observers.java:166)
        at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:285)
        at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:273)
        at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:177)
        at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:171)
        at org.jboss.weld.bootstrap.events.AbstractContainerEvent.fire(AbstractContainerEvent.java:53)
        at org.jboss.weld.bootstrap.events.AbstractDeploymentContainerEvent.fire(AbstractDeploymentContainerEvent.java:35)
        ... 7 more
Caused by: java.lang.NoSuchMethodException: class io.helidon.microprofile.health.HealthCdiExtension, method: clearAnnotationInfo, paramTypes: [interface jakarta.enterprise.inject.spi.AfterDeploymentValidation]
        at org.jboss.weld.security.MethodLookupAction.lookupMethod(MethodLookupAction.java:55)
        at org.jboss.weld.injection.SecurityActions.lookupMethod(SecurityActions.java:77)
        at org.jboss.weld.injection.VirtualMethodInjectionPoint.getMethod(VirtualMethodInjectionPoint.java:69)
        at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95)
        ... 21 more
```

**Comment by m0mus** [comment]
It's work in progress.
