### ISSUE TITLE
Connection reset by peer logged in severe

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#3902]
Helidon 2.4.2
OS: Mac OS (does not appear on Linux)

Application runs as excpected, log is being filled with this message.

The following exception can be seen in logs:

```
2022.02.17 16:04:05 SEVERE io.helidon.webserver.ForwardingHandler !thread!: Error intercepted before request context established.
java.io.IOException: Connection reset by peer
	at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358)
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:258)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

This is from the failPublisher call that was added

**Comment by tomas-langer** [comment]
This is a regression since 2.4.1

**Comment by tomas-langer** [comment]
In this case the exception is received in `ForwardingHandler.exceptionCaught(ctx, cause)`, because Netty cannot continue handling this connection (as the peer has closed it).
This is normal behavior, not an error (as we do not have a context - we are not processing any request). We should fix the `failPublisher` method to only report non-IO exceptions as issues (as those probably come from our internal code).
We cannot really depend on the text of the exception, as it varies across operating systems. I think that all IOExceptions should be logged in FINE and only other exception deserve higher log level.

**Comment by spericas** [comment]
Related to PR #3792

**Comment by spericas** [comment]
PR #3914
