### ISSUE TITLE
ProxyFactory createProxyName generates a NPE when not in an enclosing type

### ISSUE THREAD

**Issue by jvissers** [oracle/helidon#4123]
* Helidon Version: 2.5.0
* Helidon MP
* JDK version: Java(TM) SE Runtime Environment (build 17.0.2+8-LTS-86)
* OS: Ubuntu 21.10
----------

## Problem Description
The use case is that I'm trying to use a CDI based decorator to invoke a MapStruct mapper.
A `@Decorator` applied on a top-level class yields a NPE in the `createProxyName` call of the augmented `ProxyFactory` class 

```
➜  target git:(master) ✗ java -jar helidon-mapstruct-mp.jar
2022.04.13 13:21:28 INFO io.helidon.common.LogConfig Thread[main,5,main]: Logging at initialization configured using classpath: /logging.properties
Exception in thread "main" java.lang.ExceptionInInitializerError
        at io.helidon.microprofile.cdi.ContainerInstanceHolder.fromBuildTimeInitializer(ContainerInstanceHolder.java:58)
        at io.helidon.microprofile.cdi.ContainerInstanceHolder.get(ContainerInstanceHolder.java:50)
        at io.helidon.microprofile.cdi.Main.<clinit>(Main.java:55)
Caused by: java.lang.NullPointerException
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:564)
        at java.base/java.util.concurrent.ForkJoinTask.reportExecutionException(ForkJoinTask.java:604)
        at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:981)
        at org.jboss.weld.executor.AbstractExecutorServices.checkForExceptions(AbstractExecutorServices.java:73)
        at org.jboss.weld.executor.AbstractExecutorServices.invokeAllAndCheckForExceptions(AbstractExecutorServices.java:59)
        at org.jboss.weld.executor.AbstractExecutorServices.invokeAllAndCheckForExceptions(AbstractExecutorServices.java:67)
        at org.jboss.weld.bootstrap.ConcurrentBeanDeployer.createClassBeans(ConcurrentBeanDeployer.java:65)
        at org.jboss.weld.bootstrap.BeanDeployment.createBeans(BeanDeployment.java:256)
        at org.jboss.weld.bootstrap.WeldStartup.deployBeans(WeldStartup.java:438)
        at org.jboss.weld.bootstrap.WeldBootstrap.deployBeans(WeldBootstrap.java:86)
        at io.helidon.microprofile.cdi.HelidonContainerImpl.init(HelidonContainerImpl.java:215)
        at io.helidon.common.context.Contexts.runInContext(Contexts.java:137)
        at io.helidon.microprofile.cdi.HelidonContainerImpl.initInContext(HelidonContainerImpl.java:136)
        at io.helidon.microprofile.cdi.HelidonContainerImpl.create(HelidonContainerImpl.java:128)
        at io.helidon.microprofile.cdi.BuildTimeInitializer.createContainer(BuildTimeInitializer.java:51)
        at io.helidon.microprofile.cdi.BuildTimeInitializer.<clinit>(BuildTimeInitializer.java:31)
        ... 3 more
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Class.getName()" because "superInterface" is null
        at org.jboss.weld.bean.proxy.ProxyFactory.createProxyName(ProxyFactory.java:340)
        at org.jboss.weld.bean.proxy.ProxyFactory.getProxyName(ProxyFactory.java:280)
        at org.jboss.weld.bean.proxy.ProxyFactory.<init>(ProxyFactory.java:191)
        at org.jboss.weld.bean.proxy.ProxyFactory.<init>(ProxyFactory.java:187)
        at org.jboss.weld.bean.proxy.DecoratorProxyFactory.<init>(DecoratorProxyFactory.java:68)
        at org.jboss.weld.injection.producer.DecoratorInjectionTarget$1.createEnhancedSubclass(DecoratorInjectionTarget.java:78)
        at org.jboss.weld.injection.producer.SubclassedComponentInstantiator.initEnhancedSubclass(SubclassedComponentInstantiator.java:86)
        at org.jboss.weld.injection.producer.SubclassedComponentInstantiator.<init>(SubclassedComponentInstantiator.java:79)
        at org.jboss.weld.injection.producer.DecoratorInjectionTarget$1.<init>(DecoratorInjectionTarget.java:75)
        at org.jboss.weld.injection.producer.DecoratorInjectionTarget.initInstantiator(DecoratorInjectionTarget.java:75)
        at org.jboss.weld.injection.producer.BasicInjectionTarget.<init>(BasicInjectionTarget.java:94)
        at org.jboss.weld.injection.producer.BasicInjectionTarget.<init>(BasicInjectionTarget.java:78)
        at org.jboss.weld.injection.producer.BeanInjectionTarget.<init>(BeanInjectionTarget.java:58)
        at org.jboss.weld.injection.producer.BeanInjectionTarget.<init>(BeanInjectionTarget.java:63)
        at org.jboss.weld.injection.producer.DecoratorInjectionTarget.<init>(DecoratorInjectionTarget.java:58)
        at org.jboss.weld.manager.InjectionTargetFactoryImpl.chooseInjectionTarget(InjectionTargetFactoryImpl.java:124)
        at org.jboss.weld.manager.InjectionTargetFactoryImpl.createInjectionTarget(InjectionTargetFactoryImpl.java:88)
        at org.jboss.weld.bean.ManagedBean.<init>(ManagedBean.java:102)
        at org.jboss.weld.bean.DecoratorImpl.<init>(DecoratorImpl.java:61)
        at org.jboss.weld.bean.DecoratorImpl.of(DecoratorImpl.java:50)
        at org.jboss.weld.bootstrap.AbstractBeanDeployer.createDecorator(AbstractBeanDeployer.java:293)
        at org.jboss.weld.bootstrap.BeanDeployer.createClassBean(BeanDeployer.java:214)
        at org.jboss.weld.bootstrap.ConcurrentBeanDeployer$2.doWork(ConcurrentBeanDeployer.java:68)
        at org.jboss.weld.bootstrap.ConcurrentBeanDeployer$2.doWork(ConcurrentBeanDeployer.java:65)
        at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:62)
        at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:55)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedInterruptibleCallable.exec(ForkJoinTask.java:1461)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

## Steps to reproduce
I have a reproducer available. Check [here](https://github.com/jvissers/helidon-mapstruct-mp).

**Comment by tomas-langer** [comment]
Reproduced

**Comment by tomas-langer** [comment]
I now have an integration test that reproduces this issue, working on a fix.
