### ISSUE TITLE
MP Fault Tolerance annotations inheritance fails

### ISSUE THREAD

**Issue by martin-sladecek** [oracle/helidon#4171]
## Environment Details
* Helidon Version: 2.5.0
* Helidon MP
* JDK version: 17
* OS: Linux
* Docker version (if applicable):

----------

## Problem Description
When I try to define an aggregating annotation for FT, like this:
```
@Inherited
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.METHOD, ElementType.TYPE})
@InterceptorBinding
@Timeout(value = 15, unit = ChronoUnit.SECONDS)
@Retry(maxDuration = 50, durationUnit = ChronoUnit.SECONDS)
@CircuitBreaker(delay = 1, delayUnit = ChronoUnit.MINUTES)
public @interface MyFaultTolerance {

}
```

and then use it on a method, it fails with
```
java.lang.NullPointerException: Cannot invoke "org.eclipse.microprofile.metrics.Counter.inc()" because the return value of "io.helidon.microprofile.faulttolerance.FaultToleranceMetrics.getCounter(java.lang.reflect.Method, String)" is null
	at io.helidon.microprofile.faulttolerance.MethodInvoker.updateMetricsAfter(MethodInvoker.java:743) ~[helidon-microprofile-fault-tolerance-2.5.0.jar:2.5.0]
	at io.helidon.microprofile.faulttolerance.MethodInvoker.get(MethodInvoker.java:436) ~[helidon-microprofile-fault-tolerance-2.5.0.jar:2.5.0]
	at io.helidon.microprofile.faulttolerance.CommandInterceptor.interceptCommand(CommandInterceptor.java:54) ~[helidon-microprofile-fault-tolerance-2.5.0.jar:2.5.0]
```

Additionally, if the method contains other FT annotation (e.g. Fallback), then `@MyFaultTolerance` is completely ignored.

## Steps to reproduce
Use the annotation above in the described scenarios.

**Comment by spericas** [comment]
@martin-sladecek Seems more like a CDI stereotype that you are trying to define here. Is it not?

**Comment by martin-sladecek** [comment]
Does not work for me with Stereotypes either.

Nevertheless, Stereotype should not be necessary as Interceptor bindings should be transitive as per documentation:
```
An interceptor binding type may declare other interceptor bindings.

 @Inherited 
 @InterceptorBinding 
 @Target({TYPE, METHOD}) 
 @Retention(RUNTIME) 
 @Valid
 public @interface Secure {}
 
Interceptor bindings are transitive—an interceptor binding declared by an interceptor binding type is inherited by all beans and other interceptor binding types that declare that interceptor binding type.
```

**Comment by spericas** [comment]
PR #4216
