### ISSUE TITLE
CDI Extension for UCP does not support connection pooling using oracle.ucp.jdbc.PoolXADataSource

### ISSUE THREAD

**Issue by brijeshdeo** [oracle/helidon#4224]
## Environment Details
* Helidon Version: 2.5
* Helidon SE or Helidon MP: Helidon MP
* JDK version: JDK 11
* OS: MacOS Catalina 10.15.7
* Docker version (if applicable):

----------

## Problem Description
[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"
The CDI Extension for Oracle UCP implements the injection of UCP DataSource by creating a PoolDataSource object in the application scope. However this cannot be configured / overridden to create a oracle.ucp.jdbc.PoolXADataSource instead. I can see this behavior when I specify connectionFactoryClassName=oracle.jdbc.xa.client.OracleXADataSource, the PoolDataSouce cannot handle it. Only PoolXADataSource can create a pool using OracleXADataSource. The exception details are given below.
Unless OracleXADataSource is wrapped inside PoolXADataSource instead of PoolDataSource (current implementation) it won't work I think, and I couldn't find a configuration property to set PoolXADataSource. This requirement is for creating XAConnection to an Oracle DB using connection pooling for implementing a distributed transaction. Please provide support for PoolXADataSource - OracleXADataSource combination in the CDI Extension for UCP.

[//]: # "State if the problem is easily reproducible or happens intermittently"
Easily Reproducible

[//]: # "Include stack traces or command outputs"
2022.05.03 20:25:30 INFO org.eclipse.persistence.session./jar:file:/Users/xxxx/git/tmmsamples/xa/java/department-helidon-jpa/target/department-helidon-jpa.jar!/_greeting !thread!: EclipseLink, version: Eclipse Persistence Services - 2.7.9.v20210604-2c549e2208
2022.05.03 20:25:30 INFO org.eclipse.persistence.session./jar:file:/Users/bdeo/git/tmmsamples/xa/java/department-helidon-jpa/target/department-helidon-jpa.jar!/_greeting !thread!: Server: CDISEPlatform
2022.05.03 20:25:30 SEVERE org.eclipse.persistence.session./jar:file:/Users/xxxx/git/tmmsamples/xa/java/department-helidon-jpa/target/department-helidon-jpa.jar!/_greeting !thread!:
Local Exception Stack:
Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.9.v20210604-2c549e2208): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLException: Unable to start the Universal Connection Pool: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLException: Unsupported feature
Error Code: 0
        at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:318)
        at org.eclipse.persistence.sessions.JNDIConnector.connect(JNDIConnector.java:150)
        at org.eclipse.persistence.sessions.DatasourceLogin.connectToDatasource(DatasourceLogin.java:172)
        at org.eclipse.persistence.internal.databaseaccess.DatasourceAccessor.connectInternal(DatasourceAccessor.java:349)
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.connectInternal(DatabaseAccessor.java:316)
        at org.eclipse.persistence.internal.databaseaccess.DatasourceAccessor.connect(DatasourceAccessor.java:438)
        at org.eclipse.persistence.sessions.server.ConnectionPool.buildConnection(ConnectionPool.java:219)
        at org.eclipse.persistence.sessions.server.ExternalConnectionPool.startUp(ExternalConnectionPool.java:148)
        at org.eclipse.persistence.sessions.server.ServerSession.connect(ServerSession.java:522)
        at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.login(DatabaseSessionImpl.java:824)
        at org.eclipse.persistence.internal.jpa.EntityManagerFactoryProvider.login(EntityManagerFactoryProvider.java:263)
        at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:773)
        at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.getAbstractSession(EntityManagerFactoryDelegate.java:222)
        at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.getDatabaseSession(EntityManagerFactoryDelegate.java:200)
        at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.getDatabaseSession(EntityManagerFactoryImpl.java:542)
        at org.eclipse.persistence.jpa.PersistenceProvider.createContainerEntityManagerFactoryImpl(PersistenceProvider.java:388)
        at org.eclipse.persistence.jpa.PersistenceProvider.createContainerEntityManagerFactory(PersistenceProvider.java:316)
        at org.eclipse.persistence.jpa.PersistenceProvider$Proxy$_$$_WeldClientProxy.createContainerEntityManagerFactory(Unknown Source)
        at io.helidon.integrations.cdi.jpa.EntityManagerFactories.createContainerManagedEntityManagerFactory(EntityManagerFactories.java:189)
        at io.helidon.integrations.cdi.jpa.JpaExtension.lambda$addContainerManagedEntityManagerFactoryBeans$1(JpaExtension.java:1104)
        at org.jboss.weld.bootstrap.events.configurator.BeanConfiguratorImpl$CreateCallback.create(BeanConfiguratorImpl.java:368)
        at org.jboss.weld.bootstrap.events.configurator.BeanConfiguratorImpl$CreateCallback.access$700(BeanConfiguratorImpl.java:338)
        at org.jboss.weld.bootstrap.events.configurator.BeanConfiguratorImpl$ImmutableBean.create(BeanConfiguratorImpl.java:503)
        at org.jboss.weld.contexts.AbstractContext.get(AbstractContext.java:96)
        at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:100)
        at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)
        at org.jboss.weld.bean.proxy.ContextBeanInstance.getInstance(ContextBeanInstance.java:102)
        at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:105)
        at org.jboss.weldx.persistence.EntityManagerFactory$$Proxy$_$$_WeldClientProxy.isOpen(Unknown Source)
        at io.helidon.integrations.cdi.jpa.JpaExtension.onStartup(JpaExtension.java:2175)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95)
        at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:85)
        at org.jboss.weld.injection.MethodInvocationStrategy$DefaultMethodInvocationStrategy.invoke(MethodInvocationStrategy.java:144)
        at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:330)
        at org.jboss.weld.event.ExtensionObserverMethodImpl.sendEvent(ExtensionObserverMethodImpl.java:123)
        at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:296)
        at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:286)
        at javax.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:124)
        at org.jboss.weld.util.Observers.notify(Observers.java:166)
        at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:285)
        at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:273)
        at org.jboss.weld.event.EventImpl.fire(EventImpl.java:96)
        at io.helidon.microprofile.cdi.HelidonContainerImpl.doStart(HelidonContainerImpl.java:341)
        at io.helidon.common.context.Contexts.runInContext(Contexts.java:137)
        at io.helidon.microprofile.cdi.HelidonContainerImpl.start(HelidonContainerImpl.java:251)
        at io.helidon.microprofile.cdi.Main.main(Main.java:80) 

## Steps to reproduce
[//]: # "Step by step instructions to reproduce the problem"
[//]: # "Provide sample code/application if relevant"

**Comment by ljnelson** [comment]
Fixed by #4292 (and #4291)
