### ISSUE TITLE
MessageBodyProviderNotFoundException in Minikube

### ISSUE THREAD

**Issue by rgpepersack** [oracle/helidon#4471]
I get MessageBodyProviderNotFoundException when I run my Helidon REST endpoint in Minikube with an Ingress.

## Environment Details
* Helidon Version:  2.3.3
* Helidon MP
* JDK version:  17
* OS:  Ubuntu
* Docker version (if applicable):  20.10.8

----------

## Problem Description
This problem happens every time I try to send a POST request to my REST endpoint running in Minikube using a K8s ingress.  I am sending the POST request from a JUnit test class, which uses the JAX-RS client API to create a WebTarget and the POST request.

When I run Helidon in these scenarios, my REST endpoint works:
* Using the java command
* Running in Docker container
* In Minikube using an external service
 
But, when I create an ingress, instead of the external service, I get a MessageBodyProviderNotFoundException.

org.glassfish.jersey.message.internal.MessageBodyProviderNotFoundException: MessageBodyReader not found for media type=text/html, type=interface javax.json.JsonObject, genericType=interface javax.json.JsonObject.
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:208)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:132)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1072)
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:885)
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:819)
	at org.glassfish.jersey.client.ClientResponse.readEntity(ClientResponse.java:298)
	at org.glassfish.jersey.client.InboundJaxrsResponse$1.call(InboundJaxrsResponse.java:93)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:365)
	at org.glassfish.jersey.client.InboundJaxrsResponse.runInScopeIfPossible(InboundJaxrsResponse.java:244)
	at org.glassfish.jersey.client.InboundJaxrsResponse.readEntity(InboundJaxrsResponse.java:90)
	at com.myapp.resource.MyResourceTest.testMyApp(MyAppTest.java:57)
	... 67 more"

## Steps to reproduce
Run my JUnit test class, which creates a WebTarget and calls the post() method.

**Comment by spericas** [comment]
Media type `text/html` for JSON? That seems wrong. I doubt this is a Helidon issue, maybe the request gets updated in flight? I'm assuming the request content-type is not `text/html` when it works. Please verify the validity of the request.

**Comment by rgpepersack** [comment]
I'm using MediaType.APPLICATION_JSON in the POST request.  I'm also using MediaType.APPLICATION_JSON in the @Consumes and @Produces annotations on my method.
I think that you're right that it may not be Helidon.  It works everywhere, but in Minikube.  I was hoping someone would know why it doesn't work in Minikube.  I can see Helidon start up ok with the kubectl logs command, but nothing is logged after that.

**Comment by danielkec** [comment]
Looks similar https://github.com/kubernetes/ingress-nginx/issues/5265
