### ISSUE TITLE
Proper Helidon MP Bean Validation Configuration

### ISSUE THREAD

**Issue by Ordiel** [oracle/helidon#4573]
## Environment Details
* Helidon Version: 2.5.1
* Helidon MP
* JDK version: 11
* OS: Ubuntu

----------
Accordingly to [this](https://helidon.io/docs/v2/#/mp/beanvalidation/01_overview) page enabling bean validation should be as easy as adding the following dependency to the pom:

```xml
<dependency>
  <groupId>org.glassfish.jersey.ext</groupId>
  <artifactId>jersey-bean-validation</artifactId>
</dependency>
```

By doing so the following exception is thrown on application start up:

```
Exception in thread "main" javax.enterprise.event.ObserverException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at org.jboss.weld.security.NewInstanceAction.run(NewInstanceAction.java:33)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.jboss.weld.injection.Exceptions.rethrowException(Exceptions.java:40)
	at org.jboss.weld.injection.Exceptions.rethrowException(Exceptions.java:78)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:103)
	at org.jboss.weld.injection.MethodInvocationStrategy$SpecialParamPlusBeanManagerStrategy.invoke(MethodInvocationStrategy.java:187)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:330)
	at org.jboss.weld.event.ExtensionObserverMethodImpl.sendEvent(ExtensionObserverMethodImpl.java:123)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:308)
	at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:286)
	at javax.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:124)
	at org.jboss.weld.util.Observers.notify(Observers.java:166)
	at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:285)
	at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:273)
	at org.jboss.weld.event.EventImpl.fire(EventImpl.java:96)
	at io.helidon.microprofile.cdi.HelidonContainerImpl.doStart(HelidonContainerImpl.java:341)
	at io.helidon.common.context.Contexts.runInContext(Contexts.java:137)
	at io.helidon.microprofile.cdi.HelidonContainerImpl.start(HelidonContainerImpl.java:251)
	at io.helidon.microprofile.cdi.Main.main(Main.java:80)
Caused by: java.lang.AbstractMethodError: Receiver class org.glassfish.jersey.server.validation.internal.ValidationAutoDiscoverable does not define or inherit an implementation of the resolved method 'abstract void configure(javax.ws.rs.core.FeatureContext)' of interface org.glassfish.jersey.internal.spi.AutoDiscoverable.
	at org.glassfish.jersey.model.internal.CommonConfig.configureAutoDiscoverableProviders(CommonConfig.java:621)
	at org.glassfish.jersey.server.ResourceConfig.configureAutoDiscoverableProviders(ResourceConfig.java:811)
	at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:326)
	at org.glassfish.jersey.server.ApplicationHandler.lambda$initialize$1(ApplicationHandler.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.processWithException(Errors.java:232)
	at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:296)
	at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:261)
	at io.helidon.webserver.jersey.JerseySupport.<init>(JerseySupport.java:153)
	at io.helidon.webserver.jersey.JerseySupport$Builder.build(JerseySupport.java:515)
	at io.helidon.microprofile.server.JaxRsCdiExtension.toJerseySupport(JaxRsCdiExtension.java:292)
	at io.helidon.microprofile.server.ServerCdiExtension.addApplication(ServerCdiExtension.java:377)
	at io.helidon.microprofile.server.ServerCdiExtension.lambda$registerJaxRsApplications$10(ServerCdiExtension.java:260)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at io.helidon.microprofile.server.ServerCdiExtension.registerJaxRsApplications(ServerCdiExtension.java:260)
	at io.helidon.microprofile.server.ServerCdiExtension.startServer(ServerCdiExtension.java:195)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95)
	... 14 more
```

What is the full set of dependencies needed to configure bean validation on a Helidon MP project?

**Comment by romain-grecourt** [comment]
See https://github.com/oracle/helidon/blob/2.5.1/examples/microprofile/bean-validation/pom.xml

**Comment by Ordiel** [comment]
By doing a maven dependency:tree

```
[INFO] +- io.helidon.microprofile.bean-validation:helidon-microprofile-bean-validation:jar:2.5.1:compile
[INFO] |  +- org.hibernate.validator:hibernate-validator-cdi:jar:6.2.1.Final:compile
[INFO] |  \- org.glassfish:jakarta.el:jar:3.0.4:compile
```
The suggested dependencies (`helidon-microprofile-bean-validation:jar:2.5.1`) are using `hibernate-validator-cdi:jar:6.2.1.Final` which already uses the classes under jakarta's packages, and for what I am noticing this causes issues with the rest of the application, given Helidon 2.5.1 is still being Java EE instead of Jakarta EE

![image](https://user-images.githubusercontent.com/9622612/180031047-39789c6e-748d-4a43-8f37-72afba29f9fe.png)

**Comment by Ordiel** [comment]
Nevermind, issue seam to be me also having: `org.glassfish.javax.el` on the class path

**Comment by romain-grecourt** [comment]
Are you using Helidon's dependency management ?

I.e.

Do you inherit:
- `io.helidon.applications:helidon-se`
-  `io.helidon.applications:helidon-mp`

Or do you import or inherit `io.helidon:helidon-depedencies` ?

**Comment by Ordiel** [comment]
I am inheriting `io.helidon.applications:helidon-mp`
