### ISSUE TITLE
Request to endpoint /metrics fails occasionally

### ISSUE THREAD

**Issue by enbohm** [oracle/helidon#464]
Requests to metrics path ```/metrics``` seems to fail from time to time and reports HTTP status 500. This occurs often when the Helidon application has been idle for a while.

## Environment Details
* Helidon Version: 1.0.0 & 2.2.0
* Helidon MP
* JDK version: 11 (build 11-28)
* OS: Linux
* Docker version: 18.09.02-CE

----------

## Problem Description
I'm using Prometheus (https://prometheus.io/) to gather metrics from various services (scrape configuration is to call ```/metrics``` endpoint twice per minute). Once or twice a day (often when the Helidon MP app has been idle for some time) the endpoint reports HTTP status 500 and an exception occurs which is caused by a NumberFormatException, see below screenshot. However, upcoming requests does work after a while.

![helidon-metrics-stacktrace](https://user-images.githubusercontent.com/4103786/53637893-bb471d80-3c24-11e9-84e0-f84363cb20ec.png)

## Steps to reproduce
Create a simple Helidon service and call ```/metrics``` on regular basic - after a few hours the endpoint reports HTTP status 500. Subsequent request will work but during the failure systems such as Prometheus will report that the service might be down which can cause negative alarms or other notifications.

## Addendum (reopening the issue)
The same general situation (long-running server -- unclear whether it has been idle or just long-running) gives the same symptom but during JSON formatting now.

**Comment by spericas** [comment]
Looks like we may be computing a double whose string representation is "NaN" (not a number) that is later used to instantiate a BigDecimal. Not sure how an "N" could make it there otherwise.

**Comment by tomas-langer** [comment]
division by zero?

**Comment by spericas** [comment]
A division by zero gives you `Infinity`. An example of a `NaN` is `sqrt(-1)`. Looks like `WeightedSnapshot::getMean` is returning `NaN`. I think this can only happen when the values passed to the constructor of `WeightedSnapshot` include `NaN`'s (passed from `ExponentiallyDecayingReservoir`). I'm not really sure how that could happen, however we could defensively check for `Nan`'s and ignore them when part of a snapshot. Any other suggestions?

**Comment by amannm** [comment]
probably the N from an <N> .... cough.... well good luck

**Comment by spericas** [comment]
We've added some special handling for NaN's to prevent the 500 results. Please re-open with additional information if necessary.

**Comment by tjquinno** [comment]
A user is seeing this problem again, but in a slightly different situation. After a server has been running for some time (at least a day, it seems), attempts to retrieve the metrics via the endpoint triggers this problem as JSON attempts to format a NaN value as a `BigDecimal`. 

I am reopening this because we might need to use the same or a similar technique from another place in the code.
```
2021.02.24 10:39:23 WARNING io.helidon.webserver.RequestRouting Thread[nioEventLoopGroup-3-1,10,main]: Default error handler: Unhandled exception encountered.
java.util.concurrent.ExecutionException: Unhandled 'cause' of this exception encountered.
        at io.helidon.webserver.RequestRouting$RoutedRequest.defaultHandler(RequestRouting.java:397)
        at io.helidon.webserver.RequestRouting$RoutedRequest.nextNoCheck(RequestRouting.java:377)
        at io.helidon.webserver.RequestRouting$RoutedRequest.next(RequestRouting.java:325)
        at io.helidon.metrics.MetricsSupport$MetricsContextHandler.accept(MetricsSupport.java:619)
        at io.helidon.webserver.RequestRouting$RoutedRequest.next(RequestRouting.java:323)
        at io.helidon.webserver.cors.RequestAdapterSe.next(RequestAdapterSe.java:62)
        at io.helidon.webserver.cors.CorsSupport.prepareCORSResponseAndContinue(CorsSupport.java:79)
        at io.helidon.webserver.cors.CorsSupport.lambda$accept$0(CorsSupport.java:72)
        at java.base/java.util.Optional.ifPresentOrElse(Optional.java:203)
        at io.helidon.webserver.cors.CorsSupport.accept(CorsSupport.java:72)
        at io.helidon.webserver.RequestRouting$RoutedRequest.next(RequestRouting.java:323)
        at io.helidon.metrics.MetricsSupport.lambda$configureVendorMetrics$7(MetricsSupport.java:364)
        at io.helidon.webserver.RequestRouting$RoutedRequest.next(RequestRouting.java:323)
        at io.helidon.openapi.OpenAPISupport.registerJsonpSupport(OpenAPISupport.java:164)
        at io.helidon.webserver.RequestRouting$RoutedRequest.next(RequestRouting.java:323)
        at io.helidon.webserver.WebTracingConfig$RequestSpanHandler.accept(WebTracingConfig.java:247)
        at io.helidon.webserver.RequestRouting$RoutedRequest.next(RequestRouting.java:323)
        at io.helidon.common.context.Contexts.runInContext(Contexts.java:117)
        at io.helidon.webserver.RequestRouting.route(RequestRouting.java:89)
        at io.helidon.webserver.ForwardingHandler.channelRead0(ForwardingHandler.java:230)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NumberFormatException: Character N is neither a decimal digit number, decimal point, nor "e" notation exponential mark.
        at java.base/java.math.BigDecimal.<init>(BigDecimal.java:518)
        at java.base/java.math.BigDecimal.<init>(BigDecimal.java:401)
        at java.base/java.math.BigDecimal.<init>(BigDecimal.java:834)
        at java.base/java.math.BigDecimal.valueOf(BigDecimal.java:1304)
        at org.glassfish.json.JsonNumberImpl.getJsonNumber(JsonNumberImpl.java:46)
        at org.glassfish.json.JsonObjectBuilderImpl.add(JsonObjectBuilderImpl.java:104)
        at io.helidon.metrics.HelidonTimer.jsonData(HelidonTimer.java:236)
        at io.helidon.metrics.MetricsSupport.lambda$toJsonData$2(MetricsSupport.java:284)
        at java.base/java.util.stream.ReduceOps$4ReducingSink.accept(ReduceOps.java:220)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:589)
        at io.helidon.metrics.MetricsSupport.toJson(MetricsSupport.java:321)
        at io.helidon.metrics.MetricsSupport.toJsonData(MetricsSupport.java:283)
        at io.helidon.metrics.MetricsSupport.accumulateJson(MetricsSupport.java:312)
        at io.helidon.metrics.MetricsSupport.lambda$toJson$5(MetricsSupport.java:305)
        at java.base/java.util.stream.ReduceOps$4ReducingSink.accept(ReduceOps.java:220)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:589)
        at io.helidon.metrics.MetricsSupport.toJson(MetricsSupport.java:304)
        at io.helidon.metrics.MetricsSupport.toJsonData(MetricsSupport.java:279)
        at io.helidon.metrics.MetricsSupport.getMultiple(MetricsSupport.java:471)
        at io.helidon.metrics.MetricsSupport.lambda$configureEndpoint$8(MetricsSupport.java:391)
        at io.helidon.webserver.RequestRouting$RoutedRequest.next(RequestRouting.java:323)
        ... 39 more
```
