### ISSUE TITLE
Helidon OJDBC Connectivity Issue when combined with JBatch

### ISSUE THREAD

**Issue by bvkrish83** [oracle/helidon#4646]
Helidon 3.0 combined with JBatch and OJDBC libraries is resulting in Database connectivity issues.
Built a simple repro combining the JBatch and HikariCP examples provided in Helidon 3.0, and pushed it to GitHub at https://github.com/bvkrish83/helidon-jdbc-issue

Same sample works fine when we change versions to Helidon 2.5.1 and corresponding updates to all dependent libraries.

Repro Steps:
- Update microprofile-config.properties file to point to a valid Oracle database.
- Build the sample repro code provided in above github repo (or) use the already compiled version checked into build-issue folder\libs directory.
- Run the executable using `java -jar .\build\libs\helidon-examples-jbatch_3.0.0.jar`
- Execute curl command `curl -X GET http://localhost:8080/tables`
- Expected Output - Connect to database, and execute the sample SQL and return valid result.
- Actual Output
```
2022.07.31 22:15:42 INFO io.helidon.common.LogConfig Thread[main,5,main]: Logging at initialization configured using classpath: /logging.properties
2022.07.31 22:15:43 INFO io.helidon.microprofile.server.ServerCdiExtension Thread[main,5,main]: Registering JAX-RS Application: HelidonMP
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2022.07.31 22:15:44 INFO io.helidon.webserver.NettyWebServer Thread[nioEventLoopGroup-2-1,10,main]: Channel '@default' started: [id: 0x12001e33, L:/[0:0:0:0:0:0:0:0]:8080]
2022.07.31 22:15:44 INFO io.helidon.microprofile.server.ServerCdiExtension Thread[main,5,main]: Server started on http://localhost:8080 (and all other host addresses) in 1954 milliseconds (since JVM startup).
2022.07.31 22:15:44 INFO io.helidon.common.HelidonFeatures Thread[features-thread,5,main]: Helidon MP 3.0.0 features: [CDI, Config, JAX-RS, Server]
2022.07.31 22:15:59 SEVERE io.helidon.webserver.RequestRouting Thread[helidon-server-1,5,server]: Default error handler: Unhandled exception encountered.
java.util.concurrent.ExecutionException: Unhandled 'cause' of this exception encountered.
        at io.helidon.webserver.RequestRouting$RoutedRequest.defaultHandler(RequestRouting.java:398)
        at io.helidon.webserver.RequestRouting$RoutedRequest.nextNoCheck(RequestRouting.java:379)
        at io.helidon.webserver.RequestRouting$RoutedRequest.next(RequestRouting.java:421)
        at io.helidon.webserver.jersey.ResponseWriter.failure(ResponseWriter.java:141)
        at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:438)
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:263)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684)
        at io.helidon.webserver.jersey.JerseySupport$JerseyHandler.lambda$doAccept$4(JerseySupport.java:326)
        at io.helidon.common.context.Contexts.runInContext(Contexts.java:117)
        at io.helidon.common.context.ContextAwareExecutorImpl.lambda$wrap$7(ContextAwareExecutorImpl.java:154)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ExceptionInInitializerError
        at oracle.jdbc.driver.T4CPreparedStatement.configureRowData(T4CPreparedStatement.java:603)
        at oracle.jdbc.driver.OracleStatement.initStatement(OracleStatement.java:946)
        at oracle.jdbc.driver.OracleStatement.<init>(OracleStatement.java:888)
        at oracle.jdbc.driver.OraclePreparedStatement.<init>(OraclePreparedStatement.java:1122)
        at oracle.jdbc.driver.T4CPreparedStatement.<init>(T4CPreparedStatement.java:65)
        at oracle.jdbc.driver.T4CDriverExtension.allocatePreparedStatement(T4CDriverExtension.java:154)
        at oracle.jdbc.driver.PhysicalConnection.prepareStatementInternal(PhysicalConnection.java:2333)
        at oracle.jdbc.driver.PhysicalConnection.prepareStatement(PhysicalConnection.java:2253)
        at oracle.jdbc.driver.PhysicalConnection.prepareStatement(PhysicalConnection.java:2244)
        at oracle.jdbc.driver.PhysicalConnection.prepareStatement(PhysicalConnection.java:2155)
        at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:327)
        at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java)
        at io.helidon.jbatch.example.TablesResource.get(TablesResource.java:77)
        at io.helidon.jbatch.example.TablesResource$Proxy$_$$_WeldClientProxy.get(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:134)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:177)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:81)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:475)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:397)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255)
        ... 14 more
Caused by: java.lang.NullPointerException: Cannot read field "m_ucsChar" because "<local1>" is null
        at oracle.jdbc.driver.DynamicByteArray$1.run(DynamicByteArray.java:961)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at oracle.jdbc.driver.DynamicByteArray.<clinit>(DynamicByteArray.java:956)
        ... 41 more

Exception in thread "helidon-server-1" java.lang.IllegalStateException: The 'next()' method can be called only once!
        at io.helidon.webserver.RequestRouting$RoutedRequest.checkNexted(RequestRouting.java:339)
        at io.helidon.webserver.RequestRouting$RoutedRequest.checkNexted(RequestRouting.java:334)
        at io.helidon.webserver.RequestRouting$RoutedRequest.next(RequestRouting.java:419)
        at io.helidon.webserver.jersey.JerseySupport$JerseyHandler.lambda$doAccept$4(JerseySupport.java:332)
        at io.helidon.common.context.Contexts.runInContext(Contexts.java:117)
        at io.helidon.common.context.ContextAwareExecutorImpl.lambda$wrap$7(ContextAwareExecutorImpl.java:154)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
2022.07.31 22:16:05 INFO io.helidon.webserver.NettyWebServer Thread[nioEventLoopGroup-2-1,10,main]: Channel '@default' closed: [id: 0x12001e33, L:/[0:0:0:0:0:0:0:0]:8080]
2022.07.31 22:16:05 INFO io.helidon.microprofile.server.ServerCdiExtension Thread[helidon-cdi-shutdown-hook,5,main]: Server stopped in 25 milliseconds.
```

## Environment Details
* Helidon Version: 3.0.0
* Helidon MP
* JDK version: JDK 17.0.4
* OS: Windows 11
* Docker version (if applicable): NA

**Comment by ljnelson** [comment]
I'd like to understand this more. I see a `NullPointerException` in the Oracle driver itself, and I don't see anything in the stack trace that relates to batch jobs, just the manual creation of a statement that fails because the `m_ucsChar` field in the guts of the Oracle driver is `null`.  Is that a correct understanding of the problem? Do you have any theories as to how a Helidon version change could affect this?  Perhaps it is a version change in the OJDBC driver itself instead, and this is really a database driver problem?

**Comment by bvkrish83** [comment]
Yes, this is an error internal to Oralce JDBC driver itself. Strangely, this error shows up only when Helidon 3.0, JBatch Libraries and OJDBC libraries are all packaged as part of the application.

Please note that even though JBatch related libraries, and OJDBC libraries both are packaged as part of this application - BatchResource class alone depends on JBatch related libraries, and TablesResource class alone depends on OJDBC libraries. Curl command being executed triggers to load TablesResource class only - but still the problem repros.

Let me explain in detail, with all version combinations tried:
* Helidon 2.5.1, JBatch 1.0.1 and OJDBC driver 19.3.0.0 versions are used - No issues noticed.
* Helidon 2.5.1, JBatch 1.0.1 and OJDBC driver 21.3.0.0 versions are used (OJDBC version same as the one used in this failure combination) - No issues noticed.
* Helidon 2.5.1, OJDBC driver 19.3.0.0 versions are used - No issues noticed.
* Helidon 2.5.1, OJDBC driver 21.3.0.0 versions are used (OJDBC version same as the one used in this failure combination) - No issues noticed.
* Helidon 3.0.0, OJDBC driver 19.3.0.0 versions are used, with no dependency on JBatch - No issues are noticed.
* Helidon 3.0.0, OJDBC driver 21.3.0.0 versions are used, with no dependency on JBatch - No issues are noticed.
* Helidon 3.0.0, JBatch 2.1.0 and OJDBC driver 19.3.0.0 versions are used - Same JDBC connectivity issue repros.
* Helidon 3.0.0, JBatch 2.1.0 and OJDBC driver 21.3.0.0 versions are used - Same JDBC connectivity issue repros.

After trying out all the above combinations, I have narrowed down that this issue not specific to a library / framework, but it repros only when Helidon 3.0.0, JBatch and OJDBC drivers dependencies are included in application. Hence, the problem doesn;'t repro with either JDBC, JBatch or Helidon 3.0.0 alone or a combination of 2 frameworks or libraries. It repros only when all of Helidon 3.0.0, JBatch and JDBC libraries are packaged as part of the application. Strange.

Steps to not repro this issue:
1. Comment out BatchResource class and all its related dependencies.
2. Build the application.
3. Follow the above steps to start application, and try to repro the issue.
4. Now, the issue doesn't repro - but the connection gets successfully established properly.

**Comment by ljnelson** [comment]
Neither batch nor Helidon "cares" about OJDBC. I wonder if the driver bug is a result of when the connection pool initializes.  In any event, there doesn't appear to be anything we can do here, unless you think otherwise? I would suggest taking this up with the database driver team.

**Comment by bvkrish83** [comment]
@ljnelson Yes, I do understand whatever you mentioned. There seems to be something unusual happening when all these 3 libraries / frameworks are being combined - The issue doesn't repro even if Helidon 3.0 or JBatch dependencies are removed from the repro application.

I have raised an issue, and trying to follow up with OJDBC folks as well.

In simple words, i don't think this is a straight forward issue with a simple fix to resolve the issue. In other words, some changes done in these 3 frameworks / libraries are combinedly triggering this issue to repro. So, all in all, people across multiple teams / frameworks need to take initiative to investigate this issue and suggest a possible resolution of this issue.

**Comment by ljnelson** [comment]
There are seemingly various issues around `DynamicByteArray` and `NullPointerException`s.  Here's an arbitrary one: https://github.com/corda/corda/issues/5728  Here's someone else running into it in an earlier version of the driver, suggesting that `DynamicByteArray` is problematic: https://stackoverflow.com/questions/33381256/has-anyone-seen-this-npe-in-oracle-jdbc-driver  None of these issues has solutions.  Each has a strange combination of contexts (JVMs, libraries, etc.) that combine to expose the underlying flaw.  Hopefully this will help you and the driver team get to the bottom of this.

**Comment by ljnelson** [comment]
I can see from reading the bytecode of the driver that in order to get an instance of a `CharacterConverterJDBC`, which is the class? I think? that has the `m_ucsChar` array in it as an instance field?, the Oracle driver does some `ObjectInputStream` stuff, looking for a file that ends with `.glb`.  From rooting through the `ojdbc8-21.3.0.0.jar` file, I see several `.glb` files.  I note that at least one of them has a reference in it to `m_ucsChar`, suggesting my bytecode reading is at least on the right track.

I also see that `CharacterConverterJDBC`'s `m_ucsChar` array is never initialized in code, so it is always `null`, suggesting that it must be initialized elsewhere, which means that this deserialization mechanism must be loading a `CharacterConverterJDBC` object with a pre-initialized `m_ucsChar` array.  For some reason in your situation this is not happening.

Since using the Oracle driver apparently involves this Java object deserialization in order to load pre-initialized `CharacterConverterJDBC` objects, perhaps [deserialization filtering](https://docs.oracle.com/en/java/javase/17/core/serialization-filtering1.html#GUID-55BABE96-3048-4A9F-A7E6-781790FF3480) is getting in the way.  Just a guess.

**Comment by ljnelson** [comment]
Looks like I'm on the right track: https://github.com/oracle/helidon/blob/29416bd320080e0a3317071cfc5d38e493fc74f7/common/common/src/main/java/io/helidon/common/SerializationConfig.java#L76

**Comment by ljnelson** [comment]
OK, so working theory:

Helidon's deserialization protection is quite rightly rejecting every attempt to deserialize anything by anything.  You have to "opt in" to allow deserialization to happen.

Because deserialization is "off", and because the Oracle driver swallows all errors related to its internal usage of deserialization, the `CharacterConverterJDBC` instance that the driver expects to deserialize comes up uninitialized.  Its instance fields are probably all `null`.

Helidon's deserialization filtering appears in both versions 2.5.1 and 3.0.0.  In the 2.5.1 case, if I'm reading [the javadocs](https://helidon.io/docs/v3/apidocs/io.helidon.common/io/helidon/common/SerializationConfig.html) right, the default behavior is to warn.  My guess is your logging level is not set to include warnings so you don't see anything.  In 3.0.0 however it is set to fail, so I'm somewhat surprised that you're not seeing anything at `SEVERE` level.  On the other hand, as noted, the Oracle driver appears (if I'm reading bytecode right, which is hard!) to swallow all exceptions during the deserialization process without printing anything, so perhaps the error is getting swallowed.

The remedy will probably be, as our javadocs say, to include a system property named `helidon.serialFilter.pattern` that is set to `oracle.sql.converter.*`.  The deserialization patterns can be found [in the JDK's deserialization filtering documentation](https://docs.oracle.com/en/java/javase/17/core/serialization-filtering1.html#GUID-91735293-E38E-4A81-85DC-719AFEB36026).

Another thing I noticed was in our [Helidon 3.0.0 documentation](https://helidon.io/docs/v3/#/about/introduction), if you click on the search icon and type "serial" into the box, you can see that we have documentation on all this, but clicking on the search result doesn't find it.  That's a bug in our documentation site.

**Comment by bvkrish83** [comment]
@ljnelson Great, Thanks for the really detailed analysis in such short period of time. Your help is greatly appreciated. 👍 

Yes, this fixed the issue. Once i have added `pattern=oracle.sql.converter.*` in serial-config.properties, I am able to successfully connect to the OJDBC SQL Database and verify the sanity of application.

It would help users, if database connectivity examples included in Helidon Examples, included this line in serial-config.properties file to guide them that this property is related and required for these example scenarios to work properly.

**Comment by ljnelson** [comment]
In fairness, we test our examples, and have not triggered this behavior yet. My guess is that you have to do something Unicode-related that for whatever reason our examples do not trigger to see this issue. Nevertheless yes, I think this is a setting we need to document at the very least. With your permission I'll close this issue as fixed.
