### ISSUE TITLE
Intermittent test failures in webserver

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#472]
Webserver is failing the build pipeline from time to time with the following error:
```
Results :

Failed tests: 
  NettyWebServerTest.testManyPortsButTwoTheSame:243->assertStartFailure:256 Shutdown future not as expected: java.util.concurrent.CompletableFuture@6e8a9c30[Not completed]
Expected: is <true>
     but: was <false>

Tests run: 218, Failures: 1, Errors: 0, Skipped: 11
```

**Comment by barchetta** [comment]
I saw a similar failure (slightly different test) on 28-Feb-2019:
```
Tests run: 7, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.536 sec <<< FAILURE! - in io.helidon.webserver.NettyWebServerTest
testMultiplePortsAllTheSame  Time elapsed: 0.101 sec  <<< FAILURE!
java.lang.AssertionError:
Shutdown future not as expected: java.util.concurrent.CompletableFuture@53b1a3f8[Not completed]
Expected: is <true>
     but: was <false>
    at io.helidon.webserver.NettyWebServerTest.assertStartFailure(NettyWebServerTest.java:256)
    at io.helidon.webserver.NettyWebServerTest.testMultiplePortsAllTheSame(NettyWebServerTest.java:226) 
```

**Comment by spericas** [comment]
There are so many `Future`'s in this code, the interaction between them is certainly not trivial. There could be some race condition causing the web server start future to accidentally complete, possibly by this condition becoming true:

```
     if (channels.size() >= bootstrapsSize) {
         LOGGER.finer(() -> "All channels started: " + channels.size());
         channelsUpFuture.complete(this);
      }
```
