### ISSUE TITLE
Error on server startup using jaeger udp protocol

### ISSUE THREAD

**Issue by bogedal** [oracle/helidon#4734]
## Environment Details
* Helidon Version: 3.0.0
* Helidon MP
* JDK version: 17
* OS: windows 10
* Docker version (if applicable):

----------
Jaeger tracing issue after upgrade from Helidon 2.5.0

With the service I run a jaeger sidecar in an openshift environement,
I send jaeger tracing to this sidecar using the udp protocol.

However when using the same configuration in Helidon 3.0.0 i get an error from opentelemetry that I need to use http or https.
This validation is started io/helidon/tracing/jaeger/JaegerTracerBuilder.java on line 396.
Namely the setEndpoint invocation.

To continue to use the udp protocol am I missing a configuration somewhere or ?

## Tracing configuration is done partly using environment variables
TRACING_ENABLED = true
TRACING_PROTOCOL = udp
TRACING_HOST = localhost
TRACING_PORT = 6831

## microprofile-config.properties 
tracing.service = some-service-name
tracing.sampler-type = ratio
tracing.sampler-param = 1.0

## Gradle import section of the service
    implementation platform("io.helidon:helidon-dependencies:${project['io.helidon.version']}")
    implementation 'io.helidon.microprofile.bundles:helidon-microprofile-core'
    implementation 'io.helidon.microprofile.health:helidon-microprofile-health'
    implementation 'io.helidon.microprofile.metrics:helidon-microprofile-metrics'
    implementation 'io.helidon.microprofile.tracing:helidon-microprofile-tracing'
    implementation 'io.helidon.tracing:helidon-tracing-jaeger'
    implementation 'io.helidon.microprofile:helidon-microprofile-fault-tolerance'

## Stacktrace
Exception in thread "main" java.lang.IllegalArgumentException: Invalid endpoint, must start with http:// or https://: udp://localhost:6831
at io.opentelemetry.exporter.internal.ExporterBuilderUtil.validateEndpoint(ExporterBuilderUtil.java:30)
at io.opentelemetry.exporter.internal.grpc.OkHttpGrpcExporterBuilder.setEndpoint(OkHttpGrpcExporterBuilder.java:85)
at io.opentelemetry.exporter.internal.grpc.OkHttpGrpcExporterBuilder.setEndpoint(OkHttpGrpcExporterBuilder.java:35)
at io.opentelemetry.exporter.jaeger.JaegerGrpcSpanExporterBuilder.setEndpoint(JaegerGrpcSpanExporterBuilder.java:66)
at io.helidon.tracing.jaeger.JaegerTracerBuilder.build(JaegerTracerBuilder.java:397)
at io.helidon.tracing.jaeger.JaegerTracerBuilder.build(JaegerTracerBuilder.java:141)
at io.helidon.microprofile.tracing.TracingCdiExtension.prepareTracer(TracingCdiExtension.java:74)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95)
at org.jboss.weld.injection.MethodInvocationStrategy$SpecialParamPlusBeanManagerStrategy.invoke(MethodInvocationStrategy.java:187)
at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:330)
at org.jboss.weld.event.ExtensionObserverMethodImpl.sendEvent(ExtensionObserverMethodImpl.java:123)
at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:308)
at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:286)
at jakarta.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:125)
at org.jboss.weld.util.Observers.notify(Observers.java:166)
at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:285)
at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:273)
at org.jboss.weld.event.EventImpl.fire(EventImpl.java:96)
at io.helidon.microprofile.cdi.HelidonContainerImpl.doStart(HelidonContainerImpl.java:340)
at io.helidon.common.context.Contexts.runInContext(Contexts.java:137)
at io.helidon.microprofile.cdi.HelidonContainerImpl.start(HelidonContainerImpl.java:250)
at io.helidon.microprofile.server.ServerImpl.start(ServerImpl.java:76)
...
About to shutdown.

**Comment by bogedal** [comment]
added a simple sample project for ease of reproduction :
[jaeger-issue-example.zip](https://github.com/oracle/helidon/files/9350613/jaeger-issue-example.zip)
)

**Comment by tomas-langer** [comment]
The current implementation on top of Open Telemetry only supports gRPC span exporter, which is HTTP based.
I will look into this if Jaeger still supports UDP and how to configure it.

**Comment by tomas-langer** [comment]
As far as I was able to find out, the gRPC exporter is the current recommended solution and there is no UDP Thrift exporter available for Open Telemetry.

**Comment by bogedal** [comment]
@tomas-langer 

This is also my finding sadly.

Guess the best way to solve this is by replacing the jaeger-agent sidecar with an opentelemetry-collector sidecar, which can then send data to our main jaeger instance as jaeger version 1.35+ can consume otel packages.

Found this drawing that shows another way to do it, but you have to use the SDK
![IMG_0120](https://user-images.githubusercontent.com/42640385/188795401-09730179-de81-43db-af01-5869b1dd304c.jpg)

**Comment by tomas-langer** [comment]
I am closing this issue, as I have provided information why it is done this way and how to work around the problem.
