### ISSUE TITLE
uber jar start failed when using gradle shadow plugin

### ISSUE THREAD

**Issue by lost4git** [oracle/helidon#4755]
### Uber jar start error log
```
INFO: Logging at initialization configured using defaults
2022-08-19 04:21:10.231 [main]
        INFO  org.jboss.weld.Version - WELD-000900: 4.0.2 (Final)
2022-08-19 04:21:10.503 [main]
        INFO  org.jboss.weld.Bootstrap - WELD-ENV-000020: Using jandex for bean discovery
2022-08-19 04:21:11.612 [main]
        INFO  org.jboss.weld.Bootstrap - WELD-000101: Transactional services not available. Injection of @Inject UserTransaction not available. Transactional observers will be invoked synchronously.
8�� 19, 2022 4:21:11 ���� io.helidon.microprofile.server.ServerCdiExtension addApplication
INFO: Registering JAX-RS Application: HelidonMP
2022-08-19 04:21:12.062 [main]
        INFO  org.jboss.weld.Bootstrap - WELD-ENV-002001: Weld SE container 0859b0f7-cf72-4304-9aaf-2e1d77eef362 shut down
Exception in thread "main" org.jboss.weld.exceptions.IllegalArgumentException: WELD-001325: No instance of an extension class org.glassfish.jersey.ext.cdi1x.internal.CdiComponentProvider registered with the deployment
        at org.jboss.weld.manager.BeanManagerImpl.getExtension(BeanManagerImpl.java:1445)
        at org.jboss.weld.util.ForwardingBeanManager.getExtension(ForwardingBeanManager.java:239)
        at org.glassfish.jersey.ext.cdi1x.internal.CdiServerComponentProvider.initialize(CdiServerComponentProvider.java:38)
        at org.glassfish.jersey.server.ComponentProviderConfigurator.lambda$null$0(ComponentProviderConfigurator.java:55)
        at java.base/java.util.stream.ReferencePipeline$15$1.accept(ReferencePipeline.java:540)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at org.glassfish.jersey.server.ComponentProviderConfigurator.lambda$init$1(ComponentProviderConfigurator.java:56)
        at org.glassfish.jersey.internal.util.collection.Values$LazyValueImpl.get(Values.java:317)
        at org.glassfish.jersey.server.ExternalRequestScopeConfigurator.init(ExternalRequestScopeConfigurator.java:50)
        at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:340)
        at org.glassfish.jersey.server.ApplicationHandler.lambda$initialize$1(ApplicationHandler.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
        at org.glassfish.jersey.internal.Errors.processWithException(Errors.java:232)
        at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:296)
        at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:261)
        at io.helidon.webserver.jersey.JerseySupport.<init>(JerseySupport.java:152)
        at io.helidon.webserver.jersey.JerseySupport$Builder.build(JerseySupport.java:514)
        at io.helidon.microprofile.server.JaxRsCdiExtension.toJerseySupport(JaxRsCdiExtension.java:283)
        at io.helidon.microprofile.server.ServerCdiExtension.addApplication(ServerCdiExtension.java:376)
        at io.helidon.microprofile.server.ServerCdiExtension.lambda$registerJaxRsApplications$10(ServerCdiExtension.java:259)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at io.helidon.microprofile.server.ServerCdiExtension.registerJaxRsApplications(ServerCdiExtension.java:259)
        at io.helidon.microprofile.server.ServerCdiExtension.startServer(ServerCdiExtension.java:194)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95)
        at org.jboss.weld.injection.MethodInvocationStrategy$SpecialParamPlusBeanManagerStrategy.invoke(MethodInvocationStrategy.java:187)
        at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:330)
        at org.jboss.weld.event.ExtensionObserverMethodImpl.sendEvent(ExtensionObserverMethodImpl.java:123)
        at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:308)
        at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:286)
        at jakarta.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:125)
        at org.jboss.weld.util.Observers.notify(Observers.java:166)
        at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:285)
        at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:273)
        at org.jboss.weld.event.EventImpl.fire(EventImpl.java:96)
        at io.helidon.microprofile.cdi.HelidonContainerImpl.doStart(HelidonContainerImpl.java:340)
        at io.helidon.common.context.Contexts.runInContext(Contexts.java:137)
        at io.helidon.microprofile.cdi.HelidonContainerImpl.start(HelidonContainerImpl.java:250)
        at io.helidon.microprofile.cdi.Main.main(Main.java:80)
```

#### jar!/
![image](https://user-images.githubusercontent.com/65008815/185490223-0be349b3-1430-49b3-984d-c301ccf313ba.png)
#### jar!/META-INF
![image](https://user-images.githubusercontent.com/65008815/185487934-20517249-0134-4214-b0db-4ff3922657fd.png)

### build.gradle
```gradle
plugins {
  id("application")
  alias(libs.plugins.shadow)
  alias(libs.plugins.jandex)
}

dependencies {
  runtimeOnly(libs.logback)
  implementation(projects.common)
  implementation(platform(libs.helidon))
  implementation("io.helidon.microprofile.bundles:helidon-microprofile-core")
  runtimeOnly("org.glassfish.jersey.media:jersey-media-json-jackson")
  runtimeOnly("io.helidon.logging:helidon-logging-slf4j")
  runtimeOnly("org.slf4j:jul-to-slf4j")
  runtimeOnly("org.jboss:jandex")
  runtimeOnly("jakarta.activation:jakarta.activation-api")
}

ext {
  mainClass = "io.helidon.microprofile.cdi.Main"
}

application {
  mainClass = "${project.mainClass}"
}

task moveBeansXML {
  doLast {
    ant.move file: "${buildDir}/resources/main/META-INF/beans.xml",
      todir: "${buildDir}/classes/java/main/META-INF"
  }
}

test.dependsOn moveBeansXML
run.dependsOn moveBeansXML

```

### gradle build pipeline
![image](https://user-images.githubusercontent.com/65008815/185491311-040787dc-1cce-44bb-a5ce-c2c804d98781.png)

**Comment by romain-grecourt** [comment]
Using a single JAR goes against the concept of CDI bean archives. You may be able to make it work, you'd have to make sure that all META-INF/services files are merged. You may also have to merge or hand-craft META-INF/beans.xml.

The Helidon team does not support nor recommend uber jars.
Unless you identify a bug explicitly there is nothing we can do about this.

**Comment by lost4git** [comment]
https://github.com/johnrengelman/shadow/issues/304
