### ISSUE TITLE
StatusTest.checkCounters intermittently fails

### ISSUE THREAD

**Issue by barchetta** [oracle/helidon#4790]
## Environment Details
* Helidon Version: 2.5.3-SNAPSHOT, 4.0.0-SNAPSHOT

----------

## Problem Description

I have seen this intermittently fail on the pipeline:

```
java.lang.AssertionError: 
Diff in counter 4xx
Expected: is <1L>
     but: was <0L>
	at io.helidon.examples.se.httpstatuscount.StatusTest.checkCounters(StatusTest.java:125)
	at io.helidon.examples.se.httpstatuscount.StatusTest.checkAfterStatus(StatusTest.java:118)
	at io.helidon.examples.se.httpstatuscount.StatusTest.checkStatusMetrics(StatusTest.java:88)
```

**Comment by tomas-langer** [comment]
There is a race condition:
- the `HttpStatusMetricService` is using `whenSent()` to increase the metric.
- `whenSent()` is invoked after the message was written to the client
- sometimes the metric is increased after the client obtains a response
