### ISSUE TITLE
Graal: Healthchecks

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#485]
Healthcheck support

**Comment by tomas-langer** [comment]
Getting the following exception when compiling svm:
```
[helidon-examples-graalvm-native-image-full:89135]     analysis:  17,554.60 ms
Error: Error loading service implementations for service `org.eclipse.microprofile.health.spi.HealthCheckResponseProvider` from URL `jar:file:/Users/tomas/dev/helidon/graal/native-image-example/target/helidon-examples-graalvm-native-image-full.jar!/META-INF/services/org.eclipse.microprofile.health.spi.HealthCheckResponseProvider`
Caused by: java.io.FileNotFoundException: JAR entry META-INF/services/org.eclipse.microprofile.health.spi.HealthCheckResponseProvider not found in /Users/tomas/dev/helidon/graal/native-image-example/target/helidon-examples-graalvm-native-image-full.jar
        at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:144)
        at sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:152)
        at java.net.URL.openStream(URL.java:1045)
        at com.oracle.svm.hosted.ServiceLoaderFeature.parseServiceResource(ServiceLoaderFeature.java:248)
        at com.oracle.svm.hosted.ServiceLoaderFeature.handleType(ServiceLoaderFeature.java:165)
        ... 11 more

```

**Comment by tomas-langer** [comment]
When I try the same URL from a java program, it resolves correctly. Requires investigation.

**Comment by tomas-langer** [comment]
Disk space health check has to be removed due to:
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: sun.nio.fs.BsdNativeDispatcher.getfsstat()J [symbol: Java_sun_nio_fs_BsdNativeDispatcher_getfsstat or Java_sun_nio_fs_BsdNativeDispatcher_getfsstat__]
        at com.oracle.svm.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:145)
        at com.oracle.svm.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:54)
        at sun.nio.fs.BsdNativeDispatcher.getfsstat(BsdNativeDispatcher.java)
        at sun.nio.fs.BsdFileSystem.getMountEntries(BsdFileSystem.java:79)
        at sun.nio.fs.BsdFileStore.findMountEntry(BsdFileStore.java:81)
        at sun.nio.fs.UnixFileStore.<init>(UnixFileStore.java:65)
        at sun.nio.fs.BsdFileStore.<init>(BsdFileStore.java:40)
        at sun.nio.fs.BsdFileSystemProvider.getFileStore(BsdFileSystemProvider.java:46)
        at sun.nio.fs.BsdFileSystemProvider.getFileStore(BsdFileSystemProvider.java:34)
        at sun.nio.fs.UnixFileSystemProvider.getFileStore(UnixFileSystemProvider.java:368)
        at java.nio.file.Files.getFileStore(Files.java:1461)
        at io.helidon.health.checks.DiskSpaceHealthCheck.<init>(DiskSpaceHealthCheck.java:114)

```

**Comment by tomas-langer** [comment]
The problem with loading META-INF resolved automagically - maybe related to proxy?

**Comment by tomas-langer** [comment]
Other built-in healthchecks fail with:
```
com.oracle.svm.core.jdk.UnsupportedFeatureError: ThreadMXBean methods
        at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:109)
        at com.oracle.svm.core.jdk.SubstrateThreadMXBean.findDeadlockedThreads(JavaManagementSubstitutions.java:495)
        at io.helidon.health.checks.DeadlockHealthCheck.call(DeadlockHealthCheck.java:62)

```
