### ISSUE TITLE
Graal: Security

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#490]
Integration with security
 - web server integration
 - basic authentication
 - RBAC

**Comment by tomas-langer** [comment]
Same issue as with healthchecks, need to resolve

**Comment by tomas-langer** [comment]
There is a problem when we call `toString()` on `Subject` class:
```
Caused by: com.oracle.svm.core.jdk.UnsupportedFeatureError: Resource bundle not found sun.security.util.Resources. Register the resource bundle using the option -H:IncludeResourceBundles=sun.security.util.Resources.
        at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:109)
        at com.oracle.svm.core.jdk.LocalizationSupport.getCached(LocalizationSupport.java:103)
        at java.util.ResourceBundle.getBundle(ResourceBundle.java:49)
        at sun.security.util.ResourcesMgr$1.run(ResourcesMgr.java:47)
        at sun.security.util.ResourcesMgr$1.run(ResourcesMgr.java:44)
        at java.security.AccessController.doPrivileged(AccessController.java:62)
        at sun.security.util.ResourcesMgr.getString(ResourcesMgr.java:43)
        at javax.security.auth.Subject.toString(Subject.java:853)
        at javax.security.auth.Subject.toString(Subject.java:843)
        at io.helidon.security.Subject.toString(Subject.java:226)
        at java.util.Formatter$FormatSpecifier.printString(Formatter.java:2886)
        at java.util.Formatter$FormatSpecifier.print(Formatter.java:2763)
        at java.util.Formatter.format(Formatter.java:2520)
        at java.util.Formatter.format(Formatter.java:2455)
        at java.lang.String.format(String.java:2940)
        at java.util.Optional.toString(Optional.java:346)
        at java.util.Formatter$FormatSpecifier.printString(Formatter.java:2886)
        at java.util.Formatter$FormatSpecifier.print(Formatter.java:2763)
        at java.util.Formatter.format(Formatter.java:2520)
        at java.util.Formatter.format(Formatter.java:2455)
        at java.lang.String.format(String.java:2940)
        at io.helidon.security.DefaultAuditProvider.formatMessage(DefaultAuditProvider.java:109)
```

**Comment by tomas-langer** [comment]
Trying to resolve with `NATIVE_IMAGE_OPTIONS="${NATIVE_IMAGE_OPTIONS}  -H:IncludeResourceBundles=sun.security.util.Resources"`
Maybe we should modify the method in our `Subject` class not to depend on the java `Subject` to generate the string representation
