### ISSUE TITLE
Graal: Tracing

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#493]
Graal integration using zipkin tracer

**Comment by tomas-langer** [comment]
When run with tracing, the following exception occurs:
```
Exception in thread "main" com.oracle.svm.core.jdk.UnsupportedFeatureError: Accessing an URL protocol that was not enabled. The URL protocol http is supported but not enabled by default. It must be enabled by adding the --enable-url-protocols=http option to the native-image command.
        at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:109)
        at com.oracle.svm.core.jdk.JavaNetSubstitutions.unsupported(JavaNetSubstitutions.java:164)
        at com.oracle.svm.core.jdk.JavaNetSubstitutions.getURLStreamHandler(JavaNetSubstitutions.java:151)
        at java.net.URL.getURLStreamHandler(URL.java:60)
        at java.net.URL.<init>(URL.java:599)
        at java.net.URL.<init>(URL.java:490)
        at java.net.URL.<init>(URL.java:439)
        at java.net.URI.toURL(URI.java:1089)
        at io.helidon.tracing.zipkin.ZipkinTracerBuilder.createSender(ZipkinTracerBuilder.java:372)
        at io.helidon.tracing.zipkin.ZipkinTracerBuilder.build(ZipkinTracerBuilder.java:286)
        at io.helidon.tracing.zipkin.ZipkinTracerBuilder.build(ZipkinTracerBuilder.java:108)
        at io.helidon.tracing.TracerBuilder.buildAndRegister(TracerBuilder.java:268)
        at io.helidon.examples.graalvm.GraalVMNativeImageMain.main(GraalVMNativeImageMain.java:94)

```

**Comment by tomas-langer** [comment]
Mitigated by adding `NATIVE_IMAGE_OPTIONS="${NATIVE_IMAGE_OPTIONS} --enable-url-protocols=http"` to build script
