### ISSUE TITLE
Using meta-config for git appears not to be working

### ISSUE THREAD

**Issue by gcameo** [oracle/helidon#500]
## Environment Details
* Helidon Version: 1.0.0
* Helidon SE
* JDK version: 1.8
* OS: Mac/Unix
* Docker version (if applicable):

----------

## Problem Description
I tried using the git config source to build configuration for my Helidon app.
The following works 

`Config config = Config.create(
                GitConfigSourceBuilder.create("application.conf")
                        .uri(URI.create("https://github.com/helidonrobot/test-config.git"))
                        .branch("test")
                        .build());`

but a similar setup using the meta-config approach throws the exception below

## Steps to reproduce

`Config config = Config.loadSourcesFrom(classpath("dev-config-meta-git.yaml"));`

With the following meta-config

> sources:
    - type: "git"                                            
      properties:
          path: "application.conf"                           
          uri: "https://github.com/helidonrobot/test-config.git"                             
          branch: "test" 

The following exception is thrown

> Exception in thread "main" io.helidon.config.ConfigMappingException: Mapping of value stored under key 'sources.0.properties' to type 'class io.helidon.config.git.GitConfigSource' has failed: No mapper configured
	at io.helidon.config.ConfigMapperManager$NoMapperFound.apply(ConfigMapperManager.java:345)
	at io.helidon.config.ConfigMapperManager$NoMapperFound.apply(ConfigMapperManager.java:336)
	at io.helidon.config.ConfigMapperManager.map(ConfigMapperManager.java:71)
	at io.helidon.config.ConfigMapperManager.map(ConfigMapperManager.java:64)
	at io.helidon.config.ConfigValues.lambda$create$0(ConfigValues.java:130)
	at io.helidon.config.ConfigValues$GenericConfigValueImpl.asOptional(ConfigValues.java:228)
	at io.helidon.config.ConfigValue.get(ConfigValue.java:108)
	at io.helidon.config.spi.ConfigSourceConfigMapper.custom(ConfigSourceConfigMapper.java:155)
	at io.helidon.config.spi.ConfigSourceConfigMapper.lambda$providers$5(ConfigSourceConfigMapper.java:151)
	at java.util.Optional.flatMap(Optional.java:241)
	at io.helidon.config.spi.ConfigSourceConfigMapper.providers(ConfigSourceConfigMapper.java:151)
	at io.helidon.config.spi.ConfigSourceConfigMapper.lambda$apply$0(ConfigSourceConfigMapper.java:107)
	at io.helidon.common.OptionalHelper.or(OptionalHelper.java:71)
	at io.helidon.config.spi.ConfigSourceConfigMapper.lambda$apply$1(ConfigSourceConfigMapper.java:107)
	at java.util.Optional.flatMap(Optional.java:241)
	at io.helidon.config.ConfigValue.flatMap(ConfigValue.java:291)
	at io.helidon.config.spi.ConfigSourceConfigMapper.apply(ConfigSourceConfigMapper.java:105)
	at io.helidon.config.spi.ConfigSource.create(ConfigSource.java:243)
	at io.helidon.config.ConfigValues.lambda$create$4(ConfigValues.java:146)
	at io.helidon.config.ConfigValues$GenericConfigValueImpl.asOptional(ConfigValues.java:228)
	at io.helidon.config.ConfigValue.get(ConfigValue.java:108)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1380)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at io.helidon.config.ConfigSources.load(ConfigSources.java:382)
	at io.helidon.config.ConfigSources.load(ConfigSources.java:342)
	at io.helidon.config.Config.builderLoadSourcesFrom(Config.java:460)
	at io.helidon.config.Config.loadSourcesFrom(Config.java:408)
	at uk.co.senapt.crm.evxcen.website.Main.buildConfig(Main.java:138)
	at uk.co.senapt.crm.evxcen.website.Main.startServer(Main.java:61)
	at uk.co.senapt.crm.evxcen.website.Main.main(Main.java:44)

[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"
[//]: # "State if the problem is easily reproducible or happens intermittently"
[//]: # "Include stack traces or command outputs"

**Comment by tomas-langer** [comment]
Please include the following dependency:
`io.helidon.config:helidon-config-object-mapping`

By default reflection is not supported in Helidon. You need to add this library to support automated mapping to POJOs (that is used by the meta configuration).

**Comment by gcameo** [comment]
Thanks. Will test this and confirm soon.

Regards

**Comment by gcameo** [comment]
Fantastic. Works like charm. Thanks
