### ISSUE TITLE
MpcSourceEnvironmentVariablesTest::testPrecedence fails on Windows

### ISSUE THREAD

**Issue by Verdent** [oracle/helidon#636]
When you run following test MpcSourceEnvironmentVariablesTest::testPrecedence on Windows, it fails because of the value bound to the key "com.acme.size" was found in the config.
```
org.opentest4j.AssertionFailedError: Expected java.util.NoSuchElementException to be thrown, but nothing was thrown.
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:70)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:38)
	at org.junit.jupiter.api.Assertions.assertThrows(Assertions.java:1155)
	at io.helidon.microprofile.config.MpcSourceEnvironmentVariablesTest.assertNoValue(MpcSourceEnvironmentVariablesTest.java:155)
	at io.helidon.microprofile.config.MpcSourceEnvironmentVariablesTest.testPrecedence(MpcSourceEnvironmentVariablesTest.java:125)
.....
```

**Comment by batsatt** [comment]
@Verdent Does the test pass if you comment out lines 125 and 145? It is going to take me awhile to setup an env to reproduce this; I have a fix if those are the only assertions that fail on windows.

**Comment by batsatt** [comment]
I was able to setup a VirtualBox env; reproduced and verified fix.
