### ISSUE TITLE
Empty request body fails with Jackson + Jersey?

### ISSUE THREAD

**Issue by dbazile** [oracle/helidon#772]
Not sure if I've got something misconfigured, but I'm seeing GET requests to Jersey endpoints fail with the following exception:

```
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (byte[])""; line: 1, column: 0]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4145)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4000)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3091)
	at io.helidon.media.jackson.common.JacksonProcessing.lambda$reader$0(JacksonProcessing.java:60)
	... 28 more
```

Stepping through the execution flow, it looks like every request passes the request body to ObjectMapper ([JacksonProcessing.java:60](https://github.com/oracle/helidon/blob/release-1.1.1/media/jackson/common/src/main/java/io/helidon/media/jackson/common/JacksonProcessing.java#L60)), which is an empty byte array for requests without a body.  Seems to do the same if I swap `helidon-media-jackson-server` for `helidon-media-jsonb-server`.

Is anyone else seeing this?

## Environment Details

    Helidon Version:           1.1.1
    Helidon SE or Helidon MP:  neither
    JDK version:               OpenJDK 1.8.0_212-b04
    OS:                        CentOS 7.6

### Server console output including full stacktrace

```
[DEBUG] (main) Using Console logging
Jun 11, 2019 12:04:42 PM io.helidon.webserver.NettyWebServer <init>
INFO: Version: 1.1.1
Jun 11, 2019 12:04:43 PM io.helidon.webserver.NettyWebServer lambda$start$8
INFO: Channel '@default' started: [id: 0x593ceff6, L:/127.0.0.1:5000]
Listening /127.0.0.1:5000
Jun 11, 2019 12:04:45 PM io.helidon.webserver.RequestRouting$RoutedRequest defaultHandler
WARNING: Default error handler: Unhandled exception encountered.
java.util.concurrent.ExecutionException: Unhandled 'cause' of this exception encountered.
        at io.helidon.webserver.RequestRouting$RoutedRequest.defaultHandler(RequestRouting.java:414)
        at io.helidon.webserver.RequestRouting$RoutedRequest.nextNoCheck(RequestRouting.java:403)
        at io.helidon.webserver.RequestRouting$RoutedRequest.next(RequestRouting.java:436)
        at io.helidon.webserver.jersey.JerseySupport$JerseyHandler.lambda$accept$3(JerseySupport.java:267)
        at java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:870)
        at java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:852)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
        at io.helidon.media.common.ContentReaders$1.onComplete(ContentReaders.java:135)
        at io.helidon.webserver.OriginThreadPublisher.complete(OriginThreadPublisher.java:266)
        at io.helidon.webserver.ForwardingHandler.channelRead0(ForwardingHandler.java:161)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.CompletionException: io.helidon.media.jackson.common.JacksonRuntimeException: No content to map due to end-of-input
 at [Source: (byte[])""; line: 1, column: 0]
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
        ... 26 more
Caused by: io.helidon.media.jackson.common.JacksonRuntimeException: No content to map due to end-of-input
 at [Source: (byte[])""; line: 1, column: 0]
        at io.helidon.media.jackson.common.JacksonProcessing.lambda$reader$0(JacksonProcessing.java:62)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
        ... 27 more
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (byte[])""; line: 1, column: 0]
        at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4145)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4000)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3091)
        at io.helidon.media.jackson.common.JacksonProcessing.lambda$reader$0(JacksonProcessing.java:60)
        ... 28 more
```

## Steps to reproduce

Create a barebones WebServer with JAX-RS and Jackson support and curl against some endpoint.

### curl commands and output

```
$ curl -v 127.0.0.1:5000

* About to connect() to 127.0.0.1 port 5000 (#0)
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 5000 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 127.0.0.1:5000
> Accept: */*
> 
< HTTP/1.1 500 Internal Server Error
< Date: Tue, 11 Jun 2019 12:03:18 -0400
< transfer-encoding: chunked
< connection: keep-alive
< 
* Connection #0 to host 127.0.0.1 left intact

$ curl -v 127.0.0.1:5000 -XGET -d null -Hcontent-type:application/json

* About to connect() to 127.0.0.1 port 5000 (#0)
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 5000 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 127.0.0.1:5000
> Accept: */*
> content-type:application/json
> Content-Length: 4
> 
* upload completely sent off: 4 out of 4 bytes
< HTTP/1.1 200 OK
< Content-Type: application/json
< Date: Tue, 11 Jun 2019 12:03:21 -0400
< transfer-encoding: chunked
< connection: keep-alive
< 
* Connection #0 to host 127.0.0.1 left intact
{"nano":759000000,"epochSecond":1560269001}
```

### `build.gradle`

```gradle
plugins {
    id 'java'
    id 'application'
}

group   = 'foo'

mainClassName = 'foo.Main'

sourceCompatibility = 1.8

dependencies {
    compile 'io.helidon:helidon-bom:1.1.1'
    compile 'io.helidon.webserver:helidon-webserver:1.1.1'
    compile 'io.helidon.webserver:helidon-webserver-jersey:1.1.1'
    compile 'io.helidon.media.jackson:helidon-media-jackson-server:1.1.1'

    compile 'org.glassfish.jersey.media:jersey-media-json-jackson:2.26'
}

repositories {
    mavenCentral()
}
```

### `src/main/java/foo/Main.java`

```java
package foo;

import java.net.InetAddress;
import java.time.Instant;
import java.util.concurrent.TimeUnit;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;

import io.helidon.media.jackson.server.JacksonSupport;
import io.helidon.webserver.Routing;
import io.helidon.webserver.ServerConfiguration;
import io.helidon.webserver.WebServer;
import io.helidon.webserver.jersey.JerseySupport;

public final class Main {
    @Path("/")
    public static class FooResource {
        @GET
        @Produces("application/json")
        public Instant asJson() {
            return Instant.now();
        }
    }

    public static void main(String[] args) throws Exception {
        final WebServer server = WebServer.create(
                ServerConfiguration.builder()
                        .bindAddress(InetAddress.getByName("127.0.0.1"))
                        .port(5000)
                        .build(),
                Routing.builder()
                        .register(JacksonSupport.create())
                        .register(
                                JerseySupport.builder()
                                        .register(FooResource.class)
                                        .build())
                        .build()
        )
                .start()
                .toCompletableFuture()
                .get(10, TimeUnit.SECONDS);

        System.out.printf("Listening %s:%d\n", server.configuration().bindAddress(), server.port());
    }
}
```

**Comment by spericas** [comment]
@dbazile You shouldn't need to use to `JacksonSupport` when using `JerseySupport`, as the latter comes with its own support for it. Can you try removing `JacksonSupport` and its jar and leaving the Jersey jar for Jackson?

**Comment by dbazile** [comment]
@spericas: Voila, problem solved.  Thanks! :)

I'll leave this behind for posterity in case someone else runs into the same issue:

```diff
diff --git a/build.gradle b/build.gradle
index d928aeb..0f17b84 100644
--- a/build.gradle
+++ b/build.gradle
@@ -13,7 +13,6 @@ dependencies {
     compile 'io.helidon:helidon-bom:1.1.1'
     compile 'io.helidon.webserver:helidon-webserver:1.1.1'
     compile 'io.helidon.webserver:helidon-webserver-jersey:1.1.1'
-    compile 'io.helidon.media.jackson:helidon-media-jackson-server:1.1.1'
 
     compile 'org.glassfish.jersey.media:jersey-media-json-jackson:2.26'
 }
diff --git a/src/main/java/foo/Main.java b/src/main/java/foo/Main.java
index 5ee2fe1..6cb6f8d 100644
--- a/src/main/java/foo/Main.java
+++ b/src/main/java/foo/Main.java
@@ -7,7 +7,6 @@ import javax.ws.rs.GET;
 import javax.ws.rs.Path;
 import javax.ws.rs.Produces;
 
-import io.helidon.media.jackson.server.JacksonSupport;
 import io.helidon.webserver.Routing;
 import io.helidon.webserver.ServerConfiguration;
 import io.helidon.webserver.WebServer;
@@ -30,7 +29,6 @@ public final class Main {
                         .port(5000)
                         .build(),
                 Routing.builder()
-                        .register(JacksonSupport.create())
                         .register(
                                 JerseySupport.builder()
                                         .register(FooResource.class)
```

**Comment by johnoraclestites** [comment]
I tried this same approach with the same result so it might be worth updating the docs to specify that if you want jackson within jersey that you implement this way. From the docs it seemed the answer was to just register the different support classes.
