### ISSUE TITLE
Graal: ReflectionUtils using MethodHandle

### ISSUE THREAD

**Issue by dansiviter** [oracle/helidon#791]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version: `1.1.2`
* Helidon SE or Helidon MP: `MP`
* JDK version: `1.8.0_212, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/graalvm-ce-19.0.2/Contents/Home/jre`
* OS: OS name: `"mac os x", version: "10.14.5", arch: "x86_64", family: "mac"`
* Docker version (if applicable): N/A

----------

## Problem Description
Although potentially premature to be trying Helidon MP and Graal (see #716), having given it a go I hit an issue which may need looking into. It appears due to the usage of `java.lang.invoke.MethodHandle` the class `io.helidon.config.objectmapping.ReflectionUtil` fails with Graal native-image creation:

```
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Invoke with MethodHandle argument could not be reduced to at most a single call: java.lang.invoke.MethodHandle.bindTo(Object)
Trace: 
	at parsing java.lang.invoke.MethodHandleImpl.makePairwiseConvertByEditor(MethodHandleImpl.java:221)
Call path from entry point to java.lang.invoke.MethodHandleImpl.makePairwiseConvertByEditor(MethodHandle, MethodType, boolean, boolean): 
	at java.lang.invoke.MethodHandleImpl.makePairwiseConvertByEditor(MethodHandleImpl.java:207)
	at java.lang.invoke.MethodHandleImpl.makePairwiseConvert(MethodHandleImpl.java:194)
	at java.lang.invoke.MethodHandleImpl.throwException(MethodHandleImpl.java:1078)
	at java.lang.invoke.MethodHandleImpl.fakeMethodHandleInvoke(MethodHandleImpl.java:1096)
	at java.lang.invoke.MethodHandles$Lookup.unreflectForMH(MethodHandles.java:1197)
	at java.lang.invoke.MethodHandles$Lookup.unreflect(MethodHandles.java:1183)
	at io.helidon.config.objectmapping.ReflectionUtil.unreflect(ReflectionUtil.java:254)
	at io.helidon.config.objectmapping.ReflectionUtil$$Lambda$6246/1503004304.apply(Unknown Source)
	at org.glassfish.jersey.internal.util.collection.Views$1$1.next(Views.java:96)
	at java.util.AbstractCollection.containsAll(AbstractCollection.java:317)
	at java.util.RegularEnumSet.containsAll(RegularEnumSet.java:199)
	at com.oracle.svm.core.amd64.AMD64CPUFeatureAccess.verifyHostSupportsArchitecture(AMD64CPUFeatureAccess.java:172)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:131)
	at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
```

## Steps to reproduce
Create a Helidon MP application using JAX-RS.

**Comment by tomas-langer** [comment]
There reason we separated `helidon-config-object-mapping` into its own module is the usage of method handles.
This cannot be done correctly in java9+ without usage of method handles.

You should not use this library when using GraalVM native-image.

Also in general, there is no way to use Helidon MP with GraalVM native-image, and although we have an issue open for it, it is most likely not going to happen in near future.

The real problems come with CDI and its features that are not compatible with native image ahead of time compilation.

**Comment by dansiviter** [comment]
Thanks for the explanation. It's a real shame MP isn't supported as that would gives the benefits of standards with the speed of native-image. Would it be worth documenting this behaviour somewhere?

**Comment by tomas-langer** [comment]
The issue #716 should be used to gather information about MP and native-image.
