### ISSUE TITLE
SSE support - If client closes connection, SseEventSink isn't aware of it

### ISSUE THREAD

**Issue by mhorejsi** [oracle/helidon#806]
## Environment Details
* Helidon Version: 1.1.1
* Helidon MP
* JDK version: 11

I'd like to use Jersey SSE support with Helidon - https://jersey.github.io/documentation/latest/sse.html. 

I added _jersey-media-sse_ dependency to my classpath and wrote a simple resource that accepts SseEventSink and passes it to CommandResultConsumer that writes data to the sink.

Sample resource:
```java
@GET
@Path("results")
@Produces(MediaType.SERVER_SENT_EVENTS)
public void listenToEvents(@Context SseEventSink eventSink) {
    commandResultConsumer.addEventSink(eventSink);
}
```

CommandResultConsumer:
```java
private final List<SseEventSink> eventSinks  = ...
...
while (true) {
    Record record = pollRecordFromKafka();
    OutboundEvent event = createOutboundEvent(record);
    for (SseEventSink sink : eventSinks) {
        CompletionStage<?> stage = sink.send(event);
        stage.exceptionally(ex -> {
            // this is never called, stage always completes successfully even if client closes the connection
        });
        sink.isClosed(); // always returns false 
    }
}
```

When SSE client closes the connection, the CompletionStage returned by SseEventSink#send(OutboundSseEvent) always completes successfully. The same applies to SseEventSink#isClosed() method. It always returns false.

I can see in Helidon logs that the connection is closed, but it does't propagate to EventSink.
```
2019-06-21 09:56:15,248 FINEST io.helidon.webserver.BareResponseImpl (reqID: 1) Sending data chunk on event loop thread.
2019-06-21 09:56:15,249 FINEST io.helidon.webserver.BareResponseImpl (reqID: 1) Sending data chunk
2019-06-21 09:56:15,248 TRACE io.helidon.webserver.BareResponseImpl (reqID: 1) Response completion failed!
java.lang.IllegalStateException: Failure when sending a content!
        at io.helidon.webserver.BareResponseImpl.lambda$completeOnFailureListener$8(BareResponseImpl.java:222) ~[helidon-webserver-1.1.1.jar:1.1.1]
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:502) [netty-common-4.1.34.Final.jar:4.1.34.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:495) [netty-common-4.1.34.Final.jar:4.1.34.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:474) [netty-common-4.1.34.Final.jar:4.1.34.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:415) [netty-common-4.1.34.Final.jar:4.1.34.Final]
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:540) [netty-common-4.1.34.Final.jar:4.1.34.Final]
        at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:533) [netty-common-4.1.34.Final.jar:4.1.34.Final]
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:114) [netty-common-4.1.34.Final.jar:4.1.34.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:1018) [netty-transport-4.1.34.Final.jar:4.1.34.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:874) [netty-transport-4.1.34.Final.jar:4.1.34.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1365) [netty-transport-4.1.34.Final.jar:4.1.34.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:706) [netty-transport-4.1.34.Final.jar:4.1.34.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:698) [netty-transport-4.1.34.Final.jar:4.1.34.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:780) [netty-transport-4.1.34.Final.jar:4.1.34.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:691) [netty-transport-4.1.34.Final.jar:4.1.34.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:700) [netty-transport-4.1.34.Final.jar:4.1.34.Final]
        at io.netty.channel.AbstractChannelHandlerContext.access$1700(AbstractChannelHandlerContext.java:38) [netty-transport-4.1.34.Final.jar:4.1.34.Final]
        at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:1091) [netty-transport-4.1.34.Final.jar:4.1.34.Final]
        at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1138) [netty-transport-4.1.34.Final.jar:4.1.34.Final]
        at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:1062) [netty-transport-4.1.34.Final.jar:4.1.34.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-common-4.1.34.Final.jar:4.1.34.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [netty-common-4.1.34.Final.jar:4.1.34.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:495) [netty-transport-4.1.34.Final.jar:4.1.34.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) [netty-common-4.1.34.Final.jar:4.1.34.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.34.Final.jar:4.1.34.Final]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: io.netty.channel.ExtendedClosedChannelException
        at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source) ~[netty-transport-4.1.34.Final.jar:4.1.34.Final]
```

**Comment by spericas** [comment]
@mhorejsi Is it all possible for you to try this with Helidon 1.3.0? I've put together a simple example using `curl` as client, and so far, I have not been able to reproduce the stack trace.

**Comment by mhorejsi** [comment]
@spericas I just tried it with Helidon 1.3.0 and the issue is still reproducible.  Please note that to see the exception in log file, Helidon log level needs to be set to TRACE.

```2019-09-30 10:18:56,789 TRACE io.helidon.webserver.BareResponseImpl (reqID: 1) Response completion failed!
java.lang.IllegalStateException: Failure when sending a content!
        at io.helidon.webserver.BareResponseImpl.lambda$completeOnFailureListener$7(BareResponseImpl.java:240) ~[helidon-webserver-1.3.0.jar:1.3.0]
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:500) [netty-common-4.1.39.Final.jar:4.1.39.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:493) [netty-common-4.1.39.Final.jar:4.1.39.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:472) [netty-common-4.1.39.Final.jar:4.1.39.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:413) [netty-common-4.1.39.Final.jar:4.1.39.Final]
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:538) [netty-common-4.1.39.Final.jar:4.1.39.Final]
        at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:531) [netty-common-4.1.39.Final.jar:4.1.39.Final]
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:111) [netty-common-4.1.39.Final.jar:4.1.39.Final]
        at io.netty.util.concurrent.PromiseCombiner.tryPromise(PromiseCombiner.java:170) [netty-common-4.1.39.Final.jar:4.1.39.Final]
        at io.netty.util.concurrent.PromiseCombiner.access$600(PromiseCombiner.java:35) [netty-common-4.1.39.Final.jar:4.1.39.Final]
        at io.netty.util.concurrent.PromiseCombiner$1.operationComplete0(PromiseCombiner.java:62) [netty-common-4.1.39.Final.jar:4.1.39.Final]
        at io.netty.util.concurrent.PromiseCombiner$1.operationComplete(PromiseCombiner.java:44) [netty-common-4.1.39.Final.jar:4.1.39.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:500) [netty-common-4.1.39.Final.jar:4.1.39.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:474) [netty-common-4.1.39.Final.jar:4.1.39.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:413) [netty-common-4.1.39.Final.jar:4.1.39.Final]
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:538) [netty-common-4.1.39.Final.jar:4.1.39.Final]
        at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:531) [netty-common-4.1.39.Final.jar:4.1.39.Final]
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:111) [netty-common-4.1.39.Final.jar:4.1.39.Final]
        at io.netty.util.internal.PromiseNotificationUtil.tryFailure(PromiseNotificationUtil.java:64) [netty-common-4.1.39.Final.jar:4.1.39.Final]
        at io.netty.channel.ChannelOutboundBuffer.safeFail(ChannelOutboundBuffer.java:721) [netty-transport-4.1.39.Final.jar:4.1.39.Final]
        at io.netty.channel.ChannelOutboundBuffer.remove0(ChannelOutboundBuffer.java:306) [netty-transport-4.1.39.Final.jar:4.1.39.Final]
        at io.netty.channel.ChannelOutboundBuffer.failFlushed(ChannelOutboundBuffer.java:658) [netty-transport-4.1.39.Final.jar:4.1.39.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:738) [netty-transport-4.1.39.Final.jar:4.1.39.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:940) [netty-transport-4.1.39.Final.jar:4.1.39.Final]
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:356) [netty-transport-4.1.39.Final.jar:4.1.39.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:895) [netty-transport-4.1.39.Final.jar:4.1.39.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1383) [netty-transport-4.1.39.Final.jar:4.1.39.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:749) [netty-transport-4.1.39.Final.jar:4.1.39.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:741) [netty-transport-4.1.39.Final.jar:4.1.39.Final]
        at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:727) [netty-transport-4.1.39.Final.jar:4.1.39.Final]
        at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:125) [netty-transport-4.1.39.Final.jar:4.1.39.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:749) [netty-transport-4.1.39.Final.jar:4.1.39.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:741) [netty-transport-4.1.39.Final.jar:4.1.39.Final]
        at io.netty.channel.AbstractChannelHandlerContext.access$2100(AbstractChannelHandlerContext.java:56) [netty-transport-4.1.39.Final.jar:4.1.39.Final]
        at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1150) [netty-transport-4.1.39.Final.jar:4.1.39.Final]
        at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:1073) [netty-transport-4.1.39.Final.jar:4.1.39.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-common-4.1.39.Final.jar:4.1.39.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416) [netty-common-4.1.39.Final.jar:4.1.39.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515) [netty-transport-4.1.39.Final.jar:4.1.39.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918) [netty-common-4.1.39.Final.jar:4.1.39.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.39.Final.jar:4.1.39.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.39.Final.jar:4.1.39.Final]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.io.IOException: Broken pipe
        at sun.nio.ch.FileDispatcherImpl.writev0(Native Method) ~[?:?]
        at sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:51) ~[?:?]
        at sun.nio.ch.IOUtil.write(IOUtil.java:182) ~[?:?]
        at sun.nio.ch.IOUtil.write(IOUtil.java:130) ~[?:?]
        at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:496) ~[?:?]
        at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:420) ~[netty-transport-4.1.39.Final.jar:4.1.39.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:928) ~[netty-transport-4.1.39.Final.jar:4.1.39.Final]
        ... 19 more
```

> I've put together a simple example using curl as client, and so far, I have not been able to reproduce the stack trace.

When you disconnect your curl and send some message to the sink, does SseEventSink.isClosed() return true? I'm using JerseySseClient and it doesn't (and client type shouldn't matter).

If you still struggle with reproducing of this issue, let me know. I can prepare a simple app for you.

**Comment by spericas** [comment]
@mhorejsi I thought I had set the logging level, but I can check that again. In any case, I did take a closer look at the code in more detail, and clearly there is a _disconnect_ between Jersey and Helidon here. 

Fixing this problem would require some important re-design given that the current approach makes it difficult to propagate error conditions such as the one you found.

**Comment by mhorejsi** [comment]
The fix is very important for us, because our application (which is currently in production) heavily uses SSE. 

In our use-case, server sends event(s) to all connected (i.e. not-closed) SseEventSink(s). And since we cannot determine if SseEventSink is closed, server will send it to all registered SseEventSinks. Number of registered (= opened) SseEventSinks can grow indefinitely, which can cause memory / performance issues.

Is there any workaround to discover is SseEventSink is closed?

**Comment by spericas** [comment]
@mhorejsi I understand the importance of your use case. Let me get back to you shortly with some suggestions on what we can do here.

**Comment by spericas** [comment]
https://github.com/oracle/helidon/pull/1076
