### ISSUE TITLE
Metrics TCK intermittent test failure

### ISSUE THREAD

**Issue by barchetta** [oracle/helidon#865]
## Environment Details
* Helidon Version: 1.2.0
*  Helidon MP
* JDK version: 11

----------

## Problem Description
Saw these intermittent test failures during a release build. You can see the full build at https://app.wercker.com/Helidon/helidon/runs/build/5d3f36de21ca08000854a106?step=5d3f3714001212000732633b 
A retry passed. The failures were:

```
Tests run: 140, Failures: 5, Errors: 0, Skipped: 0, Time elapsed: 32.417 sec <<< FAILURE! - in TestSuite
testSnapshot99thPercentile on testSnapshot99thPercentile(org.eclipse.microprofile.metrics.tck.HistogramTest)(org.eclipse.microprofile.metrics.tck.HistogramTest)  Time elapsed: 0.011 sec  <<< FAILURE!
java.lang.AssertionError: expected:<980.0> but was:<990.0>
    at org.eclipse.microprofile.metrics.tck.HistogramTest.testSnapshot99thPercentile(HistogramTest.java:148)

testSnapshotMean on testSnapshotMean(org.eclipse.microprofile.metrics.tck.HistogramTest)(org.eclipse.microprofile.metrics.tck.HistogramTest)  Time elapsed: 0.002 sec  <<< FAILURE!
java.lang.AssertionError: expected:<506.3> but was:<508.20847125897285>
    at org.eclipse.microprofile.metrics.tck.HistogramTest.testSnapshotMean(HistogramTest.java:172)

testMetricRegistry on testMetricRegistry(org.eclipse.microprofile.metrics.tck.HistogramTest)(org.eclipse.microprofile.metrics.tck.HistogramTest)  Time elapsed: 0.002 sec  <<< FAILURE!
java.lang.AssertionError: expected:<480.0> but was:<490.0>
    at org.eclipse.microprofile.metrics.tck.HistogramTest.testMetricRegistry(HistogramTest.java:108)

testSnapshotMedian on testSnapshotMedian(org.eclipse.microprofile.metrics.tck.HistogramTest)(org.eclipse.microprofile.metrics.tck.HistogramTest)  Time elapsed: 0.002 sec  <<< FAILURE!
java.lang.AssertionError: expected:<480.0> but was:<490.0>
    at org.eclipse.microprofile.metrics.tck.HistogramTest.testSnapshotMedian(HistogramTest.java:178)

testSnapshot75thPercentile on testSnapshot75thPercentile(org.eclipse.microprofile.metrics.tck.HistogramTest)(org.eclipse.microprofile.metrics.tck.HistogramTest)  Time elapsed: 0.003 sec  <<< FAILURE!
java.lang.AssertionError: expected:<750.0> but was:<760.0>
    at org.eclipse.microprofile.metrics.tck.HistogramTest.testSnapshot75thPercentile(HistogramTest.java:130)


Results :

Failed tests:
  HistogramTest.testMetricRegistry:108 expected:<480.0> but was:<490.0>
  HistogramTest.testSnapshot75thPercentile:130 expected:<750.0> but was:<760.0>
  HistogramTest.testSnapshot99thPercentile:148 expected:<980.0> but was:<990.0>
  HistogramTest.testSnapshotMean:172 expected:<506.3> but was:<508.20847125897285>
  HistogramTest.testSnapshotMedian:178 expected:<480.0> but was:<490.0>

Tests run: 140, Failures: 5, Errors: 0, Skipped: 0
```

**Comment by spericas** [comment]
I believe these are the same old intermittent failures related to runs taking too long to complete. I recall histograms have inherent data loss over time and longer runs result in different values. We should see if the TCKs for the newer version address this.

**Comment by barchetta** [comment]
I haven't seen this in a while. Closing.
