### ISSUE TITLE
Zipkin tracing does not work with MP

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#896]
When using Helidon 1.2.0 with Zipkin tracer and MP, the following exception happens:

```
2019.08.13 11:57:24 INFO io.helidon.webserver.NettyWebServer Thread[nioEventLoopGroup-2-1,10,main]: Channel 'admin' started: [id: 0x4b1068b1, L:/127.0.0.1:9081]
2019.08.13 11:57:24 INFO io.helidon.microprofile.server.ServerImpl Thread[nioEventLoopGroup-2-1,10,main]: Server started on http://localhost:8081 in 252 milliseconds.
http://localhost:8081/greet
2019.08.13 11:57:27 WARNING io.helidon.microprofile.server.ServerImpl.jersey Thread[helidon-1,5,main]: Internal server error
java.lang.IllegalArgumentException: Span must be an instance of brave.opentracing.BraveSpan, but was class io.helidon.tracing.zipkin.ZipkinSpan
	at brave.opentracing.BraveScopeManager.activate(BraveScopeManager.java:75)
	at brave.opentracing.BraveScopeManager.activate(BraveScopeManager.java:26)
	at io.helidon.tracing.jersey.AbstractTracingFilter.filter(AbstractTracingFilter.java:84)
	at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:108)
	at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:44)
	at org.glassfish.jersey.process.internal.Stages.process(Stages.java:173)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:245)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
	at io.helidon.webserver.jersey.JerseySupport$JerseyHandler.lambda$doAccept$3(JerseySupport.java:265)
	at io.helidon.common.context.Contexts.runInContext(Contexts.java:98)
	at io.helidon.common.context.ContextAwareExecutorImpl.lambda$wrap$1(ContextAwareExecutorImpl.java:129)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by tomas-langer** [comment]
Works fine with Jaeger tracing
