### ISSUE TITLE
SE native-image build fails when zipkin is used

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#907]
Building a GraalVM image fails for SE if you add Zipkin tracing per step 11.

      ServerConfiguration serverConfig =
          ServerConfiguration.builder(config.get("server"))
              .tracer(TracerBuilder.create(config.get("tracing")).buildAndRegister())
              .build();

Here is the error and stack

[WARNING] Error: No instances are allowed in the image heap for a class that is initialized or reinitialized at image runtime: zipkin2.codec.SpanBytesEncoder$1. Try marking this class for build-time initialization with --initialize-at-build-time=zipkin2.codec.SpanBytesEncoder$1
[WARNING] Trace: 	object io.helidon.tracing.zipkin.ZipkinTracerBuilder$Version
[WARNING] 	method io.helidon.tracing.zipkin.ZipkinTracerBuilder.configApiVersion(String)
[WARNING] Call path from entry point to io.helidon.tracing.zipkin.ZipkinTracerBuilder.configApiVersion(String): 
[WARNING] 	at io.helidon.tracing.zipkin.ZipkinTracerBuilder.configApiVersion(ZipkinTracerBuilder.java:367)
[WARNING] 	at io.helidon.tracing.zipkin.ZipkinTracerBuilder$$Lambda$1022/572759193.accept(Unknown Source)
[WARNING] 	at io.helidon.webserver.RequestRouting.fireNewWebServer(RequestRouting.java:101)
[WARNING] 	at io.helidon.webserver.WebServer$Builder.build(WebServer.java:321)
[WARNING] 	at io.helidon.webserver.WebServer.create(WebServer.java:176)
[WARNING] 	at io.helidon.examples.quickstart.se.Main.startServer(Main.java:75)
[WARNING] 	at io.helidon.examples.quickstart.se.Main.main(Main.java:49)
[WARNING] 	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:153)

Thanks @pfmackin for reporting this issue on https://github.com/tomas-langer/helidon-conference/issues/4

**Comment by tomas-langer** [comment]
Resolved by #915
