### ISSUE TITLE
JaegerTracerBuilder should handle missing config more gracefully

### ISSUE THREAD

**Issue by mlagally** [oracle/helidon#978]
## Environment Details
* Helidon Version: 1.6.1
* Helidon SE
* JDK version: 11
* OS: OSX, Linux
* Docker version (if applicable):

----------

## Problem Description

Our application dies due to some missing config key for a component we are not using.
I guess, our application could just continue if it does not use the tracer, so  the implementation should treat this situation with a warning and not throw an exception.

2019-Aug-30 13:10:34 PM [main] ERROR com.oracle.microservices.oci.internal.UncaughtExceptionHandler - Uncaught exception occurred
java.lang.IllegalArgumentException: Configuration must at least contain the 'service' key
        at io.helidon.tracing.jaeger.JaegerTracerBuilder.config(JaegerTracerBuilder.java:308) ~[helidon-tracing-jaeger-1.2.0.jar:1.2.0]
        at io.helidon.tracing.jaeger.JaegerTracerBuilder.config(JaegerTracerBuilder.java:151) ~[helidon-tracing-jaeger-1.2.0.jar:1.2.0]
        at io.helidon.tracing.TracerBuilder.create(TracerBuilder.java:131) ~[helidon-tracing-1.2.0.jar:1.2.0]
        at io.helidon.microprofile.tracing.MpTracingService.configure(MpTracingService.java:40) ~[helidon-microprofile-tracing-1.2.0.jar:1.2.0]
        at io.helidon.microprofile.server.ServerImpl.lambda$loadExtensions$7(ServerImpl.java:212) ~[helidon-microprofile-server-1.2.0.jar:1.2.0]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at io.helidon.microprofile.server.ServerImpl.loadExtensions(ServerImpl.java:211) ~[helidon-microprofile-server-1.2.0.jar:1.2.0]
        at io.helidon.microprofile.server.ServerImpl.<init>(ServerImpl.java:111) ~[helidon-microprofile-server-1.2.0.jar:1.2.0]
        at io.helidon.microprofile.server.Server$Builder.doBuild(Server.java:259) ~[helidon-microprofile-server-1.2.0.jar:1.2.0]
        at io.helidon.common.context.Contexts.runInContext(Contexts.java:118) ~[helidon-common-context-1.2.0.jar:1.2.0]
        at io.helidon.microprofile.server.Server$Builder.build(Server.java:201) ~[helidon-microprofile-server-1.2.0.jar:1.2.0]
        at com.oracle.microservices.microprofile.MicroProfileServer.start(MicroProfileServer.java:48) ~[microprofile-support-1.4.1.jar:?]
        at com.oracle.microservices.microprofile.MicroProfileServer.main(MicroProfileServer.java:177) ~[microprofile-support-1.4.1.jar:?]
Weld SE container bcc4bc1c-b1d2-4456-8b2c-3593957b1a90 shut down by shutdown hook

**Comment by tomas-langer** [comment]
The failure is happening because you are using the component - the fact that `helidon-jaeger-tracing` is on your classpath means you use Jaeger tracing, and Helidon attempts to configure it.
Failure to configure it fails startup, as one of your components (that you intentionally wanted by placing it on the classpath) cannot be configured.

We could allow this if you set `tracing.enabled` to `false` - would this be helpful for you? 

If you do not want to use jaeger anywhere, just remove it from your dependencies.

**Comment by mlagally** [comment]
@tomas-langer We are using a large component (microprofile-db) that includes jaeger as one of it's components. 
We just want to *use* the microprofile-db and cannot break it up into subcomponents or remove dependencies.

 For us it would be sufficient, if there is no related config entry present, the helidon-jaeger-tracing component would assume that it is not enabled.

**Comment by tomas-langer** [comment]
Hi, you have the option to exclude the `io.helidon.tracing:helidon-tracing-jaeger` dependency from your `microprofile-db` dependency.
Maybe you could ask the team responsible for `microprofile-db` to remove that dependency from their module? 
The tracer configuration should be left to the microservice implementation (that would include `jaeger`, `zipkin` or nothing).

The reason we fail is to tell you that you have misconfigured your service and you would not get tracing. Also the tracing is not `jaeger` specific - the configuration does not mention `jaeger` at all.
You need `tracing.service` defined, or (if that is desired) `tracing.enabled` set to `false`

The failure is intentional and the product works as designed.
